%[DOCS AUTOGENERATED]
function [figs_in_RE, figs_in_AOR, tabs_in_RE, tabs_in_AOR] = fig_tab_pub_mapping()
% Function fig_tab_pub_mapping
%
% :returns: figs_in_RE
% :returns: figs_in_AOR
% :returns: tabs_in_RE
% :returns: tabs_in_AOR

%% numbers
num_figs_RE = 29;
num_figs_AOR = 61;
num_tabs_AOR = 2;
num_tabs_RE = 6;

%% RE figures

figs_in_RE = cell([1,num_figs_RE]);
figs_in_RE{1}  = 'ReadNonMatlabFigs.RM3_image';
% 2: modeling methodology
figs_in_RE{2}  = 'ReadNonMatlabFigs.methodology_flowchart';
figs_in_RE{3}  = 'ReadNonMatlabFigs.xdsm';
% archs
figs_in_RE{4}  = 'ReadNonMatlabFigs.control_analysis_flowcharts';
figs_in_RE{5} = 'ReadNonMatlabFigs.optimization_flowchart';
% 4: results
figs_in_RE{6} = 'DesignSpaceExploration.experiments_ratios';
figs_in_RE{7} = 'Comparison.overlaid_geometry';
figs_in_RE{8} = 'Comparison.overlaid_hydro_coeffs';
figs_in_RE{9} = 'Comparison.probability_CDF';
figs_in_RE{10} = 'GradientOptimFigFunc.single_obj_opt_power_matrix';
figs_in_RE{11} = 'GradientOptimFigFunc.lagrange_multipliers';
figs_in_RE{12} = 'GradientOptimFigFunc.delta_x';
figs_in_RE{13} = 'Multistart.multistart_convergence_tree';
figs_in_RE{14} = 'Multistart.multistart_bar_chart';
figs_in_RE{15} = 'ParamSensitivities.re_optim_objective_tornado';
figs_in_RE{16} = 'ParamSensitivities.re_optim_design_tornado_J1';
figs_in_RE{17} = 'ParamSensitivities.re_optim_design_tornado_J2';
figs_in_RE{18} = 'ParetoFigFunc.pareto_front_with_design_images';
figs_in_RE{19} = 'ParetoFigFunc.pareto_front_LCOE_contours';
figs_in_RE{20} = 'ParetoFigFunc.pareto_heuristics';
figs_in_RE{21} = 'ParetoFigFunc.pareto_constraint_activity_reactive';
figs_in_RE{22} = 'AllFigCompare.runtime_bar_chart';
figs_in_RE{23} = 'ParetoSweep.sweep_num_seeds';
% appendix A - supplementary results
figs_in_RE{24} = 'GradientOptimFigFunc.single_obj_convergence';
figs_in_RE{25} = 'Multistart.multistart_parallel_coordinates';
% appendix E - optimization process
figs_in_RE{26} = 'ParamSensitivities.post_optim_re_optim_objective_grid';
figs_in_RE{27} = 'ParamSensitivities.post_optim_design_grid';
figs_in_RE{28} = 'ParamSensitivities.re_optim_design_grid';
% graphical abstract (unnumbered so at the end)
figs_in_RE{29}  = 'ReadNonMatlabFigs.graphical_abstract_optim';

%% AOR figures

figs_in_AOR = cell([1,num_figs_AOR]);
% 1: introduction
figs_in_AOR{1}  = 'ReadNonMatlabFigs.taxonomy';
% 2: model structure
figs_in_AOR{2}  = 'ReadNonMatlabFigs.xdsm';
figs_in_AOR{3}  = 'ReadNonMatlabFigs.control_method_venn_diagram';
figs_in_AOR{4}  = 'ReadNonMatlabFigs.control_analysis_flowcharts';
% 3: module details
figs_in_AOR{5}  = 'ReadNonMatlabFigs.dimensions';
figs_in_AOR{6}  = 'ReadNonMatlabFigs.MEEM_geometry';
figs_in_AOR{7}  = 'ReadNonMatlabFigs.circuit_intrinsic';
figs_in_AOR{8}  = 'ReadNonMatlabFigs.mod_freq_domain_ctrl_synthesis';
figs_in_AOR{9}  = 'ReadNonMatlabFigs.mod_freq_domain_ctrl_evaluation';
figs_in_AOR{10}  = 'DescFcns.saturation_desc_fcn'; % subfig (a), combined with {52}
figs_in_AOR{11}  = 'RunSingleFigFunc.nominal_power_matrix';
figs_in_AOR{12}  = 'ReadNonMatlabFigs.FBD';
% 4: validation and benchmarking
figs_in_AOR{13} = 'Wecsim.wecsim_wcsm_multi__histogram';
figs_in_AOR{14} = 'Runtime.sim_runtime';
figs_in_AOR{15} = 'Runtime.hydro_runtime_logscale';
figs_in_AOR{16} = 'Runtime.dynamics_runtime';
% 5: insights and discussion
figs_in_AOR{17} = 'SweepGeoms.sweep_geoms_line';
figs_in_AOR{18} = 'SweepGeoms.sweep_geoms_line_cwr_sa';
figs_in_AOR{19} = 'SweepGeoms.sweep_geoms_pareto_nondim';
figs_in_AOR{20} = 'DampingPlateStructures.damping_plate_aspect_ratio';
figs_in_AOR{21} = 'ForceSaturationFigFunc.power_force_sensitivity';
figs_in_AOR{22} = 'PtoSweep.pto_sweep';
figs_in_AOR{23} = 'DesignSpaceExploration.experiments_ratios';
figs_in_AOR{24} = 'RunSingleFigFunc.nominal_power_matrix';
% appendix A - hydro
figs_in_AOR{25} = 'ReadNonMatlabFigs.meem_dims';
figs_in_AOR{26} = 'Meem.meem_sparsity';
figs_in_AOR{27} = 'Meem.meem_validation';
figs_in_AOR{28} = 'Meem.meem_matching';
figs_in_AOR{29} = 'Meem.meem_convergence_vs_omega';
figs_in_AOR{30} = 'Meem.asymptotic_b_vector';
figs_in_AOR{31} = 'FitOlaya.case4_v1_auto_semilogx_khRxRpa4b_fv1';
% appendix B - dynamics (PTO kinematics, PTO circuit, QP, drag, slamming, WECSim)
figs_in_AOR{32} = 'ReadNonMatlabFigs.circuit_kinematics';
figs_in_AOR{33} = 'ReadNonMatlabFigs.circuit_pto';
figs_in_AOR{34} = 'QPCircles.qp_circles';
figs_in_AOR{35} = 'RunSingleFigFunc.qcqp_circles_nominal';
figs_in_AOR{36} = 'RunSingleFigFunc.ctrl_polar_plot_mult';
figs_in_AOR{37} = 'DragIntegral.drag_integral_B';     % subfig (a), combined with {53},{54}
figs_in_AOR{38} = 'Slamming.slamming_amplitude';
figs_in_AOR{39} = 'RunSingleFigFunc.slamming_model_comparison_float';
figs_in_AOR{40} = 'Wecsim.wecsim_wcsm_multi_drag_off_meem_off__power_mech_unsat'; % subfig, combined with {55},{56},{57}
figs_in_AOR{41} = 'Wecsim.wecsim_wcsm_multi_drag_on_meem_off__float_drag_force_fund'; % subfig, combined with {58},{59},{60}
figs_in_AOR{42} = 'Wecsim.accel_fourier_harmonics';
figs_in_AOR{43} = 'Wecsim.drag_force_desc_fcn';
figs_in_AOR{44} = 'Wecsim.position_THD_contour';
figs_in_AOR{45} = 'Wecsim.wecsim_rpt_multi_drag_on_meem_on__power_mech_unsat';
% appendix C - economic validation
figs_in_AOR{46} = 'Validation.cost_vs_N_WEC';
% appendix D - structures
figs_in_AOR{47} = 'ReadNonMatlabFigs.equivalent_stiffness';
figs_in_AOR{48} = 'ReadNonMatlabFigs.trapezoid';
figs_in_AOR{49} = 'ReadNonMatlabFigs.damping_plate_flowchart';
figs_in_AOR{50} = 'DampingPlateStructures.damping_plate_moment';  % subfig (a), combined with {61}
% graphical abstract (unnumbered so at the end)
figs_in_AOR{51}  = 'ReadNonMatlabFigs.graphical_abstract_modeling';
% extra subplot entries (additional MATLAB outputs for multi-panel figures)
figs_in_AOR{52} = 'DescFcns.drag_desc_fcn';                         % fig 10 subfig (b)
figs_in_AOR{53} = 'DragIntegral.drag_integral_G_m';                  % fig 37 subfig (b)
figs_in_AOR{54} = 'DragIntegral.drag_integral_G_p';                  % fig 37 subfig (c)
figs_in_AOR{55} = 'Wecsim.wecsim_wcsm_multi_drag_on_meem_off__power_mech_unsat';  % fig 40 subfig
figs_in_AOR{56} = 'Wecsim.wecsim_wcsm_multi_drag_off_meem_on__power_mech_unsat';  % fig 40 subfig
figs_in_AOR{57} = 'Wecsim.wecsim_wcsm_multi_drag_on_meem_on__power_mech_unsat';   % fig 40 subfig
figs_in_AOR{58} = 'Wecsim.wecsim_wcsm_multi_drag_on_meem_off__spar_drag_force_fund';  % fig 41 subfig
figs_in_AOR{59} = 'Wecsim.wecsim_wcsm_multi_drag_on_meem_off__spar_drag_force_phase';  % fig 41 subfig
figs_in_AOR{60} = 'Wecsim.wecsim_wcsm_multi_drag_on_meem_off__float_drag_force_phase'; % fig 41 subfig
figs_in_AOR{61} = 'DampingPlateStructures.damping_plate_deflection'; % fig 50 subfig (b)

%% TABLES

tabs_in_AOR = cell(1,num_tabs_AOR);
tabs_in_AOR{1} = 'Cost.cost_parameters';
tabs_in_AOR{2} = 'Validation.validation';

tabs_in_RE = cell(1,num_tabs_RE);
tabs_in_RE{1} = 'Constraints.constraints';
tabs_in_RE{2} = 'DesignVars.design_vars';
tabs_in_RE{3} = 'Parameters.parameters';
tabs_in_RE{4} = 'Comparison.optimal_design_vars';
tabs_in_RE{5} = 'Comparison.optimal_outputs';
tabs_in_RE{6} = 'LocationSensitivity.location_sensitivity';

% check for empty - this will happen if you forget to fill in any figs/tabs
empty = cellfun(@isempty,[figs_in_RE, figs_in_AOR, tabs_in_RE, tabs_in_AOR]);
assert(~any(empty))

% check that names all appear in the corresponding analysis class
figs_split = split([figs_in_AOR,figs_in_RE].', '.');
tabs_split = split([tabs_in_AOR,tabs_in_RE].', '.');
figs_classes = figs_split(:,1);
tabs_classes = tabs_split(:,1);
for i=1:length(figs_classes)
    class_name = figs_classes{i};
    if ~strcmp(class_name, 'ReadNonMatlabFigs')
        all_fig_names_this_class = feval(class_name,struct(),struct()).fig_names;
        this_fig_name = figs_split(i,2);
        valid = ismember(this_fig_name,all_fig_names_this_class);
        msg = [this_fig_name{1} ' defined in fig_tab_pub_mapping does not match any figures in ' ...
            class_name '. Valid figures: ' strjoin(all_fig_names_this_class,', ')];
        %assert(valid, msg)
        if ~valid
            warning(msg);
        end
    end
end
for i=1:length(tabs_classes)
    class_name = tabs_classes{i};
    if ~strcmp(class_name, 'ReadNonMatlabFigs')
        all_tab_names_this_class = feval(class_name,struct(),struct()).tab_names;
        this_tab_name = tabs_split(i,2);
        valid = ismember(this_tab_name,all_tab_names_this_class);
        msg = [this_tab_name{1} ' defined in fig_tab_pub_mapping does not match any tables in ' ...
            class_name '. Valid tables: ' strjoin(all_tab_names_this_class,', ')];
        %assert(valid, msg)
        if ~valid
            warning(msg);
        end
    end

end

end
