classdef FitOlaya < GenericAnalysis
    %FITOLAYA Analysis class for Olaya damping plate hydrodynamic coefficient fits
    %   Loads digitized data and creates derived signals in analysis_fcn;
    %   generates all fit and exploratory plots in post_process_fcn.

    properties
        fig_names = {
            ... % figs_original: paper figures 3b, 4b, 12a-12d; line; x=kRb, y=fbar
            'orig_3b_line_kRb_fbar', ...
            'orig_4b_line_kRb_fbar', ...
            'orig_12a_line_kRb_fbar', ...
            'orig_12b_line_kRb_fbar', ...
            'orig_12c_line_kRb_fbar', ...
            'orig_12d_line_kRb_fbar', ...
            ... % figs_case: case 2 and case 4 exploratory line/loglog plots
            'case24_compare_line_kRb_fnorm', ...
            'case2_line_khRxRp_fnorm', ...
            'case2_line_khRxRp_f_over_a2', ...
            'case2_line_khRxRpa2_f_over_a2', ...
            'case2_line_khRxRp_f_over_a2H0', ...
            'case2_line_khRxRp_f_over_RxRb_aH0', ...
            'case2_line_khRxRp_f_over_RxRb_aH0_expe1', ...
            'case2_line_khRxRp_f_over_RxRb_aH0_expe1e2', ...
            'case2_line_khRxRp_f_over_RxRb_aH0_expe2', ...
            'case2_line_khRxRpa2_f_over_RxRb_aH0_expe1', ...
            'case4_sub_line_kRb_fnorm', ...
            'case4_sub_line_khRxRp_fnorm', ...
            'case4_sub_line_khRxRp_f_H0_cosh_N0', ...
            'case4_sub_loglog_khRxRpb_f_H0_expe2_sqrtkh', ...
            'case4_sub_loglog_khRxRpb_f_H0_expe1_sqrtkh', ...
            'case4_sub_loglog_khRxRpb_f_H0_expe1', ...
            'case4_sub_loglog_khRxRpb_f_H0_expe1_b2sqrtkh', ...
            ... % figs_case4 / figs_sep: sep-alpha manual/auto fits + coefficients
            'case4_sep_manual_khRxRpa2b_f_H0_expe1_sqrtkh', ...
            'case4_sep_auto_lnkhRxRpa2b_lnf_H0_expe1_sqrtkh', ...
            'case4_sep_coeffs_vs_beta', ...
            'case4_sep_coeffs_vs_alpha', ...
            ... % figs_case4 / figs_v1 / manual: all-alpha manual semilogx; x=kh*alpha^4/beta
            'case4_v1_manual_semilogx_khRxRpa4b_fv1', ...
            'case4_v1_manual_scatter_actual_vs_pred', ...
            'case4_v1_manual_scatter_khRxRpa2b_frac_err', ...
            ... % figs_case4 / figs_v1 / auto: all-alpha auto semilogx; x=kh*alpha^4/beta
            'case4_v1_auto_semilogx_khRxRpa4b_fv1', ...
            'case4_v1_auto_scatter_actual_vs_pred', ...
            'case4_v1_auto_scatter_khRxRpa2b_frac_err', ...
            ... % figs_case4 / figs_v1 / coeffs
            'case4_v1_coeffs_vs_beta', ...
            'case4_v1_coeffs_vs_alpha', ...
            ... % figs_case4 / figs_v2 / manual: all-alpha manual loglog; x=kh*alpha^3/beta
            'case4_v2_manual_loglog_khRxRpa3b_fv2', ...
            'case4_v2_manual_scatter_actual_vs_pred', ...
            'case4_v2_manual_scatter_khRxRpa2b_frac_err', ...
            ... % figs_case4 / figs_v2 / auto: all-alpha auto loglog; x=kh*alpha^3/beta
            'case4_v2_auto_loglog_khRxRpa3b_fv2', ...
            'case4_v2_auto_scatter_actual_vs_pred', ...
            'case4_v2_auto_scatter_khRxRpa2b_frac_err', ...
            ... % figs_case4 / figs_v2 / coeffs
            'case4_v2_coeffs_vs_beta', ...
            'case4_v2_coeffs_vs_alpha', ...
            ... % figs_case4 / figs_v3: second-order fit in x^1.5 space; loglog
            'case4_v3_loglog_khRxRpa3b_fv2_x15', ...
            'case4_v3_scatter_actual_vs_pred', ...
            'case4_v3_scatter_khRxRpa2b_frac_err'};
        tab_names = {};
    end

    methods
        function obj = FitOlaya(varargin)
            obj = obj@GenericAnalysis(varargin{:});
            obj.extra_analysis_inputs = [obj.extra_analysis_inputs, ...
                {'./dev/hydro_coeffs/damping_plate/3b_black.csv', ...
                 './dev/hydro_coeffs/damping_plate/3b_blue.csv', ...
                 './dev/hydro_coeffs/damping_plate/3b_red.csv', ...
                 './dev/hydro_coeffs/damping_plate/4b_black.csv', ...
                 './dev/hydro_coeffs/damping_plate/4b_blue.csv', ...
                 './dev/hydro_coeffs/damping_plate/4b_red.csv', ...
                 './dev/hydro_coeffs/damping_plate/12a_black.csv', ...
                 './dev/hydro_coeffs/damping_plate/12a_blue.csv', ...
                 './dev/hydro_coeffs/damping_plate/12a_red.csv', ...
                 './dev/hydro_coeffs/damping_plate/12b_black.csv', ...
                 './dev/hydro_coeffs/damping_plate/12b_blue.csv', ...
                 './dev/hydro_coeffs/damping_plate/12b_red.csv', ...
                 './dev/hydro_coeffs/damping_plate/12c_black.csv', ...
                 './dev/hydro_coeffs/damping_plate/12c_blue.csv', ...
                 './dev/hydro_coeffs/damping_plate/12c_red.csv', ...
                 './dev/hydro_coeffs/damping_plate/12d_black.csv', ...
                 './dev/hydro_coeffs/damping_plate/12d_blue.csv', ...
                 './dev/hydro_coeffs/damping_plate/12d_red.csv'}];
        end
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
