function units = validation_units()
%VALIDATION_UNITS Returns a struct with the same fieldnames as the validation
%   output struct, where each field is a char giving the units of that field.
%   Units use LaTeX-compatible notation for use in the validation table.
%   Note: percent is written as \\%% so that MATLAB's fprintf correctly
%   outputs \% in the .tex file, which LaTeX renders as the percent sign.

units = struct(...
    'mass_f',         'kg', ...
    'mass_vc',        'kg', ...
    'mass_rp',        'kg', ...
    'mass_tot',       'kg', ...
    'vol_f',          'm$^3$', ...  % m^3 in LaTeX math mode inline
    'vol_s',          'm$^3$', ...
    'capex',          '\$', ...     % \$ renders as dollar sign in LaTeX
    'opex',           '\$', ...
    'LCOE',           '\$/kWh', ...
    'capex_struct',   '\$/WEC', ...
    'capex_PTO',      '\$/WEC', ...
    'capex_design',   '\$/WEC', ...
    'J_capex_design', 'M\$', ...
    'power_avg',      'W', ...
    'power_max',      'W', ...
    'force_heave',    'N', ...
    'FOS_spar',       '-', ...      % dimensionless
    'c_v',            '\\%%', ...   % fprintf turns \\%% into \% in the file; LaTeX renders \% as %
    'CB_f',           'm', ...
    'CG_f',           'm' ...
);
end
