% find the value of F_max for the nominal RM3 
% that is just high enough so there is no saturation

%[DOCS AUTOGENERATED]
function F_max_nom = find_nominal_inputs(b, p)
% Function find_nominal_inputs
%
% :param b: Design variable bounds struct
% :param p: Parameter struct
% :returns: F_max_nom

    X = [b.X_noms; 1];
    p.use_force_sat = false;
    [~, ~, ~, val] = simulation(X, p);
    F_max_nom = val.force_ptrain;

end
