%[DOCS AUTOGENERATED]
function intermed_result_struct = analysis_fcn(~,~)
% Function analysis_fcn
%
% :param ~: ~
% :param ~: ~
% :returns: Intermediate results struct (cached heavy analyses)
    % Run WEC-Sim dynamics validation
    runOnlyFewSeaStates = false;

    case_cell = make_all_cases(runOnlyFewSeaStates);
    filename_cell = run_wecsim_all_cases(case_cell);
    
    % Store results for post-processing
    intermed_result_struct.case_cell = case_cell;
    intermed_result_struct.filename_cell = filename_cell;
    intermed_result_struct.runOnlyFewSeaStates = runOnlyFewSeaStates;

end

function out_cell = run_wecsim_all_cases(case_cell)
    num_case_groups = size(case_cell,1);
    out_cell = cell(num_case_groups,1);
    for case_group_idx = 1:num_case_groups
        X = case_cell{case_group_idx,1};
        p_array = case_cell{case_group_idx,2};
        out_each_case_array = cell(1,numel(p_array));
        for p_idx = 1:numel(p_array)
            p = p_array(p_idx);
            out_each_case_array{p_idx} = run_wecsim_validation(X,p);
        end
        out_cell{case_group_idx} = out_each_case_array;
    end
end

function output_filename = run_wecsim_validation(X,p)
    % X and p need to be in the workspace for runRM3Parallel script to work right
    runRM3Parallel % this script uses p and modifies it, and saves output_filename to workspace
end

function case_cell = make_all_cases(runOnlyFewSeaStates)

    wecsim_X = [var_bounds('wecsim').X_noms; 1];
    report_X = [var_bounds('report').X_noms; 1];

    wecsim_mb_p_array = make_case_group('wecsim',true,runOnlyFewSeaStates);
    wecsim_sb_p_array = make_case_group('wecsim',false,runOnlyFewSeaStates);
    report_mb_p_array = make_case_group('report',true,runOnlyFewSeaStates);

    case_cell = {wecsim_X, wecsim_mb_p_array;
                wecsim_X, wecsim_sb_p_array;
                report_X, report_mb_p_array};

end

function p_array = make_case_group(geometry, multibody, runOnlyFewSeaStates)
    p = parameters(geometry);
    p.use_force_sat = false;
    p.use_power_sat = false;
    p.use_multibody = multibody;

    if runOnlyFewSeaStates
        p.Hs = p.Hs(3:4);
        p.T = p.T(4:5);
        p.JPD = p.JPD(3:4,4:5);
    end

    p_array = make_drag_hydro_param_combos(p);
end

% bonus that I have't checked yet: sweep drag, irregular waves, force saturation

function p_array = make_drag_hydro_param_combos(p_baseline)
    % drag off, wamit coeffs
    p_drag_off_wamit = p_baseline;
    p_drag_off_wamit.C_d_float = 0;
    p_drag_off_wamit.C_d_spar  = 0;
    p_drag_off_wamit.use_MEEM = false;
    
    % drag on, wamit coeffs
    p_drag_on_wamit = p_baseline;
    assert(p_drag_on_wamit.C_d_float>0 && p_drag_on_wamit.C_d_spar>0)
    p_drag_on_wamit.use_MEEM = false;

    % drag off, meem coeffs
    p_drag_off_meem = p_baseline;
    p_drag_off_meem.C_d_float = 0;
    p_drag_off_meem.C_d_spar  = 0;
    p_drag_off_meem.use_MEEM = true;

    % drag on, meem coeffs
    p_drag_on_meem = p_baseline;
    assert(p_drag_on_meem.C_d_float>0 && p_drag_on_meem.C_d_spar>0)
    p_drag_on_meem.use_MEEM = true;
    
    % array of all four
    p_array = [p_drag_off_wamit
               p_drag_on_wamit
               p_drag_off_meem
               p_drag_on_meem];

end
