%[AUTOGENERATED]
%[AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
            
            fig_array = [intermed_result_struct.fig_singlebody, ...
                        intermed_result_struct.fig_multibody, ...
                        intermed_result_struct.all_sea_states_fig];
            
            tab_array_display = {intermed_result_struct.validation_table};
            tab_array_latex = {intermed_result_struct.validation_table};
            
            tab_firstrows = {[]};
            tab_colspecs = {[]};
            
            end_result_struct.wecsim_validation_complete = true;
            end_result_struct.validation_errors = intermed_result_struct.validation_table;
end
