function [sigma_xx,shear,sigma_bending,sigma_axial,M_x,I_x,F_water,F_support,y] = damping_plate_func(E1,D_d,A_dt,theta_dt,L_dt,h_d,D_s,t_d,A_c1,A_c2,A_c3,P_hydrostatic1,P_hydrostatic2,P_hydrostatic3,x,x1,F_heave)
%DAMPING_PLATE_FUNC
%    [SIGMA_XX,SHEAR,SIGMA_BENDING,SIGMA_AXIAL,M_x,I_x,F_water,F_support,Y] = DAMPING_PLATE_FUNC(E1,D_d,A_dt,THETA_DT,L_dt,H_D,D_s,T_D,A_c1,A_c2,A_c3,P_hydrostatic1,P_hydrostatic2,P_hydrostatic3,X,X1,F_heave)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    25-Nov-2024 15:16:54

t2 = cos(theta_dt);
t3 = sin(theta_dt);
t4 = D_d.^2;
t5 = D_s.^2;
t6 = h_d.^3;
t7 = t_d.^3;
t8 = x.^2;
t9 = -D_s;
t10 = 1.0./L_dt;
t11 = D_d./2.0;
t12 = D_s./2.0;
t13 = F_heave./2.0;
t14 = D_d.*D_s.*F_heave.*1.8e+1;
t26 = D_d.*D_s.*(-1.0./2.0);
t15 = -t8;
t16 = D_d+t9;
t17 = -t11;
t18 = -t12;
t20 = t4./4.0;
t21 = t5./4.0;
t22 = -t14;
t23 = F_heave.*t4.*9.0;
t24 = F_heave.*t5.*9.0;
t25 = D_d.*D_s.*t3.*4.8e+1;
t27 = D_d.*E1.*t6.*8.0;
t28 = D_s.*E1.*t6.*8.0;
t29 = D_d.*E1.*t7.*8.0;
t30 = D_s.*E1.*t7.*8.0;
t32 = t3.*t4.*2.4e+1;
t33 = t3.*t5.*2.4e+1;
t31 = -t25;
t34 = 1.0./t16;
t35 = -t28;
t36 = -t29;
t37 = t11+t18;
t38 = t12+t17+1.0;
t48 = t22+t23+t24;
t49 = t20+t21+t26;
t39 = t37.^2;
t40 = t38.^2;
t41 = t8.*t13.*t34;
t42 = (F_heave.*t37)./4.0;
t50 = t31+t32+t33;
t52 = sqrt(t49);
t63 = t27+t30+t35+t36;
t43 = -t40;
t44 = sqrt(t39);
t47 = t15+t39;
t67 = 1.0./t63;
t70 = F_heave.*t16.*t38.*t52.*2.4e+1;
t71 = t3.*t16.*t38.*t52.*4.8e+1;
t45 = t44.^3;
t51 = sqrt(t47);
t62 = t39+t43;
t69 = t44.*t48;
t89 = t44.*t50.*t67;
t46 = F_heave.*t45.*4.0;
t53 = 1.0./t51;
t54 = h_d.*t51.*2.0;
t55 = t51.*t_d.*2.0;
t59 = (t6.*t51)./3.0;
t60 = (t7.*t51)./3.0;
t64 = sqrt(t62);
t56 = t53.*x;
t58 = -t55;
t61 = -t60;
t65 = t64.^3;
t66 = 1.0./t64;
t75 = t48.*t64;
t76 = F_heave.*t16.*t38.*t64.*1.2e+1;
t78 = t3.*t16.*t38.*t64.*2.4e+1;
t81 = t46+t69;
t82 = t50.*t64;
t57 = atan(t56);
t68 = F_heave.*t65.*4.0;
t72 = t38.*t66;
t74 = t54+t58;
t79 = -t76;
t80 = -t78;
t83 = t59+t61;
t97 = t67.*t81;
t73 = atan(t72);
t77 = 1.0./t74;
t84 = 1.0./t83;
t85 = F_heave.*t16.*t40.*t73.*1.2e+1;
t86 = t3.*t16.*t40.*t73.*2.4e+1;
t91 = t38.*t48.*t73;
t92 = t38.*t50.*t73;
t93 = F_heave.*t16.*t62.*t73.*1.2e+1;
t95 = t3.*t16.*t62.*t73.*2.4e+1;
t87 = -t85;
t88 = -t86;
t94 = -t93;
t96 = -t95;
t98 = t71+t80+t82+t88+t92+t96;
t99 = t68+t70+t75+t79+t87+t91+t94;
t100 = t67.*t98;
t101 = t67.*t99;
t102 = -t101;
t106 = -1.0./(A_dt.*E1.*t10.*(t89-t100)+1.0);
t107 = t97+t102;
t108 = A_dt.*E1.*t3.*t10.*t106.*t107;
t109 = (A_dt.*E1.*t3.*t10.*t107.*-2.0)./(A_dt.*E1.*t10.*(t89-t100)+1.0);
t112 = (A_dt.*D_d.*D_s.*E1.*t3.*t10.*t107.*4.8e+1)./(A_dt.*E1.*t10.*(t89-t100)+1.0);
t119 = A_dt.*E1.*t2.*t10.*t77.*t106.*t107;
t110 = F_heave+t109;
t115 = t13+t108;
t118 = t37.*t108;
t116 = t115.*x;
t117 = -t116;
t120 = t41+t42+t117+t118;
t121 = h_d.*t84.*t120;
sigma_xx = t119+t121;
if nargout > 1
    shear = [t77.*(-t13+(t13.*x1)./t37+(A_dt.*E1.*t3.*t10.*t107)./(A_dt.*E1.*t10.*(t89-t100)+1.0))];
end
if nargout > 2
    sigma_bending = t121;
end
if nargout > 3
    sigma_axial = t119;
end
if nargout > 4
    M_x = t120;
end
if nargout > 5
    I_x = (t6.*t51)./6.0-(t7.*t51)./6.0;
end
if nargout > 6
    F_water = t13;
end
if nargout > 7
    F_support = A_dt.*E1.*t10.*t106.*t107;
end
if nargout > 8
    et1 = -t67.*(t51.*(t14-t23-t24-t112+(A_dt.*E1.*t10.*t32.*t107)./(A_dt.*E1.*t10.*(t89-t100)+1.0)+(A_dt.*E1.*t10.*t33.*t107)./(A_dt.*E1.*t10.*(t89-t100)+1.0))-F_heave.*1.0./t53.^3.*4.0+t16.*x.*(F_heave.*t52+t52.*t109).*2.4e+1+t57.*x.*(t14-t23-t24-t112+(A_dt.*E1.*t10.*t32.*t107)./(A_dt.*E1.*t10.*(t89-t100)+1.0)+(A_dt.*E1.*t10.*t33.*t107)./(A_dt.*E1.*t10.*(t89-t100)+1.0))-t8.*t16.*t57.*t110.*1.2e+1-t16.*t51.*t110.*x.*1.2e+1+t16.*t57.*t110.*(t8-t39).*1.2e+1);
    et2 = -t67.*(t46-t44.*(t14-t23-t24-t112+(A_dt.*E1.*t10.*t32.*t107)./(A_dt.*E1.*t10.*(t89-t100)+1.0)+(A_dt.*E1.*t10.*t33.*t107)./(A_dt.*E1.*t10.*(t89-t100)+1.0)));
    y = et1+et2;
end
end
