%[AUTOGENERATED]
%[AUTOGENERATED]
function sigma = get_plate_stress(moment_per_length, y_max, h_eq)
% Function get_plate_stress
%
% :param moment_per_length: moment_per_length
% :param y_max: y_max
% :param h_eq: h_eq
% :returns: $\\sigma$
    M = moment_per_length;

    % see notebook p21 12/15/24
    sigma = 12 * M .* y_max ./ h_eq.^3;

end