name: mdocean
title: MDOcean
description: Multidisciplinary Design Optimization (MDO) to optimize
  an ocean wave energy converter (WEC).
environments:
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive via Docker.
pipeline:
  stages:
    build-paper:
      kind: latex
      target_path: pubs/renewable-energy-mdo/mdocean.tex
      environment: tex
      inputs:
        - pubs/renewable-energy-mdo/figs
        - pubs/renewable-energy-mdo/sections/
        - pubs/renewable-energy-mdo/tables
        - pubs/renewable-energy-mdo/references.bib
        - pubs/renewable-energy-mdo/numbers.tex
        - pubs/elsarticle-num-names.bst
        - mdocean/simulation/modules/OpenFLASH/pubs/src/meem-appendix.tex
publications:
  - path: pubs/renewable-energy-mdo/mdocean.pdf
    title: Journal Renewable Energy
    description:
    kind: journal-article
    stage: build-paper
    overleaf:
      project_id: 6753a38b61276b931380c29c
      wdir: pubs/renewable-energy-mdo
      sync_paths:
        - mdocean.tex
        - sections/
        - ../mdocean/simulation/modules/OpenFLASH/pubs/src/meem-appendix.tex
        - tables/
        - references.bib
        - numbers.tex
        - ../elsarticle-num-names.bst
      push_paths:
        - figs
      last_sync_commit: 9c9ebc1955e169a2f2bff30521f08919b875d820
  - path: pubs/UMERC-2025-grid-value/UMERC_2025_grid_value.pdf
    title: WEC optimization to maximize grid economic value and
      avoided emissions
    description:
    kind: conference-paper
    stage: build-pubs-umerc-2025-grid-value
    overleaf:
      project_id: 68516ba5bc36663bb61711a6
      wdir: pubs/UMERC-2025-grid-value
      sync_paths:
        - UMERC_2025_grid_value.tex
        - references.bib
        - logo.jpg
      push_paths:
        - figures
      last_sync_commit: deb4547f8c2893e267574e6f36448e5c54238b97
