name: mdocean
title: MDOcean
description: Multidisciplinary Design Optimization (MDO) to optimize 
  an ocean wave energy converter (WEC).
environments:
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive via Docker.
  py-jupyter-matlab:
    path: requirements.txt
    kind: uv-venv
    prefix: .venv
pipeline:
  stages:
    run-tutorial:
      kind: jupyter-notebook
      environment: py-jupyter-matlab
      notebook_path: tutorials/tutorial.ipynb
      inputs:
        - mdocean/
      html_storage: dvc
      executed_ipynb_storage: null
      cleaned_ipynb_storage: git
    build-paper:
      kind: latex
      target_path: pubs/journal-paper/mdocean.tex
      environment: tex
      inputs:
        - pubs/journal-paper/figs
        - pubs/journal-paper/sections/
        - pubs/journal-paper/tables
        - pubs/journal-paper/references.bib
        - pubs/journal-paper/numbers.tex
        - pubs/journal-paper/elsarticle-num-names.bst
publications:
  - path: pubs/journal-paper/mdocean.pdf
    title: Journal Renewable Energy
    description:
    kind: journal-article
    stage: build-paper
    overleaf:
      project_id: 6753a38b61276b931380c29c
      wdir: pubs/journal-paper
      sync_paths:
        - mdocean.tex
        - sections/
        - tables/
        - references.bib
        - numbers.tex
        - elsarticle-num-names.bst
      push_paths:
        - figs
      last_sync_commit: c50eec7a28349c1cdabac90de69d26e7fc493613
  - path: pubs/UMERC-2025-grid-value/UMERC_2025_grid_value.pdf
    title: WEC optimization to maximize grid economic value and 
      avoided emissions
    description:
    kind: conference-paper
    stage: build-pubs-umerc-2025-grid-value
    overleaf:
      project_id: 68516ba5bc36663bb61711a6
      wdir: pubs/UMERC-2025-grid-value
      sync_paths:
        - UMERC_2025_grid_value.tex
        - references.bib
        - logo.jpg
      push_paths:
        - figures
      last_sync_commit: 19e80b2eb61b274772d9ab359199f8aec05422d1
notebooks:
  - path: tutorials/tutorial.ipynb
    title: MDOcean Tutorial
    stage: run-tutorial
