name: mdocean
title: MDOcean
description: Multidisciplinary Design Optimization (MDO) to optimize
  an ocean wave energy converter (WEC).
environments:
  matlab:
    kind: matlab
    version: R2024b
    products:
      - Statistics_and_Machine_Learning_Toolbox
      - Parallel_Computing_Toolbox
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive via Docker.
pipeline:
  stages:
    run-matlab-tests:
      kind: matlab-script
      environment: matlab
      script_path: tests/run_tests.m
      outputs:
        - test-results/
      inputs: 
        - mdocean/
    build-RE-paper:
      kind: latex
      target_path: pubs/renewable-energy-mdo/mdocean.tex
      environment: tex
      inputs:
        - pubs/renewable-energy-mdo/figs
        - pubs/renewable-energy-mdo/sections/
        - pubs/renewable-energy-mdo/tables
        - pubs/renewable-energy-mdo/references.bib
        - pubs/renewable-energy-mdo/numbers.tex
        - pubs/elsarticle-num-names.bst
    build-AOR-paper:
      kind: latex
      target_path: pubs/applied-ocean-research-model/main.tex
      environment: tex
      inputs:
        - pubs/applied-ocean-research-model/sections/
        - pubs/applied-ocean-research-model/main.tex
        - pubs/applied-ocean-research-model/numbers.tex
        - pubs/elsarticle-num-names.bst
        - mdocean/simulation/modules/OpenFLASH/pubs/src/meem-appendix.tex
publications:
  - path: pubs/applied-ocean-research-model/out/main.pdf
    title: Modeling - Journal (Applied Ocean Research)
    description: Development, Validation, and Benchmarking of a Multidisciplinary Semi-Analytical Model for Wave Energy Converters
    kind: journal-article
    stage: build-AOR-paper
  - path: pubs/renewable-energy-mdo/out/mdocean.pdf
    title: Optimization - Journal (Renewable Energy)
    description: Leveraging Multidisciplinary Design Optimization to Advance Wave Energy Converter Viability
    kind: journal-article
    stage: build-RE-paper
    overleaf:
      project_id: 6753a38b61276b931380c29c
      wdir: pubs/renewable-energy-mdo
      sync_paths:
        - mdocean.tex
        - sections/
        - ../mdocean/simulation/modules/OpenFLASH/pubs/src/meem-appendix.tex
        - tables/
        - references.bib
        - numbers.tex
        - ../elsarticle-num-names.bst
      push_paths:
        - figs
      last_sync_commit: c50eec7a28349c1cdabac90de69d26e7fc493613
  - path: pubs/UMERC-2025-grid-value/UMERC_2025_grid_value.pdf
    title: Grid Value - Conference (UMERC)
    description: WEC optimization to maximize grid economic value and avoided emissions
    kind: conference-paper
    stage: build-pubs-umerc-2025-grid-value
    overleaf:
      project_id: 68516ba5bc36663bb61711a6
      wdir: pubs/UMERC-2025-grid-value
      sync_paths:
        - UMERC_2025_grid_value.tex
        - references.bib
        - logo.jpg
      push_paths:
        - figures
      last_sync_commit: 19e80b2eb61b274772d9ab359199f8aec05422d1
