flowchart TD
	node1["all-postpro"]
	node2["all-viz"]
	node3["analysis-AllFigCompare"]
	node4["analysis-Comparison"]
	node5["analysis-Constraints"]
	node6["analysis-Cost"]
	node7["analysis-DampingPlateStructures"]
	node8["analysis-DescFcns"]
	node9["analysis-DesignSpaceExploration"]
	node10["analysis-DesignVars"]
	node11["analysis-DragIntegral"]
	node12["analysis-FitOlaya"]
	node13["analysis-ForceSaturationFigFunc"]
	node14["analysis-GradientOptimFigFunc"]
	node15["analysis-HydroCoeffFigFunc"]
	node16["analysis-LocationSensitivity"]
	node17["analysis-Meem"]
	node18["analysis-Multistart"]
	node19["analysis-ParamSensitivities"]
	node20["analysis-Parameters"]
	node21["analysis-ParetoFigFunc"]
	node22["analysis-ParetoSweep"]
	node23["analysis-PtoSweep"]
	node24["analysis-QPCircles"]
	node25["analysis-ReadNonMatlabFigs"]
	node26["analysis-RunSingleFigFunc"]
	node27["analysis-Runtime"]
	node28["analysis-Slamming"]
	node29["analysis-SparHydro"]
	node30["analysis-SweepGeoms"]
	node31["analysis-Validation"]
	node32["analysis-Wecsim"]
	node33["aor-results-to-latex"]
	node34["build-AOR-paper"]
	node35["build-RE-paper"]
	node36["build-UMERC-paper"]
	node37["build-dissertation"]
	node38["copy-shared-latex"]
	node39["make-calkit-stages"]
	node40["make-drag-integral"]
	node41["make-quarto-yaml"]
	node42["make-var-bounds"]
	node43["mdocean/plots/non_matlab_figs/img/FBD.jpg.dvc"]
	node44["mdocean/plots/non_matlab_figs/img/MEEM_geometry.jpg.dvc"]
	node45["mdocean/plots/non_matlab_figs/img/RM3_image.png.dvc"]
	node46["mdocean/plots/non_matlab_figs/img/control_analysis_flowcharts.png.dvc"]
	node47["mdocean/plots/non_matlab_figs/img/damping_plate_flowchart.png.dvc"]
	node48["mdocean/plots/non_matlab_figs/img/dimensions.jpg.dvc"]
	node49["mdocean/plots/non_matlab_figs/img/drag_damping_integral.svg.dvc"]
	node50["mdocean/plots/non_matlab_figs/img/drag_exc_mag_integral.svg.dvc"]
	node51["mdocean/plots/non_matlab_figs/img/drag_exc_phase_integral.svg.dvc"]
	node52["mdocean/plots/non_matlab_figs/img/equivalent_stiffness.png.dvc"]
	node53["mdocean/plots/non_matlab_figs/img/graphical_abstract_modeling.png.dvc"]
	node54["mdocean/plots/non_matlab_figs/img/methodology_flowchart.png.dvc"]
	node55["mdocean/plots/non_matlab_figs/img/optimization_flowchart.jpg.dvc"]
	node56["mdocean/plots/non_matlab_figs/img/section_flow.png.dvc"]
	node57["mdocean/plots/non_matlab_figs/img/sim_runtime.png.dvc"]
	node58["mdocean/plots/non_matlab_figs/img/trapezoid.png.dvc"]
	node59["mdocean/plots/non_matlab_figs/img/xdsm.png.dvc"]
	node60["mdocean/plots/non_matlab_figs/pdf/FBD.pdf.dvc"]
	node61["mdocean/plots/non_matlab_figs/pdf/MEEM_geometry.pdf.dvc"]
	node62["mdocean/plots/non_matlab_figs/pdf/RM3_image.pdf.dvc"]
	node63["mdocean/plots/non_matlab_figs/pdf/control_analysis_flowcharts.pdf.dvc"]
	node64["mdocean/plots/non_matlab_figs/pdf/damping_plate_flowchart.pdf.dvc"]
	node65["mdocean/plots/non_matlab_figs/pdf/dimensions.pdf.dvc"]
	node66["mdocean/plots/non_matlab_figs/pdf/equivalent_stiffness.pdf.dvc"]
	node67["mdocean/plots/non_matlab_figs/pdf/graphical_abstract_modeling.pdf.dvc"]
	node68["mdocean/plots/non_matlab_figs/pdf/methodology_flowchart.pdf.dvc"]
	node69["mdocean/plots/non_matlab_figs/pdf/optimization_flowchart.pdf.dvc"]
	node70["mdocean/plots/non_matlab_figs/pdf/section_flow.pdf.dvc"]
	node71["mdocean/plots/non_matlab_figs/pdf/sim_runtime.pdf.dvc"]
	node72["mdocean/plots/non_matlab_figs/pdf/trapezoid.pdf.dvc"]
	node73["mermaid-make-pdfs@mod_freq_domain_ctrl_evaluation"]
	node74["mermaid-make-pdfs@mod_freq_domain_ctrl_synthesis"]
	node75["mermaid-make-pdfs@taxonomy"]
	node76["mermaid-make-pngs@mod_freq_domain_ctrl_evaluation"]
	node77["mermaid-make-pngs@mod_freq_domain_ctrl_synthesis"]
	node78["mermaid-make-pngs@taxonomy"]
	node79["move-aor-results"]
	node80["move-re-results"]
	node81["postpro-AllFigCompare"]
	node82["postpro-Comparison"]
	node83["postpro-Constraints"]
	node84["postpro-Cost"]
	node85["postpro-DampingPlateStructures"]
	node86["postpro-DescFcns"]
	node87["postpro-DesignSpaceExploration"]
	node88["postpro-DesignVars"]
	node89["postpro-DragIntegral"]
	node90["postpro-FitOlaya"]
	node91["postpro-ForceSaturationFigFunc"]
	node92["postpro-GradientOptimFigFunc"]
	node93["postpro-HydroCoeffFigFunc"]
	node94["postpro-LocationSensitivity"]
	node95["postpro-Meem"]
	node96["postpro-Multistart"]
	node97["postpro-ParamSensitivities"]
	node98["postpro-Parameters"]
	node99["postpro-ParetoFigFunc"]
	node100["postpro-ParetoSweep"]
	node101["postpro-PtoSweep"]
	node102["postpro-QPCircles"]
	node103["postpro-ReadNonMatlabFigs"]
	node104["postpro-RunSingleFigFunc"]
	node105["postpro-Runtime"]
	node106["postpro-Slamming"]
	node107["postpro-SparHydro"]
	node108["postpro-SweepGeoms"]
	node109["postpro-Validation"]
	node110["postpro-Wecsim"]
	node111["postpro-WithTables"]
	node112["pubs/applied-ocean-research-model/figs/manual.dvc"]
	node113["pubs/defense/figs/icon-people.png.dvc"]
	node114["pubs/defense/figs/icon-planet.png.dvc"]
	node115["pubs/defense/figs/icon-profit.png.dvc"]
	node116["pubs/defense/figs/img0000.png.dvc"]
	node117["pubs/defense/figs/img0001.png.dvc"]
	node118["pubs/defense/figs/img0007.png.dvc"]
	node119["pubs/defense/figs/img0008.png.dvc"]
	node120["pubs/defense/figs/img0010.png.dvc"]
	node121["pubs/defense/figs/img0011.png.dvc"]
	node122["pubs/defense/figs/img0013.png.dvc"]
	node123["pubs/defense/figs/img0014.png.dvc"]
	node124["pubs/defense/figs/img0015.png.dvc"]
	node125["pubs/defense/figs/img0016.png.dvc"]
	node126["pubs/defense/figs/img0021.png.dvc"]
	node127["pubs/defense/figs/img0028.png.dvc"]
	node128["pubs/defense/figs/img0029.png.dvc"]
	node129["pubs/defense/figs/img0030.png.dvc"]
	node130["pubs/defense/figs/img0033.png.dvc"]
	node131["pubs/defense/figs/img0034.png.dvc"]
	node132["pubs/defense/figs/img0036.png.dvc"]
	node133["pubs/defense/figs/img0038.png.dvc"]
	node134["pubs/defense/figs/img0039.png.dvc"]
	node135["pubs/defense/figs/img0040.png.dvc"]
	node136["pubs/defense/figs/img0041.png.dvc"]
	node137["pubs/defense/figs/img0042.png.dvc"]
	node138["pubs/defense/figs/img0043.png.dvc"]
	node139["pubs/defense/figs/img0044.png.dvc"]
	node140["pubs/defense/figs/img0045.png.dvc"]
	node141["pubs/defense/figs/img0047.png.dvc"]
	node142["pubs/defense/figs/img0048.png.dvc"]
	node143["pubs/defense/figs/img0049.png.dvc"]
	node144["pubs/defense/figs/img0050.png.dvc"]
	node145["pubs/defense/figs/img0051.png.dvc"]
	node146["pubs/defense/figs/img0052.png.dvc"]
	node147["pubs/defense/figs/img0053.png.dvc"]
	node148["pubs/defense/figs/img0054.png.dvc"]
	node149["pubs/defense/figs/img0055.png.dvc"]
	node150["pubs/defense/figs/img0056.png.dvc"]
	node151["pubs/defense/figs/img0057.png.dvc"]
	node152["pubs/defense/figs/img0058.png.dvc"]
	node153["pubs/defense/figs/img0059.png.dvc"]
	node154["pubs/defense/figs/img0060.png.dvc"]
	node155["pubs/defense/figs/img0061.png.dvc"]
	node156["pubs/defense/figs/img0062.png.dvc"]
	node157["pubs/defense/figs/img0063.png.dvc"]
	node158["pubs/defense/figs/img0064.png.dvc"]
	node159["pubs/defense/figs/img0065.png.dvc"]
	node160["pubs/defense/figs/img0066.png.dvc"]
	node161["pubs/defense/figs/img0067.png.dvc"]
	node162["pubs/defense/figs/img0068.png.dvc"]
	node163["pubs/defense/figs/img0069.png.dvc"]
	node164["pubs/defense/figs/img0070.png.dvc"]
	node165["pubs/defense/figs/img0071.png.dvc"]
	node166["pubs/defense/figs/img0072.png.dvc"]
	node167["pubs/defense/figs/img0073.png.dvc"]
	node168["pubs/defense/figs/img0074.png.dvc"]
	node169["pubs/defense/figs/lin-ps-flow.png.dvc"]
	node170["pubs/defense/figs/pto.png.dvc"]
	node171["pubs/defense/figs/sealab.png.dvc"]
	node172["pyxdsm"]
	node173["re-results-to-latex"]
	node174["render-quarto-html"]
	node175["render-quarto-pdf"]
	node176["test-aor"]
	node177["test-re"]
	node178["view-aor-figs"]
	node179["view-re-figs"]
	node180["viz-AllFigCompare"]
	node181["viz-Comparison"]
	node182["viz-Constraints"]
	node183["viz-Cost"]
	node184["viz-DampingPlateStructures"]
	node185["viz-DescFcns"]
	node186["viz-DesignSpaceExploration"]
	node187["viz-DesignVars"]
	node188["viz-DragIntegral"]
	node189["viz-FitOlaya"]
	node190["viz-ForceSaturationFigFunc"]
	node191["viz-GradientOptimFigFunc"]
	node192["viz-HydroCoeffFigFunc"]
	node193["viz-LocationSensitivity"]
	node194["viz-Meem"]
	node195["viz-Multistart"]
	node196["viz-ParamSensitivities"]
	node197["viz-Parameters"]
	node198["viz-ParetoFigFunc"]
	node199["viz-ParetoSweep"]
	node200["viz-PtoSweep"]
	node201["viz-QPCircles"]
	node202["viz-ReadNonMatlabFigs"]
	node203["viz-RunSingleFigFunc"]
	node204["viz-Runtime"]
	node205["viz-Slamming"]
	node206["viz-SparHydro"]
	node207["viz-SweepGeoms"]
	node208["viz-Validation"]
	node209["viz-Wecsim"]
	node3-->node80
	node3-->node81
	node3-->node177
	node4-->node80
	node4-->node82
	node4-->node176
	node4-->node177
	node5-->node80
	node5-->node83
	node5-->node177
	node6-->node79
	node6-->node84
	node6-->node176
	node7-->node79
	node7-->node85
	node7-->node176
	node8-->node79
	node8-->node86
	node8-->node176
	node9-->node79
	node9-->node80
	node9-->node87
	node9-->node176
	node9-->node177
	node10-->node80
	node10-->node88
	node10-->node177
	node11-->node79
	node11-->node89
	node11-->node176
	node12-->node79
	node12-->node90
	node13-->node79
	node13-->node91
	node13-->node176
	node14-->node80
	node14-->node92
	node14-->node177
	node15-->node79
	node15-->node93
	node15-->node176
	node16-->node80
	node16-->node94
	node16-->node177
	node17-->node79
	node17-->node95
	node17-->node176
	node18-->node80
	node18-->node96
	node18-->node177
	node19-->node80
	node19-->node97
	node19-->node177
	node20-->node80
	node20-->node98
	node20-->node177
	node21-->node80
	node21-->node99
	node21-->node177
	node22-->node80
	node22-->node100
	node22-->node177
	node23-->node79
	node23-->node101
	node24-->node79
	node24-->node102
	node25-->node79
	node25-->node80
	node25-->node103
	node25-->node176
	node25-->node177
	node26-->node79
	node26-->node104
	node26-->node176
	node27-->node79
	node27-->node105
	node27-->node176
	node28-->node79
	node28-->node106
	node28-->node176
	node29-->node79
	node29-->node107
	node29-->node176
	node30-->node79
	node30-->node108
	node31-->node79
	node31-->node109
	node31-->node176
	node32-->node79
	node32-->node110
	node32-->node176
	node33-->node34
	node33-->node37
	node36-->node37
	node38-->node34
	node38-->node35
	node38-->node37
	node40-->node3
	node40-->node4
	node40-->node5
	node40-->node6
	node40-->node7
	node40-->node8
	node40-->node9
	node40-->node10
	node40-->node11
	node40-->node12
	node40-->node13
	node40-->node14
	node40-->node15
	node40-->node16
	node40-->node17
	node40-->node18
	node40-->node19
	node40-->node20
	node40-->node21
	node40-->node22
	node40-->node23
	node40-->node24
	node40-->node25
	node40-->node26
	node40-->node27
	node40-->node28
	node40-->node29
	node40-->node30
	node40-->node31
	node40-->node32
	node40-->node39
	node40-->node42
	node40-->node81
	node40-->node82
	node40-->node83
	node40-->node84
	node40-->node85
	node40-->node86
	node40-->node87
	node40-->node88
	node40-->node89
	node40-->node90
	node40-->node91
	node40-->node92
	node40-->node93
	node40-->node94
	node40-->node95
	node40-->node96
	node40-->node97
	node40-->node98
	node40-->node99
	node40-->node100
	node40-->node101
	node40-->node102
	node40-->node103
	node40-->node104
	node40-->node105
	node40-->node106
	node40-->node107
	node40-->node108
	node40-->node109
	node40-->node110
	node40-->node176
	node40-->node177
	node41-->node174
	node42-->node3
	node42-->node4
	node42-->node5
	node42-->node6
	node42-->node7
	node42-->node8
	node42-->node9
	node42-->node10
	node42-->node11
	node42-->node12
	node42-->node13
	node42-->node14
	node42-->node15
	node42-->node16
	node42-->node17
	node42-->node18
	node42-->node19
	node42-->node20
	node42-->node21
	node42-->node22
	node42-->node23
	node42-->node24
	node42-->node25
	node42-->node26
	node42-->node27
	node42-->node28
	node42-->node29
	node42-->node30
	node42-->node31
	node42-->node32
	node42-->node39
	node42-->node81
	node42-->node82
	node42-->node83
	node42-->node84
	node42-->node85
	node42-->node86
	node42-->node87
	node42-->node88
	node42-->node89
	node42-->node90
	node42-->node91
	node42-->node92
	node42-->node93
	node42-->node94
	node42-->node95
	node42-->node96
	node42-->node97
	node42-->node98
	node42-->node99
	node42-->node100
	node42-->node101
	node42-->node102
	node42-->node103
	node42-->node104
	node42-->node105
	node42-->node106
	node42-->node107
	node42-->node108
	node42-->node109
	node42-->node110
	node42-->node176
	node42-->node177
	node43-->node103
	node43-->node176
	node43-->node177
	node44-->node103
	node44-->node176
	node44-->node177
	node45-->node103
	node45-->node176
	node45-->node177
	node46-->node103
	node46-->node176
	node46-->node177
	node47-->node103
	node47-->node176
	node47-->node177
	node48-->node103
	node48-->node176
	node48-->node177
	node49-->node103
	node49-->node176
	node49-->node177
	node50-->node103
	node50-->node176
	node50-->node177
	node51-->node103
	node51-->node176
	node51-->node177
	node52-->node103
	node52-->node176
	node52-->node177
	node53-->node103
	node53-->node176
	node53-->node177
	node54-->node103
	node54-->node176
	node54-->node177
	node55-->node103
	node55-->node176
	node55-->node177
	node56-->node103
	node56-->node176
	node56-->node177
	node57-->node103
	node57-->node176
	node57-->node177
	node58-->node103
	node58-->node176
	node58-->node177
	node59-->node103
	node59-->node176
	node59-->node177
	node60-->node79
	node60-->node80
	node60-->node103
	node60-->node176
	node60-->node177
	node61-->node79
	node61-->node80
	node61-->node103
	node61-->node176
	node61-->node177
	node62-->node79
	node62-->node80
	node62-->node103
	node62-->node176
	node62-->node177
	node63-->node79
	node63-->node80
	node63-->node103
	node63-->node176
	node63-->node177
	node64-->node79
	node64-->node80
	node64-->node103
	node64-->node176
	node64-->node177
	node65-->node79
	node65-->node80
	node65-->node103
	node65-->node176
	node65-->node177
	node66-->node79
	node66-->node80
	node66-->node103
	node66-->node176
	node66-->node177
	node67-->node79
	node67-->node80
	node67-->node103
	node67-->node176
	node67-->node177
	node68-->node79
	node68-->node80
	node68-->node103
	node68-->node176
	node68-->node177
	node69-->node79
	node69-->node80
	node69-->node103
	node69-->node176
	node69-->node177
	node70-->node79
	node70-->node80
	node70-->node103
	node70-->node176
	node70-->node177
	node71-->node79
	node71-->node80
	node71-->node103
	node71-->node176
	node71-->node177
	node72-->node79
	node72-->node80
	node72-->node103
	node72-->node176
	node72-->node177
	node73-->node79
	node73-->node80
	node73-->node103
	node73-->node176
	node73-->node177
	node74-->node79
	node74-->node80
	node74-->node103
	node74-->node176
	node74-->node177
	node75-->node79
	node75-->node80
	node75-->node103
	node75-->node176
	node75-->node177
	node76-->node103
	node76-->node176
	node76-->node177
	node77-->node103
	node77-->node176
	node77-->node177
	node78-->node103
	node78-->node176
	node78-->node177
	node79-->node34
	node79-->node37
	node79-->node178
	node80-->node35
	node80-->node37
	node80-->node179
	node81-->node1
	node81-->node80
	node81-->node180
	node82-->node1
	node82-->node80
	node82-->node111
	node82-->node181
	node83-->node1
	node83-->node80
	node83-->node111
	node83-->node182
	node84-->node1
	node84-->node79
	node84-->node111
	node84-->node183
	node85-->node1
	node85-->node79
	node85-->node184
	node86-->node1
	node86-->node79
	node86-->node185
	node87-->node1
	node87-->node41
	node87-->node79
	node87-->node80
	node87-->node111
	node87-->node186
	node88-->node1
	node88-->node80
	node88-->node111
	node88-->node187
	node89-->node1
	node89-->node79
	node89-->node188
	node90-->node1
	node90-->node79
	node90-->node189
	node91-->node1
	node91-->node41
	node91-->node79
	node91-->node173
	node91-->node190
	node92-->node1
	node92-->node41
	node92-->node80
	node92-->node111
	node92-->node191
	node93-->node1
	node93-->node79
	node93-->node192
	node94-->node1
	node94-->node80
	node94-->node111
	node94-->node193
	node95-->node1
	node95-->node79
	node95-->node194
	node96-->node1
	node96-->node80
	node96-->node111
	node96-->node195
	node97-->node1
	node97-->node80
	node97-->node196
	node98-->node1
	node98-->node33
	node98-->node41
	node98-->node80
	node98-->node111
	node98-->node197
	node99-->node1
	node99-->node80
	node99-->node198
	node100-->node1
	node100-->node80
	node100-->node199
	node101-->node1
	node101-->node33
	node101-->node79
	node101-->node200
	node102-->node1
	node102-->node79
	node102-->node201
	node103-->node1
	node103-->node79
	node103-->node80
	node103-->node202
	node104-->node1
	node104-->node33
	node104-->node79
	node104-->node173
	node104-->node203
	node105-->node1
	node105-->node33
	node105-->node41
	node105-->node79
	node105-->node173
	node105-->node204
	node106-->node1
	node106-->node79
	node106-->node205
	node107-->node1
	node107-->node79
	node107-->node206
	node108-->node1
	node108-->node79
	node108-->node207
	node109-->node1
	node109-->node41
	node109-->node79
	node109-->node111
	node109-->node208
	node110-->node1
	node110-->node33
	node110-->node41
	node110-->node79
	node110-->node111
	node110-->node209
	node112-->node34
	node112-->node37
	node112-->node178
	node113-->node174
	node114-->node174
	node115-->node174
	node116-->node174
	node117-->node174
	node118-->node174
	node119-->node174
	node120-->node174
	node121-->node174
	node122-->node174
	node123-->node174
	node124-->node174
	node125-->node174
	node126-->node174
	node127-->node174
	node128-->node174
	node129-->node174
	node130-->node174
	node131-->node174
	node132-->node174
	node133-->node174
	node134-->node174
	node135-->node174
	node136-->node174
	node137-->node174
	node138-->node174
	node139-->node174
	node140-->node174
	node141-->node174
	node142-->node174
	node143-->node174
	node144-->node174
	node145-->node174
	node146-->node174
	node147-->node174
	node148-->node174
	node149-->node174
	node150-->node174
	node151-->node174
	node152-->node174
	node153-->node174
	node154-->node174
	node155-->node174
	node156-->node174
	node157-->node174
	node158-->node174
	node159-->node174
	node160-->node174
	node161-->node174
	node162-->node174
	node163-->node174
	node164-->node174
	node165-->node174
	node166-->node174
	node167-->node174
	node168-->node174
	node169-->node174
	node170-->node174
	node171-->node174
	node172-->node79
	node172-->node80
	node172-->node103
	node172-->node176
	node172-->node177
	node173-->node35
	node173-->node37
	node174-->node175
	node180-->node2
	node181-->node2
	node182-->node2
	node183-->node2
	node184-->node2
	node185-->node2
	node186-->node2
	node187-->node2
	node188-->node2
	node189-->node2
	node190-->node2
	node191-->node2
	node192-->node2
	node193-->node2
	node194-->node2
	node195-->node2
	node196-->node2
	node197-->node2
	node198-->node2
	node199-->node2
	node200-->node2
	node201-->node2
	node202-->node2
	node203-->node2
	node204-->node2
	node205-->node2
	node206-->node2
	node207-->node2
	node208-->node2
	node209-->node2
