stages:
  build-paper:
    cmd: calkit xenv -n tex -- latexmk -cd -silent -interaction=nonstopmode -pdf pubs/journal-paper/mdocean.tex
    deps:
    - pubs/journal-paper/figs
    - pubs/journal-paper/mdocean.tex
    - pubs/journal-paper/sections/
    - pubs/journal-paper/tables
    - pubs/journal-paper/references.bib
    - pubs/journal-paper/numbers.tex
    - pubs/journal-paper/elsarticle-num-names.bst
    - mdocean/simulation/modules/OpenFLASH/pubs/src/meem-appendix.tex
    outs:
    - pubs/journal-paper/mdocean.pdf
