stages:
  build-paper:
    cmd: calkit xenv -n tex -- latexmk -cd -interaction=nonstopmode -pdf paper/mdocean.tex
    deps:
    - paper/figs
    - paper/mdocean.tex
    - paper/sections/
    outs:
    - paper/mdocean.pdf
