stages:
  build-paper:
    cmd: calkit xenv -n tex -- latexmk -cd -silent -interaction=nonstopmode -pdf paper/mdocean.tex
    deps:
    - paper/figs
    - paper/mdocean.tex
    - paper/sections/
    - paper/tables
    - paper/references.bib
    - paper/numbers.tex
    - paper/elsarticle-num-names.bst
    - mdocean/simulation/modules/OpenFLASH/pubs/src/meem-appendix.tex
    outs:
    - paper/mdocean.pdf
