classdef ReadNonMatlabFigs < GenericAnalysis
    %READNONMATLABFIGS Analysis class for non-MATLAB figure reading
    %   Reads external image files and creates MATLAB figures

    properties
        fig_names = {'control_analysis_flowcharts',...
                    'damping_plate_flowchart',...
                    'dimensions',...
                    'drag_damping_integral',...
                    'drag_exc_mag_integral',...
                    'drag_exc_phase_integral',...
                    'equivalent_stiffness',...
                    'FBD',...
                    'graphical_abstract_modeling',...
                    'MEEM_geometry',...
                    'methodology_flowchart',...
                    'graphical_abstract_optim',...
                    'optimization_flowchart',...
                    'RM3_image',...
                    'section_flow',...
                    'sim_runtime', ...
                    'taxonomy', ...
                    'trapezoid',...
                    'xdsm',...
                    };
        tab_names = {};
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
