classdef ReadNonMatlabFigs < GroupedStageClass
    %READNONMATLABFIGS Analysis class for non-MATLAB figure reading
    %   Reads external image files and creates MATLAB figures

    properties
        fig_names = {'circuit_intrinsic', ...
                    'circuit_pto', ...
                    'circuit_kinematics', ...
                    'control_method_venn_diagram', ...
                    'control_analysis_flowcharts',...
                    'damping_plate_flowchart',...
                    'dimensions',...
                    'equivalent_stiffness',...
                    'FBD',...
                    'graphical_abstract_modeling',...
                    'graphical_abstract_optim',...
                    'meem_dims', ...
                    'MEEM_geometry',...
                    'methodology_flowchart',...
                    'mod_freq_domain_ctrl_synthesis',...
                    'mod_freq_domain_ctrl_evaluation',...
                    'mod_freq_domain_ctrl_combined',...
                    'optimization_flowchart',...
                    'RM3_image',...
                    'section_flow',...
                    'sim_runtime', ...
                    'taxonomy', ...
                    'trapezoid',...
                    'xdsm',...
                    };
        tab_names = {};
    end

    methods
        function obj = ReadNonMatlabFigs(varargin)
            obj = obj@GroupedStageClass(varargin{:});
            not_fig = ~endsWith(obj.postpro_outputs, '.fig');
            obj.postpro_outputs = obj.postpro_outputs(not_fig);
            obj.extra_postpro_inputs = [obj.extra_postpro_inputs, ...
                                {'mdocean/plots/non_matlab_figs/img/', ...
                                 'mdocean/plots/non_matlab_figs/pdf/'}];
        end
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
