%[DOCS AUTOGENERATED]
function intermed_result_struct = analysis_fcn(p,b)
% Function analysis_fcn
%
% :param p: Parameter struct
% :param b: Design variable bounds struct
% :returns: Intermediate results struct (cached heavy analyses)
    X = [b.X_noms; 1];
    num_outputs = 3;

    % run sim with timing
    p.use_multibody = true;
    profile clear
    profile on
    simulation(X,p);
    profile_multibody = profile('info');
    t_multibody_fullsim_timeit = timeit(@()simulation(X,p),num_outputs);

    p.use_multibody = false;
    profile clear
    profile on
    simulation(X,p);
    profile_singlebody = profile('info');
    t_singlebody_fullsim_timeit = timeit(@()simulation(X,p),num_outputs);

    gcp;
    add_wecsim_path()
    time = tic;
    runRM3Parallel
    t_wecsim = toc(time); %447

    % Store results for post-processing
    intermed_result_struct.profile_multibody = profile_multibody;
    intermed_result_struct.profile_singlebody = profile_singlebody;
    intermed_result_struct.t_singlebody_fullsim_timeit = t_singlebody_fullsim_timeit;
    intermed_result_struct.t_multibody_fullsim_timeit = t_multibody_fullsim_timeit;
    intermed_result_struct.t_wecsim = t_wecsim;
    intermed_result_struct.p = p;
end
