function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)

    fig_array = [intermed_result_struct.dynamics_runtime_fig, ...
                intermed_result_struct.hydro_runtime_fig, ...
                intermed_result_struct.sim_runtime_fig];
    
    tab_array_display = {};
    tab_array_latex = {};
    
    tab_firstrows = {};
    tab_colspecs = {};
    
    end_result_struct.runtime_analysis_complete = true;
end
