%[DOCS AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs

    int = intermed_result_struct;

    % Run runtime comparison analysis
    [fig_array, ...
    pct_runtime_MEEM, ...
    pct_runtime_dynamics, ...
    pct_runtime_other] = module_runtime_compare(int.p, int.profile_multibody, int.profile_singlebody, ...
                                                int.profile_freq_domain, int.t_multibody_fullsim_timeit, ...
                                                int.t_singlebody_fullsim_timeit, ...
                                                int.t_freq_domain_fullsim_timeit, int.t_wecsim);
    
    tab_array_display = {};
    tab_array_latex = {};
    
    tab_firstrows = {};
    tab_colspecs = {};
    
    end_result_struct.simRuntime = int.t_multibody_fullsim_timeit;
    end_result_struct.pctRuntimeDynamics = pct_runtime_dynamics;
    end_result_struct.pctRuntimeMEEM = pct_runtime_MEEM;
    end_result_struct.pctRuntimeOther = pct_runtime_other;
end
