%[AUTOGENERATED]
%[AUTOGENERATED]
function intermed_result_struct = analysis_fcn(~,~)
% Function analysis_fcn
%
% :param ~: ~
% :param ~: ~
% :returns: Intermediate results struct (cached heavy analyses)
    % Run hydrodynamic coefficient error analysis
    [~, ~, fig] = hydro_coeff_err();
    
    % Store figure for post-processing
    intermed_result_struct.created_figs = fig;
end
