%[AUTOGENERATED]
function [figs] = all_sens_plots(par_J_par_p_local, dJ_star_dp_quad_local, ...
                                 dJ_star_dp_lin_local, dJstar_dp_global, ...
                                 par_x_star_par_p_local, par_x_star_par_p_global, ...
                                 delta_p_change_activity_local, ...
                                 delta_p_change_activity_global, ...
                                 param_names, dvar_names, b)
% Function all_sens_plots
%
% :param par_J_par_p_local: par_J_par_p_local
% :param dJ_star_dp_quad_local: dJ_star_dp_quad_local
% :param dJ_star_dp_lin_local: dJ_star_dp_lin_local
% :param dJstar_dp_global: dJstar_dp_global
% :param par_x_star_par_p_local: par_x_star_par_p_local
% :param par_x_star_par_p_global: par_x_star_par_p_global
% :param delta_p_change_activity_local: $\\delta$ p change activity local
% :param delta_p_change_activity_global: $\\delta$ p change activity global
% :param param_names: param_names
% :param dvar_names: dvar_names
% :param b: Design variable bounds struct
% :returns: Figure handles

    %% Post processing
    dJdp_combined = [par_J_par_p_local; dJ_star_dp_quad_local; dJ_star_dp_lin_local; dJstar_dp_global];
    dJdp_names = {'partial','total linear','total quadratic','re-optimization'};
    
    % color grid plots
    % fig 1: dJ*/dp combined
    f1 = sensitivity_plot(dJdp_combined, 'dJ*/dp normalized', param_names, dJdp_names, ...
        'Parameters p', 'Type of Sensitivity');
    % fig 2: dJ*/dp global
    f2 = sensitivity_plot(dJstar_dp_global, 'dJ*/dp normalized: global', param_names, '', ...
        'Parameters p', '');
    
    % fig 3: dx*/dp local
    f3 = dxdp_plot(par_x_star_par_p_local,  param_names, dvar_names, 'local');
    % fig 4: dx*/dp global
    f4 = dxdp_plot(par_x_star_par_p_global, param_names, dvar_names, 'global');
    
    % fig 5: delta p local
    f5 = delta_p_plot(delta_p_change_activity_local,  b, dvar_names, param_names, 'local');
    % fig 6: delta p global
    f6 = delta_p_plot(delta_p_change_activity_global, b, dvar_names, param_names, 'global');

    figs = [f1,f2,f3,f4,f5,f6]; 
end

function fig = delta_p_plot(delta_p_norm,b,dvar_names,param_names,title_suffix)
    % combine all the slamming constraints into one so it fits on plot
    constr_names  = [b.constraint_names_pretty b.lin_constraint_names_pretty ...
        strcat(dvar_names," lower"), strcat(dvar_names," upper")];
    idx_slam = contains(constr_names,'Slamming');
    delta_p_norm_combine_slamming = delta_p_norm(:,~idx_slam);
    delta_p_norm_slam = delta_p_norm(:,idx_slam);
    [~,idx_delta_p_slam] = min(abs(delta_p_norm_slam),[],2);
    idx_delta_p_slam = sub2ind(size(delta_p_norm_slam),1:length(param_names),idx_delta_p_slam');
    delta_p_norm_combine_slamming(:,end+1) = delta_p_norm_slam(idx_delta_p_slam);
    
    titl = ['Normalized \Deltap to change constraint activity: ' title_suffix];
    xticks = [constr_names(~idx_slam),'Slamming'];
    yticks = param_names;
    xlab = 'Constraints';
    ylab = 'Parameters';
    fig = sensitivity_plot(delta_p_norm_combine_slamming, titl, xticks, yticks, xlab, ylab);
end

function fig = dxdp_plot(dxdp, param_names, dvar_names,title_suffix)
    titl = ['dx*/dp normalized: ' title_suffix];
    xticks = param_names;
    yticks = dvar_names;
    xlab = 'Parameters p';
    ylab = 'Design Variables x';
    fig = sensitivity_plot(dxdp, titl, xticks, yticks, xlab, ylab);
end

function fig = sensitivity_plot(matrix, titl, xticks, yticks, xlab, ylab)
    fig = color_each_element(matrix);
    ax = gca;
    title(titl)
    set(ax,'XTickLabel',xticks)
    set(ax,'YTickLabel',yticks)
    clim([-3 3])
    colormap(bluewhitered)
    xlabel(xlab)
    ylabel(ylab)
    improvePlot
    set(ax,'XTickLabelRotation', 60)
    if length(xticks) < 50
        ax.XAxis.FontSize = 14;
    else
        ax.XAxis.FontSize = 10;
    end
    if length(yticks) > 40
        ax.YAxis.FontSize = 10;
    end
    set(fig,'Position',[1 41 1536 840]) % full screen
end
