%[AUTOGENERATED]
function figs = global_sens_plots(ratios,LCOE,LCOE_nom,P_var,Pvar_nom,param_names,num_DVs,...
                                    X_LCOE,X_LCOE_nom,dvar_names,X_Pvar,X_Pvar_nom,...
                                    slope_LCOE_norm,slope_Pvar_norm,slope_X_LCOE_norm,...
                                    slope_X_Pvar_norm,param_table)
% Function global_sens_plots
%
% :param ratios: ratios
% :param LCOE: Levelized cost of energy ($/kWh)
% :param LCOE_nom: LCOE_nom
% :param P_var: P_var
% :param Pvar_nom: Pvar_nom
% :param param_names: param_names
% :param num_DVs: num_DVs
% :param X_LCOE: X_LCOE
% :param X_LCOE_nom: X_LCOE_nom
% :param dvar_names: dvar_names
% :param X_Pvar: X_Pvar
% :param X_Pvar_nom: X_Pvar_nom
% :param slope_LCOE_norm: slope_LCOE_norm
% :param slope_Pvar_norm: slope_Pvar_norm
% :param slope_X_LCOE_norm: slope_X_LCOE_norm
% :param slope_X_Pvar_norm: slope_X_Pvar_norm
% :param param_table: param_table
% :returns: Figure handles

    groups = categorical(param_table.subsystem(param_table.sweep));
    color_groupings = {'b','g','r','k','y','m'};
    colors = color_groupings(groups);

    %% Line plots showing nonlinearity
    fig_num_start = gcf().Number+1;
    f1 = figure(fig_num_start);
    subplot 121
    plot(ratios,LCOE/LCOE_nom)
    xlabel('Parameter Ratio from nominal')
    ylabel('LCOE ratio from nominal')
    legend(param_names)
    improvePlot
    grid on
    
    subplot 122
    plot(ratios,P_var/Pvar_nom)
    xlabel('Parameter ratio from nominal')
    ylabel('Power Variation ratio from nominal')
    legend(param_names)
    improvePlot
    grid on
    set(f1,'Position',[1 41 1536 840]) % full screen
    
    for i = 1:num_DVs
        f2 = figure(fig_num_start+1);
        subplot(3,5,i)
        plot(ratios, X_LCOE(:,:,i)./X_LCOE_nom(i))
        xlabel ('Parameter ratio from nominal')
        ylabel ('X* ratio from nominal')
        title([dvar_names{i} ' - min LCOE'])
        %improvePlot
        grid on
        
        f3 = figure(fig_num_start+2);
        subplot(3,5,i)
        plot(ratios, X_Pvar(:,:,i)./X_Pvar_nom(i))
        xlabel ('Parameter ratio from nominal')
        ylabel ('X* ratio from nominal')
        title([dvar_names{i} ' - min c_v'])
        %improvePlot
        grid on
    end
    legend(param_names)
    set(f2,'Position',[1 41 1536 840]) % full screen
    set(f3,'Position',[1 41 1536 840]) % full screen

    %% Tornado chart for overall slope
    f4 = sensitivity_tornado_barh(slope_LCOE_norm, slope_Pvar_norm, param_names, colors, groups, 'dJ*/dp');
    
    % separate figures for each design variable, with subplot for each objective
    for i=1:num_DVs
        f5_arr(i) = sensitivity_tornado_barh(slope_X_LCOE_norm(:,i), slope_X_Pvar_norm(:,i), ...
                                param_names, colors, groups, ['d' dvar_names{i} '^*/dp']);
    end

    % separate figures for each objective, with subplots for each design variable
    f6 = figure;
    t = tiledlayout(3,4);
    for i=1:num_DVs
        nexttile
        sensitivity_tornado_barh_inner(slope_X_LCOE_norm(:,i), param_names, colors, 8)
        title(['d' dvar_names{i} '^*/dp'])
    end
    color_legend(groups,colors,'eastoutside')
    title(t,'Normalized Sensitivities at Minimum LCOE')
    t.TileSpacing = 'compact';
    t.Padding = 'compact';

    f7 = figure;
    t2 = tiledlayout(3,4);
    for i=1:num_DVs
        nexttile
        sensitivity_tornado_barh_inner(slope_X_Pvar_norm(:,i), param_names, colors, 8)
        title(['d' dvar_names{i} '^*/dp'])
    end
    color_legend(groups,colors,'eastoutside')
    title(t2,'Normalized Sensitivities at Minimum Design Cost')
    t2.TileSpacing = 'compact';
    t2.Padding = 'compact';

    set(f6,'Position',[1 41 1536 840]) % full screen
    set(f7,'Position',[1 41 1536 840]) % full screen

    figs = [f1,f2,f3,f4,f5_arr,f6,f7];
end

function color_legend(groups,colors,loc)
    [~,first_idx] = ismember(categories(groups),groups);
    cols = colors(first_idx);
    h = gobjects([1 length(cols)]);
    for i=1:length(cols)
        h(i) = barh(NaN,NaN,cols{i});
    end
    set(h,{'DisplayName'},categories(groups));
    legend('location',loc)
end

function sensitivity_tornado_barh_inner(slope, param_names, colors, k)

    % set k=0 to show all parameters
    if k==0
        k = length(param_names);
    end

    % sort by highest sensitivity
    [~,sort_idx] = sort(abs(slope),'MissingPlacement','first');

    % only show the parameters with the k highest sensitivities.
    sort_idx_highest_k = sort_idx(end-k+1:end);
    slope_highest_k = slope(sort_idx_highest_k);
    colors_highest_k = colors(sort_idx_highest_k);
    params = categorical( param_names(sort_idx_highest_k), param_names(sort_idx_highest_k) );

    % bar chart
    for i=1:length(params)
        h = barh(params(i),slope_highest_k(i),colors_highest_k{i});
        h.Annotation.LegendInformation.IconDisplayStyle = 'off';
        hold on
    end
    xlim([-1.2 1.2] + fix(imrange(slope)))
    ax = gca;
    set(ax,'YGrid','on','XGrid','on')
    improvePlot

    % reduce fontsize
    all_axes = findobj(gcf().Children,'Type','Axes'); % all subplots in fig
    set(all_axes,'FontSize',12)
end

function f = sensitivity_tornado_barh(slope_LCOE, slope_Pvar, param_names, colors, groups, extra_title)
    
    % separate subplots for each objective
    f = figure;
    subplot 121
    sensitivity_tornado_barh_inner(slope_LCOE, param_names, colors, 25)
    title('At Minimum LCOE')
    
    subplot 122
    sensitivity_tornado_barh_inner(slope_Pvar, param_names, colors, 25)
    title('At Minimum Design Cost')
    sgtitle(['Normalized Sensitivities: ' extra_title])
    
    % legend
    color_legend(groups,colors,'southeast')
    set(f,"Position",[1.8 41.8 930 836.8])
    
    % both objectives on the same chart
%     figure
%     barh(categorical(param_names),[slope_LCOE, slope_Pvar])
%     legend('LCOE','P_{var}')
%     title(['Normalized Sensitivities' extra_title])
%     improvePlot
%     set(gca, 'FontSize', 12)
%     set(ax,'FontSize',12)
%     set(gca,'YGrid','on','XGrid','on')
end