%[DOCS AUTOGENERATED]
function fig = make_ctrl_polar_plot(MAG_GUESS, PHASE_GUESS, real_P, constraint_err, idx_opt, H_ss, T_ss)
% Function make_ctrl_polar_plot
%
% Visualisation of the brute-force controller search grid on complex axes.
% Selects the sea state with the highest optimal power and shows:
%   - power as a pcolor patch map using a log10-scaled radius:
%       r = log10(|alpha|) - log10(min|alpha|)
%     so that cells are spread out in the radial direction.
%   - cross-hatching where constraint_err ~= 0  (legend: 'Constraint violated')
%   - single-line red hatching where power is Inf  (legend: 'Unstable')
%   - star marker at the controller with maximum power
%
% Hatching uses per-cell quadrilateral patches (hatchfill2 on a multi-face
% patch) so hatch boundaries follow cell edges exactly.
%
% Cells are centred at the true grid coordinates: corner vertices are
% constructed as midpoints between adjacent centres in (log_r, phase) space,
% with the inner radial edge clamped to 0.
%
% :param MAG_GUESS:      meshgrid of ctrl mult magnitudes  (n_phase x n_mag)
% :param PHASE_GUESS:    meshgrid of ctrl mult phases in rad (n_phase x n_mag)
% :param real_P:         power in W (n_Hs x n_T x n_ctrl), unmodified raw values
% :param constraint_err: constraint error scalar (n_Hs x n_T x n_ctrl)
% :param idx_opt:        optimal controller index for each sea state (n_Hs x n_T)
% :param H_ss:           wave height for each sea state (n_Hs x n_T)
% :param T_ss:           wave period for each sea state (n_Hs x n_T)
% :returns: Figure handle

    real_P(isinf(real_P)) = NaN; % replace inf with nan (blank on plot)

    [sz_phase, sz_mag] = size(MAG_GUESS);
    n_ctrl = sz_phase * sz_mag;
    n_ss   = numel(real_P) / n_ctrl;

    % flatten sea-state and controller dimensions
    P_flat   = reshape(real_P,         n_ss, n_ctrl);
    C_flat   = reshape(constraint_err, n_ss, n_ctrl);
    idx_flat = idx_opt(:);           % (n_ss x 1), column-major

    % choose a sea state to make the plot - we want lots of stable
    % controllers so the plot isn't blank, and around 50% feasible controllers
    % so it shows a power tradeoff among the stable options
    ctrl_dim = 3;
    num_ctrl_stable_per_ss = sum(isfinite(real_P),ctrl_dim);
    num_ctrl_feasible_per_ss = sum(constraint_err <= 0,ctrl_dim);
    pct_feasible_per_ss = num_ctrl_feasible_per_ss ./num_ctrl_stable_per_ss;
    pct_off_from_half_feasible = abs(pct_feasible_per_ss - .5);
    [~,idx_chosen_ss] = max(num_ctrl_stable_per_ss./pct_off_from_half_feasible,[],'all');

    % 2-D controller grids for the chosen sea state
    P_ss = reshape(P_flat(idx_chosen_ss, :), sz_phase, sz_mag);
    C_ss = reshape(C_flat(idx_chosen_ss, :), sz_phase, sz_mag);

    % ---- Log10-scaled radius: r = log10(|alpha|) - log10(min|alpha|) ----
    % This maps min|alpha| -> r=0 and avoids negative radii for the centres.
    min_mag          = MAG_GUESS(1, 1);
    log_mag_centers  = log10(MAG_GUESS(1, :));           % 1 x sz_mag, uniform in log-space
    log_step         = log_mag_centers(2) - log_mag_centers(1);
    phase_centers    = PHASE_GUESS(:, 1);                % sz_phase x 1
    phase_step       = phase_centers(2) - phase_centers(1);

    % Corner log10-radii: midpoints between adjacent centres.
    % The innermost corner is clamped to 0 so it does not go negative.
    r_log_corners_1d = [log_mag_centers(1) - log_step/2, log_mag_centers + log_step/2] ...
                       - log10(min_mag);                  % 1 x (sz_mag+1)
    r_log_corners_1d(1) = max(0, r_log_corners_1d(1));

    % Corner phases: midpoints between adjacent centres
    phase_corners_1d = [phase_centers(1) - phase_step/2; ...
                        phase_centers + phase_step/2];   % (sz_phase+1) x 1

    % Build (sz_phase+1) x (sz_mag+1) vertex grids and convert to Cartesian
    [R_corners, PHI_corners] = meshgrid(r_log_corners_1d, phase_corners_1d);
    X_cart = R_corners .* cos(PHI_corners);
    Y_cart = R_corners .* sin(PHI_corners);

    % Pad data with repeated boundary row/col so pcolor (flat shading) renders
    % all sz_phase x sz_mag cells (it drops the last row/col of an MxN input).
    P_pad = [P_ss,     P_ss(:, end);  P_ss(end, :),  P_ss(end, end)];

    % --- figure setup ---
    fig = figure;
    ax  = axes(fig);
    hold(ax, 'on');

    % power colourmap via pcolor on the log10-scaled polar grid
    h_pc = pcolor(ax, X_cart, Y_cart, P_pad);
    set(h_pc, 'HandleVisibility', 'off');
    cb = colorbar(ax);
    cb.Label.String = 'Power (W)';

    % axis limits and labels reflecting the log-scaled radius
    r_lim = r_log_corners_1d(end);
    axis(ax, 'equal');
    xlim(ax, [-r_lim, r_lim]);
    ylim(ax, [-r_lim, r_lim]);
    xlabel(ax, sprintf('r_{log}\\cdotcos(\\phi_{\\alpha}),  r_{log} = log_{10}(|\\alpha|/%.3g)', min_mag))
    ylabel(ax, 'r_{log}\cdotsin(\phi_{\alpha})')
    title(ax, sprintf('Brute-force control grid for H=%.3g, T=%.3g', H_ss(idx_chosen_ss), T_ss(idx_chosen_ss)))

    tmp_clim = clim(ax);

    % --- cell-aligned hatching ---
    % hatchfill2 is called on a multi-face patch (4-x-N_cells), one quad per
    % infeasible cell.  This guarantees hatch boundaries follow cell edges exactly
    % (no diagonal contour interpolation artefacts).

    % Constraint-violated cells: black cross-hatch
    viol_list = find(C_ss(:) > 0 & ~isinf(C_ss(:)));
    if ~isempty(viol_list)
        [xd, yd] = cell_quads(viol_list, X_cart, Y_cart, sz_phase, sz_mag);
        hp_c = patch(ax, xd, yd, [1 1 1], 'FaceAlpha', 0, 'EdgeColor', 'none');
        hh_c = hatchfill2(hp_c, 'cross');
        hh_c.DisplayName = 'Constraint violated';
        hp_c.HandleVisibility = 'off';  % must happen after the call to hatchfill2
        hh_c.Color = [0 0 0 0.5];
    end

    % Unstable cells (Inf power): red single-diagonal hatch
    unstab_list = find(isinf(C_ss(:)));
    if ~isempty(unstab_list)
        [xd_u, yd_u] = cell_quads(unstab_list, X_cart, Y_cart, sz_phase, sz_mag);
        hp_u = patch(ax, xd_u, yd_u, [1 1 1], 'FaceAlpha', 0, 'EdgeColor', 'none');
        hh_u = hatchfill2(hp_u, 'single', 'HatchColor', [0.8 0 0], 'HatchLineWidth', 0.7);
        hh_u.DisplayName = 'Unstable';
        hp_u.HandleVisibility = 'off';  % must happen after the call to hatchfill2
    end

    clim(ax, tmp_clim);

    % --- reference circles labelled by |alpha| value ---
    th_ring = linspace(0, 2*pi, 200);
    % circles at each integer decade of |alpha| from min_mag to max_mag
    alpha_refs = min_mag * 10 .^ (0 : floor(r_lim));
    for alpha_val = alpha_refs
        r_val = log10(alpha_val / min_mag);
        if r_val < 0 || r_val > r_lim; continue; end
        plot(ax, r_val*cos(th_ring), r_val*sin(th_ring), ...
             'k:', 'LineWidth', 1, 'HandleVisibility', 'off')
        text(ax, r_val*cos(pi/8), r_val*sin(pi/8), ...
             sprintf('|\\alpha|=%.3g', alpha_val), ...
             'FontSize', 12, 'Color', 'k','BackgroundColor','w')
    end

    % --- controller markers ---
    % constrained optimal controller (already computed with constraints)
    idx_constrained_opt = idx_flat(idx_chosen_ss);
    [ir_cons, ic_cons] = ind2sub([sz_phase, sz_mag], idx_constrained_opt);
    r_cons = log10(MAG_GUESS(ir_cons, ic_cons)) - log10(min_mag);
    x_cons = r_cons * cos(PHASE_GUESS(ir_cons, ic_cons));
    y_cons = r_cons * sin(PHASE_GUESS(ir_cons, ic_cons));

    % unconstrained optimal controller (max power on this sea-state grid)
    valid_unconstrained = isfinite(P_ss);
    if any(valid_unconstrained(:))
        linear_valid = find(valid_unconstrained);
        [~, local_idx] = max(P_ss(valid_unconstrained));
        idx_unconstrained_opt = linear_valid(local_idx);
    else
        idx_unconstrained_opt = NaN;
    end
    if isnan(idx_unconstrained_opt)
        ir_uncons_opt = NaN;
        ic_uncons_opt = NaN;
        x_uncons_opt = NaN;
        y_uncons_opt = NaN;
    else
        [ir_uncons_opt, ic_uncons_opt] = ind2sub([sz_phase, sz_mag], idx_unconstrained_opt);
        r_uncons_opt = log10(MAG_GUESS(ir_uncons_opt, ic_uncons_opt)) - log10(min_mag);
        x_uncons_opt = r_uncons_opt * cos(PHASE_GUESS(ir_uncons_opt, ic_uncons_opt));
        y_uncons_opt = r_uncons_opt * sin(PHASE_GUESS(ir_uncons_opt, ic_uncons_opt));
    end

    % reactive control: alpha = 1  -> mag = 1, phase = 0
    [~, idx_mag_one] = min(abs(log_mag_centers));
    [~, idx_phase_zero] = min(abs(phase_centers));
    r_reactive = log10(MAG_GUESS(idx_phase_zero, idx_mag_one)) - log10(min_mag);
    x_reactive = r_reactive * cos(PHASE_GUESS(idx_phase_zero, idx_mag_one));
    y_reactive = r_reactive * sin(PHASE_GUESS(idx_phase_zero, idx_mag_one));

    % use distinct symbols so overlap remains readable (o x ^)
    plot(ax, x_reactive, y_reactive, 'ko', 'MarkerSize', 10, 'LineWidth', 1.5, ...
         'DisplayName', 'Reactive control');
    plot(ax, x_uncons_opt, y_uncons_opt, 'kx', 'MarkerSize', 10, 'LineWidth', 1.8, ...
         'DisplayName', 'Unconstrained optimal');
    plot(ax, x_cons, y_cons, 'k^', 'MarkerSize', 9, 'LineWidth', 1.5, ...
         'DisplayName', 'Constrained optimal');

    legend('location','eastoutside')
    improvePlot

    if ~isempty(viol_list)
        hh_c.Color = [0 0 0 0.5]; % need to set color again after improvePlot
    end

    % --- additional polar plot in gamma-space ---
    % gamma = (1 - alpha) / (1 + alpha)
    alpha_grid = MAG_GUESS .* exp(1i .* PHASE_GUESS);
    gamma_grid = (1 - alpha_grid) ./ (1 + alpha_grid);
    gamma_grid(~isfinite(gamma_grid)) = NaN;

    fig_gamma = figure;
    pax = polaraxes(fig_gamma);
    hold(pax, 'on');

    theta_gamma = angle(gamma_grid(:));
    rho_gamma = abs(gamma_grid(:));
    pvals = P_ss(:);
    valid_pts = isfinite(theta_gamma) & isfinite(rho_gamma) & isfinite(pvals);

    if any(valid_pts)
        polarscatter(pax, theta_gamma(valid_pts), rho_gamma(valid_pts), 30, pvals(valid_pts), 'filled', ...
            'DisplayName', 'Controller grid');
    end
    cb2 = colorbar(pax);
    cb2.Label.String = 'Power (W)';

    % alpha=1 maps to gamma=0 (origin in gamma-space)
    polarplot(pax, 0, 0, 'ko', 'MarkerSize', 10, 'LineWidth', 1.5, ...
        'DisplayName', 'Reactive control');

    if ~isnan(ir_uncons_opt)
        gamma_uncons = gamma_grid(ir_uncons_opt, ic_uncons_opt);
        if isfinite(gamma_uncons)
            polarplot(pax, angle(gamma_uncons), abs(gamma_uncons), 'kx', 'MarkerSize', 10, 'LineWidth', 1.8, ...
                'DisplayName', 'Unconstrained optimal');
        end
    end

    gamma_cons = gamma_grid(ir_cons, ic_cons);
    if isfinite(gamma_cons)
        polarplot(pax, angle(gamma_cons), abs(gamma_cons), 'k^', 'MarkerSize', 9, 'LineWidth', 1.5, ...
            'DisplayName', 'Constrained optimal');
    end

    title(pax, sprintf('Gamma polar plot for H=%.3g, T=%.3g', H_ss(idx_chosen_ss), T_ss(idx_chosen_ss)));
    legend(pax, 'Location', 'bestoutside');
    fig.UserData.gamma_fig = fig_gamma;
end

function [xdata, ydata] = cell_quads(cell_list, X_cart, Y_cart, sz_phase, sz_mag)
% Build 4-x-N vertex arrays for a multi-face patch covering the listed cells.
% cell_list contains linear indices into an (sz_phase x sz_mag) grid.
% Corners of cell (i,j) are X_cart([i i+1],[j j+1]).
    n = numel(cell_list);
    xdata = zeros(4, n);
    ydata = zeros(4, n);
    for k = 1:n
        [i, j] = ind2sub([sz_phase, sz_mag], cell_list(k));
        xdata(:,k) = [X_cart(i,j);   X_cart(i,j+1);   X_cart(i+1,j+1); X_cart(i+1,j)];
        ydata(:,k) = [Y_cart(i,j);   Y_cart(i,j+1);   Y_cart(i+1,j+1); Y_cart(i+1,j)];
    end
end
