%[DOCS AUTOGENERATED]
function fig = make_ctrl_polar_plot(MAG_GUESS, PHASE_GUESS, real_P, constraint_err, idx_opt)
% Function make_ctrl_polar_plot
%
% Visualisation of the brute-force controller search grid on complex axes.
% Selects the sea state with the highest optimal power and shows:
%   - power as a pcolor patch map on complex-plane (alpha = mag*exp(j*phase)) axes
%   - cross-hatching (using hatchfill2) where constraint_err ~= 0
%   - star marker at the controller with maximum power
%
% The grid is padded by one row/column before calling pcolor so that no
% data is discarded (pcolor with shading flat would otherwise drop the last
% row and column).
%
% :param MAG_GUESS:      meshgrid of ctrl mult magnitudes  (n_phase x n_mag_full)
% :param PHASE_GUESS:    meshgrid of ctrl mult phases in rad (n_phase x n_mag_full)
% :param real_P:         power in W (n_Hs x n_T x n_ctrl), unmodified raw values
% :param constraint_err: constraint error scalar (n_Hs x n_T x n_ctrl)
% :param idx_opt:        optimal controller index for each sea state (n_Hs x n_T)
% :returns: Figure handle

    [sz_phase, sz_mag_full] = size(MAG_GUESS);
    n_ctrl = sz_phase * sz_mag_full;
    n_ss   = numel(real_P) / n_ctrl;

    % flatten sea-state and controller dimensions
    P_flat   = reshape(real_P,        n_ss, n_ctrl);
    C_flat   = reshape(constraint_err, n_ss, n_ctrl);
    idx_flat = idx_opt(:);           % (n_ss x 1), column-major

    % compute optimal power per sea state
    opt_P_vec = nan(n_ss, 1);
    for s = 1:n_ss
        opt_P_vec(s) = P_flat(s, idx_flat(s));
    end
    [opt_P_best, best_ss] = max(opt_P_vec, [], 'omitnan');

    % 2-D controller grids for the chosen sea state (use all columns)
    P_ss = reshape(P_flat(best_ss, :), sz_phase, sz_mag_full);
    C_ss = reshape(C_flat(best_ss, :), sz_phase, sz_mag_full);

    % Pad grid by one row/col for pcolor so no data is discarded.
    % pcolor(X,Y,P) with shading flat renders only (M-1)x(N-1) patches of an
    % MxN input; padding to (M+1)x(N+1) makes the full MxN grid visible.
    mag_ratio  = MAG_GUESS(1, 2)   / MAG_GUESS(1, 1);    % logspace step ratio
    phase_step = PHASE_GUESS(2, 1) - PHASE_GUESS(1, 1);  % phase increment

    % Vertex grid: one extra row (phase extended) and one extra col (mag extended)
    MAG_verts  = [MAG_GUESS,   MAG_GUESS(:, end) * mag_ratio; ...
                  MAG_GUESS(end, :), MAG_GUESS(end, end) * mag_ratio];
    PHS_verts  = [PHASE_GUESS,   PHASE_GUESS(:, end); ...
                  PHASE_GUESS(end, :) + phase_step, PHASE_GUESS(end, end) + phase_step];

    % Data padded by repeating boundary row/col (so pcolor renders all cells)
    P_pad = [P_ss,     P_ss(:, end);     P_ss(end, :),     P_ss(end, end)];
    C_pad = [C_ss,     C_ss(:, end);     C_ss(end, :),     C_ss(end, end)];

    % Convert to Cartesian (alpha = mag * exp(j*phase))
    X_cart = MAG_verts .* cos(PHS_verts);
    Y_cart = MAG_verts .* sin(PHS_verts);

    % --- figure setup ---
    fig = figure;
    ax  = axes(fig);
    hold(ax, 'on');

    % power colourmap via pcolor on the complex-plane grid
    pcolor(ax, X_cart, Y_cart, P_pad);
    %shading(ax, 'flat');
    cb = colorbar(ax);
    cb.Label.String = 'Power (W)';
    axis(ax, 'equal');
    xlabel(ax, 'Re(\alpha)')
    ylabel(ax, 'Im(\alpha)')
    title(ax, sprintf('Brute-force ctrl grid | max-power sea state  (P_{opt} = %.3g W)', opt_P_best))

    % reference circles at selected radii
    th_ring = linspace(0, 2*pi, 200);
    r_refs  = [0.5, 1, 2];
    for r_val = r_refs
        plot(ax, r_val*cos(th_ring), r_val*sin(th_ring), ...
             'k:', 'LineWidth', 0.5, 'HandleVisibility', 'off')
        text(ax, r_val*cos(pi/8), r_val*sin(pi/8), ...
             sprintf('|\\alpha|=%.4g', r_val), ...
             'FontSize', 7, 'Color', 'k')
    end

    % --- hatching where constraint is violated (constraint_err ~= 0) ---
    % Use original (non-padded) grid for contourf so the hatched region matches
    X_orig = MAG_GUESS .* cos(PHASE_GUESS);
    Y_orig = MAG_GUESS .* sin(PHASE_GUESS);
    constr_violated = double(C_ss ~= 0);
    if any(constr_violated(:))
        tmp_clim = clim(ax);
        [~, h_hatch] = contourf(ax, X_orig, Y_orig, constr_violated, [0.5 0.5],'Fill','off');
        hh = hatchfill2(h_hatch, 'cross');
        hh.Color = [0 0 0 0.5];
        hh.DisplayName = 'Constraint violated';
        clim(ax, tmp_clim);
    end

    % --- star marker at the max-power optimal controller ---
    opt_ctrl_idx = idx_flat(best_ss);
    [ir_opt, ic_opt] = ind2sub([sz_phase, sz_mag_full], opt_ctrl_idx);
    x_opt = MAG_GUESS(ir_opt, ic_opt) * cos(PHASE_GUESS(ir_opt, ic_opt));
    y_opt = MAG_GUESS(ir_opt, ic_opt) * sin(PHASE_GUESS(ir_opt, ic_opt));
    plot(ax, x_opt, y_opt, 'r*', 'MarkerSize', 14, 'LineWidth', 2, ...
         'DisplayName', 'Max power controller')

    legend
    improvePlot
end
