%[DOCS AUTOGENERATED]
function intermed_result_struct = analysis_fcn(~,~)
% Function analysis_fcn
%
% :param ~: ~
% :param ~: ~
% :returns: Intermediate results struct (cached heavy analyses)
    fig = circle_intersect_script();

    intermed_result_struct.figure_handle = fig;
end
