%[AUTOGENERATED]
%[AUTOGENERATED]
function intermed_result_struct = analysis_fcn(p,b)
% Function analysis_fcn
%
% :param p: Parameter struct
% :param b: Design variable bounds struct
% :returns: Intermediate results struct (cached heavy analyses)
    % Run single analysis with drag convergence plotting
    p.operational_dynamics_debug_plots_on = true;
    figs = run_single(p,b);

    % Store figure numbers for post-processing
    intermed_result_struct.created_figs = figs;
end
