%[DOCS AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
    
    figs_intermed = intermed_result_struct.created_figs;

    fig_circles = plot_nominal_constraint_circles(intermed_result_struct.val);

    fig_gamma = figs_intermed(6);
    fig_circles_overlay = plot_nominal_constraint_circles(intermed_result_struct.val, fig_gamma.CurrentAxes);

    fig_array = [figs_intermed, fig_circles, fig_circles_overlay];
    
    tab_array_display = {};
    tab_array_latex = {};
    
    tab_firstrows = {};
    tab_colspecs = {};
    
    end_result_struct.nominalLCOE = intermed_result_struct.LCOE;
    surgeForce = intermed_result_struct.val.force_surge;
    end_result_struct.surgeForceFloatNominal = surgeForce(1);
    end_result_struct.surgeForceSparNominal  = surgeForce(2);
    end_result_struct.capexDesignNominal = intermed_result_struct.val.capex_design;
    end_result_struct.powerAvgNominal = intermed_result_struct.val.power_avg;
end
