%[DOCS AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs

    fig_array = intermed_result_struct.created_figs;
    
    p = intermed_result_struct.p;
    b = intermed_result_struct.b;
    X = [b.X_noms; 1];
    fig_circles = plot_nominal_constraint_circles(intermed_result_struct.val, p, X);
    fig_array = [intermed_result_struct.created_figs, fig_circles];
    
    tab_array_display = {};
    tab_array_latex = {};
    
    tab_firstrows = {};
    tab_colspecs = {};
    
    end_result_struct.nominalLCOE = intermed_result_struct.LCOE;
    surgeForce = intermed_result_struct.val.force_surge;
    end_result_struct.surgeForceFloatNominal = surgeForce(1);
    end_result_struct.surgeForceSparNominal  = surgeForce(2);
    end_result_struct.capexDesignNominal = intermed_result_struct.val.capex_design;
    end_result_struct.powerAvgNominal = intermed_result_struct.val.power_avg;
end
