classdef RunSingleFigFunc < GenericAnalysis
    %RUNSINGLEFIGFUNC Analysis class for single run figures
    %   Generates nominal geometry, power matrix, and drag convergence figures

    properties
        fig_names = {'nominal_geometry_viz',...
                     'nominal_power_pdf',...
                     'nominal_power_matrix',...
                     'drag_convergence',...
                     'slamming_model_comparison_float',...
                     'slamming_model_comparison_spar'};
        tab_names = {};
    end

    methods
        function obj = RunSingleFigFunc(varargin)
            obj = obj@GenericAnalysis(varargin{:});
            obj.extra_outputs = { ...
                'results/RunSingleFigFunc/intermed_created_figs_1.fig', ...
                'results/RunSingleFigFunc/intermed_created_figs_4.fig', ...
                'results/RunSingleFigFunc/intermed_created_figs_6.fig', ...
                'results/RunSingleFigFunc/intermed_created_figs_3.fig', ...
                'results/RunSingleFigFunc/intermed_created_figs_5.fig', ...
                'results/RunSingleFigFunc/intermed_created_figs_2.fig' ...
            };
        end
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
