%https://www.mathworks.com/matlabcentral/fileexchange/50477-pareto-filtering
%[AUTOGENERATED]
function [ P_matrix, idxs] = paretoFront( P_matrix )
% Function paretoFront
%
% :param P_matrix: P_matrix
% :returns: P_matrix
% :returns: idxs
% Filters a set of points P according to Pareto dominance, i.e., points
% that are dominated (both weakly and strongly) are filtered.
%
% Inputs:
%
%   - P_matrix    : N-by-D matrix, where N is the number of points and D is the 
%            number of elements (objectives) of each point.
%
% Outputs:
%
%   - P_matrix    : Pareto-filtered P_matrix
%   - idxs : indices of the non-dominated solutions
%
% Example::
%
%   p = [1 1 1; 2 0 1; 2 -1 1; 1, 1, 0];
%   [f, idxs] = paretoFront(p)
%   f = [1 1 1; 2 0 1]
%   idxs = [1; 2]
[i, dim] = size(P_matrix);
idxs = [1 : i]';
while i >= 1
    old_size = size(P_matrix,1);
    indices = sum( bsxfun( @ge, P_matrix(i,:), P_matrix ), 2 ) == dim;
    indices(i) = false;
    P_matrix(indices,:) = [];
    idxs(indices) = [];
    i = i - 1 - (old_size - size(P_matrix,1)) + sum(indices(i:end));
end    
end