%[DOCS AUTOGENERATED]
function figs = pareto_curve_heuristics(r1,r2)
% Function pareto_curve_heuristics
%
% :param r1: r1
% :param r2: r2
% :returns: Figure handles

    % if no arguments are passed, it loads and plots the most recent two runs.
    % if one argument is passed, it plots that run.
    % if two arguments are passed, it plots both those runs.

    if nargin == 0
        d = dir("**/pareto_search_results*");
        r1 = load(d(end).name);
        r2 = load(d(end-1).name);
    end
    if nargin == 1
        load_two = false;
    else
        load_two = true;
    end

    p0 = parameters();
    b = var_bounds();
    p_w = parameters('wecsim');
    b_w = var_bounds('wecsim');

    if ~isequaln(r1.p,p0)
        warning(['You are loading results with different parameters than your ' ...
            'local machine right now. WecSim validation results (p_w) may be incorrect.'])
    end

    if ~isfield(r1,'tol')
        r1.tol = 1e-6;
    end

    new_objs = true; % switch between LCOE-Pvar (old) and capex-Pavg (new)

    [~,f1] = constraint_active_plot(r1.residuals,r1.fval,r1.tol,b,new_objs);

    cols = b.idxs_recover;
    X = r1.x(:,cols); % swap indices based on solver generated function
    X = [X ones(length(X),1)]; % add extra column for material 
    LCOE = r1.fval(:,1);
    Pvar = r1.fval(:,2);

    [J1, bestJ1, idx_best_J1, J1_nom, J1_nom_sim, J1_solar, J1_balanced,...
     J2, bestJ2, idx_best_J2, J2_nom, J2_nom_sim, J2_solar, J2_balanced,...
     x_best_J1, x_best_J2, x_nom, x_balanced, idxo, LCOE_nom, idx_min_LCOE] = process_pareto_front(LCOE,Pvar,X,r1.p,p_w,b,b_w,new_objs);
    
    %% super simple "pareto" plot of just single objective optimizations
    showSingleObj = true;
    showImages = false;
    showLCOEContours = false;
    f2 = pareto_plot(J1, bestJ1, idx_best_J1, J1_nom, J1_nom_sim, J1_solar, J1_balanced,...
                J2, bestJ2, idx_best_J2, J2_nom, J2_nom_sim, J2_solar, J2_balanced,...
                x_best_J1, x_best_J2, x_nom, x_balanced, [], showSingleObj, ...
                showImages, showLCOEContours, r1.p, new_objs, [], [], idx_min_LCOE);
    
    %% simple pareto plot
    showSingleObj = false;
    showImages = false;
    showLCOEContours = true;
    f3 = pareto_plot(J1, bestJ1, idx_best_J1, J1_nom, J1_nom_sim.*[1 NaN], J1_solar, J1_balanced,...
                J2, bestJ2, idx_best_J2, J2_nom, J2_nom_sim.*[1 NaN], J2_solar, J2_balanced,...
                x_best_J1, x_best_J2, x_nom, x_balanced, idxo, showSingleObj, ...
                showImages, showLCOEContours, r1.p, new_objs, LCOE_nom, min(LCOE), idx_min_LCOE);
    
    %% plot pareto front with annotations and embedded images of three recommended designs
    showSingleObj = true;
    showImages = true;
    showLCOEContours = false;
    f4 = pareto_plot(J1, bestJ1, idx_best_J1, J1_nom, J1_nom_sim.*[1 NaN], J1_solar, J1_balanced,...
                J2, bestJ2, idx_best_J2, J2_nom, J2_nom_sim.*[1 NaN], J2_solar, J2_balanced,...
                x_best_J1, x_best_J2, x_nom, x_balanced, idxo, showSingleObj, ...
                showImages, showLCOEContours, r1.p, new_objs, [], [], idx_min_LCOE);
    
    %% plots for DVs as a fn of percent along the pareto
    J1_max = Inf;%p.LCOE_max;
    [f5,f6,f8] = design_heuristics_plot(J1, bestJ1, idx_best_J1, x_best_J1, ...
                           J2, bestJ2, idx_best_J2, X, idxo, J1_max, b.var_names_pretty(1:end-1),new_objs, r1.p);
    f9 = lcoe_tangent_contours_plot(J1(idxo), J2(idxo), r1.p);

    %% double pareto plot, if plotting two results
    if load_two
        [~,f7] = constraint_active_plot(r2.residuals,r2.fval,r2.tol,b,new_objs);

        X = r2.x(:,cols); % swap indices based on solver generated function
        X = [X ones(length(X),1)]; % add extra column for material 
        LCOE = r2.fval(:,1);
        Pvar = r2.fval(:,2);
    
        [J1, bestJ1, idx_best_J1, J1_nom, J1_nom_sim, J1_solar, J1_balanced,...
         J2, bestJ2, idx_best_J2, J2_nom, J2_nom_sim, J2_solar, J2_balanced,...
         x_best_J1, x_best_J2, x_nom, x_balanced, idxo, LCOE_nom, idx_min_LCOE] = process_pareto_front(LCOE,Pvar,X,r2.p,p_w,b,b_w,new_objs);
        
        %% simple pareto plot
        showSingleObj = false;
        showImages = false;
        showLCOEContours = true;
        f3 = pareto_plot(J1, bestJ1, idx_best_J1, J1_nom, J1_nom_sim.*[1 NaN], J1_solar, J1_balanced,...
                    J2, bestJ2, idx_best_J2, J2_nom, J2_nom_sim.*[1 NaN], J2_solar, J2_balanced,...
                    x_best_J1, x_best_J2, x_nom, x_balanced, idxo, showSingleObj, ...
                    showImages, showLCOEContours, r2.p, new_objs, LCOE_nom, min(LCOE), idx_min_LCOE, f3);
        legend(r1.p.control_type,'',r2.p.control_type,'LCOE ($/kWh)','Location','northwest');
        xlim([40 180])
        ylim([.6 1.85])
    end

    figs = [f1, f2, f3, f4, f5, f6];
    if load_two
        figs = [figs f7];
    end
    figs = [figs f8, f9];
end
%%
function [J1, bestJ1, idx_best_J1, J1_nom, ...
         J1_nom_sim,  J1_solar,  J1_balanced,...
         J2, bestJ2, idx_best_J2, J2_nom, ...
         J2_nom_sim, J2_solar, J2_balanced,...
         x_best_J1, x_best_J2, x_nom, x_balanced, ...
         idxo, LCOE_nom, idx_min_LCOE] = process_pareto_front(LCOE,Pvar,X,p,p_w,b,b_w,new_objs)
    
    if new_objs
        num_points = size(X,1);
        P_avg = zeros(num_points, 1);
        for i=1:num_points
            [~, ~, ~, val] = simulation(X(i,:),p);
            P_avg(i) = val.power_avg;
        end
        J1 = P_avg;
        J1_fieldname = 'power_avg';
        J1_fieldidx = ':';
        J1_mult = 1/1000; % W to kW

        capex_design = Pvar; % second sim output means something different
        J2 = capex_design;
        J2_fieldname = 'J_capex_design';
        J2_fieldidx = 4;
        J2_mult = 1; % $M

        J1_solar = NaN;
        J2_solar = NaN;

        J1_balanced_approx = b.power_balanced;
        min_max_sign = [-1 1]; % -1 for maximize, 1 for minimize

    else
        J1 = LCOE;
        J1_fieldname = 'LCOE';
        J1_fieldidx = 4;
        J1_mult = 1; % $/kWh

        J2 = Pvar;
        J2_fieldname = 'c_v';
        J2_fieldidx  = ':';
        J2_mult = 1; % percent (0-100)
    
        % solar
        J1_solar = 0.03; % LCOE solar
        J2_solar = 125;  % P var solar

        J1_balanced_approx = .2;
        min_max_sign = [1 1];
    end

    % find basic pareto front
    [~,idxo] = paretoFront(-min_max_sign .* [J1 J2]);
    [bestJ1,idx_best_J1] = min(min_max_sign(1)*J1);
    bestJ1 = min_max_sign(1) * bestJ1;
    [bestJ2,idx_best_J2] = min(min_max_sign(2)*J2);
    bestJ2 = min_max_sign(2) * bestJ2;
    [~,idx_min_LCOE] = min(LCOE);

    % RM3 nominal - actual
    RM3_report = validation_inputs('report');
    RM3_wecsim = validation_inputs('wecsim');
    try
        J1_nom = [RM3_report.(J1_fieldname)(J1_fieldidx),...
                  RM3_wecsim.(J1_fieldname)(J1_fieldidx)];
        J2_nom = [RM3_report.(J2_fieldname)(J2_fieldidx),...
                  RM3_wecsim.(J2_fieldname)(J2_fieldidx)];
        LCOE_nom = RM3_report.LCOE(4);
    catch
        J1_nom = [NaN NaN]; % fixme
        J2_nom = [NaN NaN];
    end
    
    % RM3 nominal - simulated
    x_nom = [b.X_noms b_w.X_noms];
    x_nom(end+1,:) = 1;

    [~, ~, ~, val_report_sim] = simulation(x_nom(:,1),p);
    [~, ~, ~, val_wecsim_sim] = simulation(x_nom(:,2),p_w);
    try
        J1_report_sim = val_report_sim.(J1_fieldname);
        J2_report_sim = val_report_sim.(J2_fieldname);
        J1_wecsim_sim = val_wecsim_sim.(J1_fieldname);
        J2_wecsim_sim = val_wecsim_sim.(J2_fieldname);
    catch
        J1_report_sim = NaN; % fixme
        J2_report_sim = NaN;
        J1_wecsim_sim = NaN;
        J2_wecsim_sim = NaN;
    end
    
    J1_nom_sim = [J1_report_sim, J1_wecsim_sim];
    J2_nom_sim = [J2_report_sim, J2_wecsim_sim];

    % balanced design
    [~,idx_balanced] = min(abs(J1-J1_balanced_approx));
    J1_balanced = J1(idx_balanced);
    J2_balanced = J2(idx_balanced);
    
    % idenitfy design variables for best designs
    x_best_J1 = X(idx_best_J1,:)
    x_best_J2 = X(idx_best_J2,:)
    x_balanced = X(idx_balanced,:)

    % apply multplier to all J1
    J1s = {J1, bestJ1, J1_nom, J1_nom_sim, J1_solar, J1_balanced};
    J1s_scaled = cellfun(@(x) x * J1_mult, J1s, 'UniformOutput', false);
    [J1, bestJ1, J1_nom, J1_nom_sim, ...
        J1_solar, J1_balanced] = deal(J1s_scaled{:});

    % apply multiplier to all J2
    J2s = {J2, bestJ2, J2_nom, J2_nom_sim, J2_solar, J2_balanced};
    J2s_scaled = cellfun(@(x) x * J2_mult, J2s, 'UniformOutput', false);
    [J2, bestJ2, J2_nom, J2_nom_sim, ...
        J2_solar, J2_balanced] = deal(J2s_scaled{:});
         
end

%%
function [f] = pareto_plot(J1, bestJ1, idx_best_J1, J1_nom, J1_nom_sim, J1_solar, J1_balanced,...
                          J2, bestJ2, idx_best_J2, J2_nom, J2_nom_sim, J2_solar, J2_balanced,...
                          x_best_J1, x_best_J2, x_nom, x_balanced, idxo, showSingleObj,...
                          showImages, showLCOEContours, p, new_objs, LCOE_nom, LCOE_min, idx_min_LCOE, fig)
    if ~exist('fig','var')
        f = figure;
        pareto_color = 'b';
        pareto_shape = 's';
    else
        f = figure(fig);
        pareto_color = '#9999ff';
        pareto_shape = 'o';
    end

    % overall pareto front
    plot(J1(idxo),J2(idxo),pareto_shape,'Color',pareto_color,'MarkerEdgeColor',...
        pareto_color,'MarkerFaceColor',pareto_color,'HandleVisibility','on')
    hold on
    
    % utopia point
    plot(bestJ1,bestJ2,'gp','MarkerFaceColor','g','MarkerSize',20,'HandleVisibility','off')
    
    % RM3 nominal reference - report
    plot(J1_nom(1),    J2_nom(1),    'rd','MarkerFaceColor','r','HandleVisibility','off')
    plot(J1_nom_sim(1),J2_nom_sim(1),'rs','MarkerFaceColor','r','HandleVisibility','off')

    % RM3 nominal reference - wecsim
    plot(J1_nom(2),    J2_nom(2),    'md','HandleVisibility','off')
    plot(J1_nom_sim(2),J2_nom_sim(2),'ms','HandleVisibility','off')
    
    if showSingleObj  
        plot(J1(idx_best_J1),J2(idx_best_J1), 'gs','MarkerFaceColor','g','HandleVisibility','off')
        plot(J1(idx_best_J2),J2(idx_best_J2), 'rs','MarkerFaceColor','r','HandleVisibility','off')
        plot(J1(idx_min_LCOE),J2(idx_min_LCOE),'bs','MarkerFaceColor','b','HandleVisibility','off')
        plot(J1_balanced,J2_balanced,'ms','MarkerFaceColor','m','HandleVisibility','off')
    end
    
    % axis labels
    if new_objs
        xlabel('Average Electrical Power (kW)')
        ylabel('Structural and PTO Cost ($M)')
        xlim([.9*min(J1) 1.1*max(J1)])
        ylim([.9*min(J2) 1.05*max(J2)])
        [T_grid,Hs_grid] = meshgrid(p.T,p.Hs);
        P_wave = p.rho_w * p.g^2 / (64*pi) .* T_grid .* (Hs_grid.^2);
        CW_max = p.g * T_grid.^2 / (4*pi^2);
        P_rad_limit = P_wave .* CW_max .* p.eff_array;
        P_avg_rad_limit_kW = sum(P_rad_limit .* p.JPD/100, 'all') / 1000;
        xline(P_avg_rad_limit_kW,'k--','HandleVisibility','off')
    else
        xlabel('LCOE ($/kWh)')
        ylabel('Power Variation (%)')
        xlim([0 1])
        ylim([25 165])
    end
    
    title('Pareto Front')
    improvePlot
    
    % solar reference
    yellow = [1, .87, .2];
    plot(J1_solar, J2_solar,'o','MarkerSize',12,'MarkerEdgeColor',yellow,...
        'MarkerFaceColor',yellow,'HandleVisibility','off')
    % for the yellow color to work, do not use improvePlot below here
    
    % text labels
    sz = 14;
    text(J1_nom(1)+2,J2_nom(1)+.02,'RM3 Report','FontSize',sz)
    text(J1_nom(1)+.01,J2_nom(1)-5,'Actual [10]','FontSize',sz)
    text(J1_nom_sim(1)-.02,J2_nom_sim(1)+5,'RM3 Report','FontSize',sz)
    text(J1_nom_sim(1)+.03,J2_nom_sim(1)-.05,'Sim','FontSize',sz)

    text(J1_nom(2)+.03,J2_nom(2),'RM3 WecSim','FontSize',sz)
    text(J1_nom(2)+.01,J2_nom(2)-5,'Actual','FontSize',sz)
    text(J1_nom_sim(2)-.02,J2_nom_sim(2)+5,'RM3 WecSim','FontSize',sz)
    text(J1_nom_sim(2)+.03,J2_nom_sim(2),'Sim','FontSize',sz)

    text(bestJ1+.03,bestJ2-2,'Utopia Point','FontSize',sz)
    text(J1_solar+.03,J2_solar,'Solar','FontSize',sz)
    if showSingleObj
        xx = xlim;
        yy = ylim;
        x_spacing = (xx(2) - xx(1)) / 50;
        y_spacing = (yy(2) - yy(1)) / 50;
        text(J1(idx_best_J1)+.5*x_spacing, J2(idx_best_J1)+y_spacing,   {'Most','Power'},     'FontSize',sz)
        text(J1(idx_best_J2)+   x_spacing, J2(idx_best_J2)-y_spacing,    'Least Cost',        'FontSize',sz)
        text(J1(idx_min_LCOE)+  x_spacing, J2(idx_min_LCOE)+y_spacing,   {'Min','LCOE'},      'FontSize',sz)
        text(J1_balanced    -   x_spacing, J2_balanced    -9*y_spacing, {'Balanced','Design'},'FontSize',sz)
    end

    if showLCOEContours
        overlay_LCOE(p, LCOE_nom, LCOE_min)
    end

    if showImages   % small pictures of best geometries
        ylim([0.58, 2.3])

        upper_right = [.75 .512];
        mini_plot(upper_right,x_best_J1,p)

        lower_left = [.1 .18];
        mini_plot(lower_left,x_best_J2,p)
        
        balanced_pos = [.55 .35];
        mini_plot(balanced_pos,x_balanced,p)

        report_pos = [.21,.625];
        mini_plot(report_pos,x_nom(:,1),p)
        
        %wecsim_pos = [.28 .65];
        %mini_plot(wecsim_pos,x_nom(:,2),p)
    end

end

function mini_plot(pos, x, p)
    mini_plot_size = [.2 .22];
    axes('Position',[pos mini_plot_size])
    box on
    visualize_geometry(x,p,true);
    set(gca,'XTickLabel',[],'YTickLabel',[])
end

%%
function [f_unfiltered,f_filtered,f_nondim] = design_heuristics_plot(overallJ1, J1_best, idx_best_J1, x_best_J1, ...
                                     overallJ2, J2_best, idx_best_J2, ...
                                     overallX, idxo, J1_max, var_names, new_objs, p)

    % filter out pareto nonoptimal points
    J1_pareto = overallJ1(idxo);
    J2_pareto = overallJ2(idxo);
    X_pareto  = overallX(idxo,1:end-1); % get rid of material

    % filter out J1 above thresh
    idx_keep = J1_pareto < J1_max;

    J1_worst = overallJ1(idx_best_J2);
    J2_worst = overallJ2(idx_best_J1);

    % desired direction
    if new_objs
        dir = {'max','min'};
    else
        dir = {'min','min'};
    end

    % order from left to right on pareto front appearance, 
    % and normalize by optimal J1 values
    [X_pareto_ordered_normed,...
     J1_pareto_ordered_normed, ...
     J2_pareto_ordered_normed,...
     pct_angle] = pareto_order_normalize(J1_pareto(idx_keep), J2_pareto(idx_keep), ...
                                         X_pareto(idx_keep,:), dir,...
                                         J1_best, J1_worst, ...
                                         J2_best, J2_worst, x_best_J1(1:end-1), true);
    
    % apply filter
    backwards = strcmp(dir(1),'max');
    [X_filtered,pct_angle_even] = low_pass_filter(pct_angle, X_pareto_ordered_normed, backwards);
    
    % plot unfiltered
    f_unfiltered = figure;
    semilogy(pct_angle,X_pareto_ordered_normed)
    title('Unfiltered Design Heuristics')
    xlabel('Percent along the Pareto Curve')
    ylabel('Normalized Optimal Design Value')
    legend(var_names,'Location','eastoutside')
    ylim([0 15])
    improvePlot
    grid on
    set(gca,'YMinorGrid','on')
    
    % plot filtered
    cols = {'r:','r--','r-','r-.','r.',...       % bulk dims
            'b:','b--',...                       % PTO
            'g:','g--','g-','g-.','g.'}; % 'g*'  % structural
    f_filtered = figure;
    sub1 = subplot(2,1,1);
    for i=1:size(X_pareto_ordered_normed,2)
        semilogy(pct_angle_even,X_filtered(:,i),cols{i})
        hold on
    end
    
    % make fake major grid lines (didn't do "grid on" because then major lines show up for .2 .5 2 5 too)
    x_grid = [3 97];
    y_grid = [.1 1];
    y_tick = [.01 .02 .05 .1 .2 .5 1 2 5];
    for i=1:length(y_grid)
        plot(x_grid, y_grid(i)*[1 1],'Color',[.85 .85 .85]);
    end

    y_limits = [.9*min(X_filtered,[],'all'), 1.1*max(X_filtered,[],'all')];
    plot(pct_angle, y_limits(1) * ones(size(pct_angle)), 'ks','MarkerSize',5,'MarkerFaceColor','k','HandleVisibility','off')
    
    title('Design Trends')
    %xlabel('Percent along the Pareto Curve')
    ylabel('Normalized Optimal Design Value')
    ylim(y_limits)
    set(sub1,'YTick',y_tick)
    improvePlot
    
    leg1 = legend(var_names,'Location','eastoutside');
    set(sub1,'YMinorGrid','on')
    set(sub1,'XGrid','on')
    set(sub1, 'Children', flipud(get(sub1, 'Children')) ) % put fake gridlines behind real lines
    
    if new_objs
        legend_text = {'Average Electrical Power','Structural and PTO Cost'};
        scale_1 = 1;
        scale_2 = 1; %100;
    else
        scale_1 = 100; % convert $ to cents
        scale_2 = 1;
        cent = char(0162);
        legend_text = {['LCOE (' cent '/kWh)'],'c_v (%)'};
    end

    % objective heuristics
    sub2 = subplot(2,1,2); %figure
    plot(pct_angle, scale_1 * J1_pareto_ordered_normed,'Color',[0.4940 0.1840 0.5560]) % purple
    hold on
    plot(pct_angle, scale_2 * J2_pareto_ordered_normed,'Color',[0.4660 0.6740 0.1880]) % green
    grid on
    xlabel('Percent along the Pareto Curve')
    ylabel('Normalized Objective Value')
    improvePlot
    l2 = legend(legend_text,Location='eastoutside');

    set(gcf,"Position",[100 100 715 835]) % make wider so x major grid shows for every 20
    leg1.Position(1:2) = [.78 .43];
    sub1.Position(2:4) = [.5 .6 .4];
    sub2.Position(3:4) = [.6 .28];
    l2.Position(1:2) = [.54 .16];

    % nondimensionalized design variables (no front-point-to-front-point normalization)
    X_nondim = nondimensionalize_design_vars(overallX, p);
    X_pareto_nd = X_nondim(idxo,:);
    [X_pareto_nd_ordered,...
     ~, ~,...
     pct_angle_nd] = pareto_order_normalize(J1_pareto(idx_keep), J2_pareto(idx_keep), ...
                                            X_pareto_nd(idx_keep,:), dir,...
                                            J1_best, J1_worst, ...
                                            J2_best, J2_worst, [], false);
    [X_filtered_nd,pct_angle_even_nd] = low_pass_filter(pct_angle_nd, X_pareto_nd_ordered, backwards);

    f_nondim = figure;
    semilogy(pct_angle_even_nd, X_filtered_nd)
    grid on
    xlabel('Percent along the Pareto Curve')
    ylabel('Nondimensional Design Value')
    title('Nondimensional Design Trends')
    legend(nondim_var_names(var_names),'Location','eastoutside')
    improvePlot
end

function [filtered, t_even_spread] = low_pass_filter(time, signals, backwards)

    num_sigs = size(signals,2);

    windowSize = round(length(time) * 5/100);
    b = (1/windowSize) * ones(1,windowSize);
    a = 1;

    n_points_interp = 51;
    t_even_spread = linspace(min(time),max(time),n_points_interp);

    filtered = zeros(n_points_interp, num_sigs);
    
    for i=1:num_sigs
        % interpolate signal onto uniform time grid
        sig = signals(:,i);
        sig_even_spread = interp1(time,sig,t_even_spread).';

        % flip if filtering backwards in time
        if backwards
            sig_even_spread = flipud(sig_even_spread);
        end

        % pad, apply moving average filter, and crop away padding
        sig_padded = [ones(windowSize,1); sig_even_spread];
        yy = filter(b,a,sig_padded); 
        yy_crop = yy((windowSize+1):end);

        % flip if filtering backwards in time
        if backwards
            yy_crop = flipud(yy_crop); % apply filter backwards
        end

        filtered(:,i) = yy_crop;
    end
end

function [] = overlay_LCOE(p, LCOE_nom, LCOE_min)
    n_points = 30;
    P_elec_kW = xlim;
    C_design_M = ylim;
    P_elec_W = 1000*linspace(P_elec_kW(1), P_elec_kW(2), n_points);
    C_design = 1e6*linspace(C_design_M(1), C_design_M(2), n_points);

    [P_ELEC,C_DESIGN] = meshgrid(P_elec_W,C_design);
    LCOE = LCOE_from_capex_design_power(C_DESIGN, p.N_WEC, P_ELEC, p.FCR, p.eff_array);

    hold on
    levs = [LCOE_min;
            .4; .5; .6;
            LCOE_nom];
    grey = [.85 .85 .85];
    [~,h] = contour(P_ELEC/1000,C_DESIGN/1e6,LCOE,levs,'Color',grey,'ShowText','on','LabelSpacing',400);
    if isMATLABReleaseOlderThan("R2022b")
        h.LevelList = round(h.LevelList,3); % for old versions, round the contours directly. Will be slightly off from scatter points.
    else
        h.LabelFormat = '%0.2f'; % for new versions, just round the text
    end

    legend('LCOE ($/kWh)','Location','northwest')

end

function [X_pareto_ordered_normed,...
          J1_pareto_ordered_normed, ...
          J2_pareto_ordered_normed, pct_angle] = pareto_order_normalize(J1_pareto, J2_pareto, X_pareto, dir,  ...
                                                                        J1_best, J1_worst, J2_best, J2_worst,...
                                                                        X_best_J1, normalize_by_best)

    % sort from min J1 to max J1 (left to right)
    [J1_pareto_ordered,idx_order] = sort(J1_pareto);
    J2_pareto_ordered = J2_pareto(idx_order);
    X_pareto_ordered = X_pareto(idx_order,:);
    
    if normalize_by_best
        X_pareto_ordered_normed = X_pareto_ordered ./ repmat(X_best_J1,length(idx_order),1);
    else
        X_pareto_ordered_normed = X_pareto_ordered;
    end
    J1_pareto_ordered_normed = J1_pareto_ordered / J1_best;
    J2_pareto_ordered_normed = J2_pareto_ordered / J2_worst;

    % ranges
    J1_range = J1_best - J1_worst;
    J2_range = J2_best - J2_worst;

    % fraction along each objective
    frac_J1 = abs( (J1_worst - J1_pareto_ordered) / J1_range );
    frac_J2 = abs( (J2_worst - J2_pareto_ordered) / J2_range );

    % choose num and den to keep 0% corresponding to left (min J1) and 
    % 100% corresponding to right (max J1). See notebook p83 1/25/25
    if strcmp(dir(1),'max')
        num = frac_J1;
        den = frac_J2;
    elseif strcmp( dir(1),'min')
        num = frac_J2;
        den = frac_J1;
    else
        error('invalid direction string')
    end

    % find angle along circle with origin at nadir point - useful because 
    % diminishing returns often makes pareto look like a quarter circle
    angle = atan( num ./ den);

    % express angle as percentage: 0 to pi/2 maps 0 to 100
    pct_angle = 100/(pi/2) * angle;
    pct_angle(pct_angle==-100) = 100;
    
end

function X_nondim = nondimensionalize_design_vars(X_full, p)
    X = X_full(:,1:end-1);
    X_nondim = X;
    D_s = X(:,1);
    D_f = X(:,2);
    n_pts = size(X_full,1);
    F_uncon = nan(n_pts,1);
    P_uncon = nan(n_pts,1);
    for ii = 1:n_pts
        [~,~,~,val_i] = simulation(X_full(ii,:), p);
        F_uncon(ii) = max(val_i.force_ptrain/1e6, 1e-6);
        P_uncon(ii) = max(val_i.power_max/1e5, 1e-6);
    end
    X_nondim(:,1) = D_s ./ D_f;
    X_nondim(:,3) = X(:,3) ./ D_f;
    X_nondim(:,4) = X(:,4) ./ D_f;
    X_nondim(:,5) = X(:,5) ./ D_f;
    X_nondim(:,6) = X(:,6) ./ F_uncon;
    X_nondim(:,7) = X(:,7) ./ P_uncon;
    X_nondim(:,8) = (X(:,8)/1000) ./ D_f;
    X_nondim(:,9) = (X(:,9)/1000) ./ D_f;
    X_nondim(:,10) = (X(:,10)/1000) ./ D_f;
    X_nondim(:,11) = (X(:,11)/10) ./ D_f;
    X_nondim(:,12) = X(:,12) ./ D_f;
end

function names_out = nondim_var_names(names_in)
    names_out = names_in;
    names_out{1} = 'D_s/D_f';
    names_out{3} = 'T_{f,2}/D_f';
    names_out{4} = 'h_s/D_f';
    names_out{5} = 'h_{fs,clear}/D_f';
    names_out{6} = 'F_{max}/F_{max,unconstrained}';
    names_out{7} = 'P_{max}/P_{max,unconstrained}';
    names_out{8} = 't_{fb}/D_f';
    names_out{9} = 't_{sr}/D_f';
    names_out{10} = 't_d/D_f';
    names_out{11} = 'h_{stiff,f}/D_f';
    names_out{12} = 'h_{1,stiff,d}/D_f';
end

function f = lcoe_tangent_contours_plot(P_pareto_kW, C_pareto_M, p)
    f = figure;
    t = tiledlayout(2,2);
    t.TileSpacing = 'compact';

    P = P_pareto_kW(:) * 1000;
    C = C_pareto_M(:) * 1e6;
    [P,idx_sort] = sort(P);
    C = C(idx_sort);
    [P,ia] = unique(P,'stable');
    C = C(ia);

    ellipse = fit_ellipse_arc(P,C);

    alpha_non_design = 0.741;
    capex_indep_nom = (12.68e6 * p.N_WEC^(-alpha_non_design) + 1.24e6);
    alpha_opex = 0.5567;
    opex_nom = 1.193e6 * p.N_WEC^-alpha_opex;

    FCR_values = p.FCR .* [0.75 0.9 1.1 1.25];
    opex_vec = linspace(0.5*opex_nom, 1.5*opex_nom, 45);
    capex_indep_vec = linspace(0.5*capex_indep_nom, 1.5*capex_indep_nom, 45);
    [OPEX,CAPEX_INDEP] = meshgrid(opex_vec, capex_indep_vec);

    for i = 1:length(FCR_values)
        FCR_i = FCR_values(i);
        pct_star = nan(size(OPEX));
        for j = 1:numel(OPEX)
            pct_star(j) = tangent_percent_from_econ_terms(ellipse, FCR_i, OPEX(j), CAPEX_INDEP(j));
        end
        nexttile
        contourf(OPEX/1e6, CAPEX_INDEP/1e6, pct_star, 0:10:100, 'LineStyle','none')
        colorbar
        xlabel('OPEX design-independent ($M/yr)')
        ylabel('CAPEX design-independent ($M)')
        title(sprintf('FCR = %.3f', FCR_i))
        grid on
        improvePlot
    end
end

function ellipse = fit_ellipse_arc(P,C)
    p0 = [mean(P), mean(C), 0.6*(max(P)-min(P)), 0.6*(max(C)-min(C))];
    lb = [min(P)-2*range(P), min(C)-2*range(C), 1, 1];
    ub = [max(P)+2*range(P), max(C)+2*range(C), 10*range(P)+1, 10*range(C)+1];
    obj = @(q) sum(( ((P-q(1))./q(3)).^2 + ((C-q(2))./q(4)).^2 - 1 ).^2);
    opts = optimoptions('fmincon','Display','off');
    q = fmincon(obj,p0,[],[],[],[],lb,ub,[],opts);
    ellipse = struct('P0',q(1),'C0',q(2),'a',q(3),'b',q(4), ...
                     'Pmin',min(P),'Pmax',max(P));
end

function pct = tangent_percent_from_econ_terms(ellipse, FCR, opex, capex_indep)
    K = capex_indep + opex/FCR;
    f_root = @(P) P .* dC_dP_ellipse(ellipse, P) - C_ellipse(ellipse, P) - K;
    P_scan = linspace(ellipse.Pmin, ellipse.Pmax, 300);
    val = f_root(P_scan);
    idx = find(diff(sign(val))~=0,1,'first');
    if isempty(idx)
        [~,idx_min] = min(abs(val));
        P_star = P_scan(idx_min);
    else
        P_star = fzero(f_root, [P_scan(idx), P_scan(idx+1)]);
    end
    P_star = max(min(P_star, ellipse.Pmax), ellipse.Pmin);
    s = linspace(ellipse.Pmin, ellipse.Pmax, 500);
    C_s = C_ellipse(ellipse,s);
    ds = sqrt(diff(s).^2 + diff(C_s).^2);
    s_cum = [0 cumsum(ds)];
    s_star = interp1(s, s_cum, P_star, 'linear','extrap');
    pct = 100 * s_star / s_cum(end);
end

function C = C_ellipse(e, P)
    term = max(0, 1 - ((P - e.P0)./e.a).^2);
    C_upper = e.C0 + e.b * sqrt(term);
    C_lower = e.C0 - e.b * sqrt(term);
    if abs(mean(C_upper) - e.C0) < abs(mean(C_lower) - e.C0)
        C = C_lower;
    else
        C = C_upper;
    end
end

function dC = dC_dP_ellipse(e, P)
    denom = max(1e-12, sqrt(max(0, 1 - ((P - e.P0)./e.a).^2)));
    base = -e.b * (P - e.P0) ./ (e.a^2 .* denom);
    C_upper = e.C0 + e.b * sqrt(max(0, 1 - ((P - e.P0)./e.a).^2));
    C_lower = e.C0 - e.b * sqrt(max(0, 1 - ((P - e.P0)./e.a).^2));
    if abs(mean(C_upper) - e.C0) < abs(mean(C_lower) - e.C0)
        dC = -base;
    else
        dC = base;
    end
end
