%[DOCS AUTOGENERATED]
function [DV_table, out_table, figs] = compare(p,b,X,vals)
% Function compare
%
% :param p: Parameter struct
% :param b: Design variable bounds struct
% :param X: Design variable vector
% :param vals: vals
% :returns: DV_table
% :returns: out_table
% :returns: Figure handles

titles = {'Nominal','Min LCOE','Min Capex','Max Power','Balanced'};
color = {'k','b','r','g','m'};
num_designs = length(titles);

%% geometry comparison
h_geom = figure;
% sort by float diameter
idx_D_f = strcmp(b.var_names,'D_f');
D_f = X(:,idx_D_f);
[~,biggest_to_smallest] = sort(D_f,'descend');

% find x range
idx_D_s = strcmp(b.var_names,'D_s');
D_d = p.D_d_over_D_s * X(:,idx_D_s);
biggest_diam = max([D_f;D_d]);
x_max = biggest_diam/2 * 1.1;

% find y range
T_s = p.T_s_over_D_s * X(:,idx_D_s);
y_min = -max(T_s) * 1.1;

% waves
x = linspace(-x_max,x_max,100);
Hs = 3;
T = 7.5;
hold on
waves = plot(x,Hs/2*cos(x*2*pi/T),'c','Linewidth',3);
set(waves,'HandleVisibility','off')

for i=1:num_designs
    x = X(biggest_to_smallest(i),:);
    hold on
    visualize_geometry(x,p,false,color{biggest_to_smallest(i)});
end
xlim([-x_max,x_max])
y_max = max([findobj(gca().Children,'Type','Line').YData]) * 1.1;
ylim([y_min y_max])
legend(titles(biggest_to_smallest),'Position',[0.5941    0.3508    0.2663    0.2167])

%% power probability comparison
h_prob = figure;
t = tiledlayout(2,1);
t.TileSpacing = 'compact';
ylabel(t,'Probability (-)','FontWeight','bold')
for i=1:num_designs
    x = X(i,:);
    hold on
    t = power_PDF(x,p,color{i},t,[false true]);
end
legend(titles{:},'location','best')
delete(nexttile(1)) % delete blank PDF so just CDF remains
h_prob.Position(3:4) = [792 484];

%% power matrix comparison

h_power_matrix = figure;
for i=1:num_designs
    x = X(i,:);
    [~,P_matrix] = simulation(x, p);
    P_matrix = P_matrix / 1e3; % convert W to kW
    [T,Hs] = meshgrid(p.T,p.Hs);

    subplot(2,3,i);
    hold on
    contourf(T,Hs,P_matrix .* p.JPD/100)
    improvePlot
    grid on
    title(titles{i})
    caxis([0 15])
    ax = gca;
    second_col = i==2 || i==5;
    third_col = i==3;
    if second_col
        xoffset = -ax.Position(3)*.25;
    elseif third_col
        xoffset = -ax.Position(3)*.5;
    else
        xoffset = 0;
    end
    second_row = i>3;
    if second_row
        yoffset = ax.Position(4)*.2;
    else
        yoffset = 0;
    end
    set(ax,'Position',[ax.Position(1)+xoffset ax.Position(2)+yoffset ...
        ax.Position(3)*.8 ax.Position(4)*.8])
    set(ax.Title,'FontWeight','normal')
    set(ax,'Layer','top','GridColor',[.9 .9 .9])
end
cb = colorbar('Position',[.8 .175 .08 .685]);
%cb.Label.String = 'Weighted Power (kW)';
sgtitle('Weighted Power (kW)','FontWeight','bold','FontSize',20)
text(-10,-2,'Wave Period T (s)','FontWeight','bold','FontSize',16)
text(-30,5,'Wave Height Hs (m)','FontWeight','bold','FontSize',16,'Rotation',90)

%% hydro coeff comparison plot
h_hydro = hydro_compare(vals,color);
h_hydro_imp = hydro_impedance_compare(vals,color,p,X);

%% stacked cost breakdown + power histogram (nominal vs min LCOE)
h_cost_power = figure;
t_cost = tiledlayout(1,3);
t_cost.TileSpacing = 'compact';
h_cost_power.Position(3:4) = [1200 600];

idx_compare = [1 2]; % nominal and min LCOE
labels_compare = titles(idx_compare);

% PTO cost stack (power + force)
idx_F_max = strcmp(b.var_names,'F_max');
idx_P_max = strcmp(b.var_names,'P_max');
N_WEC = p.N_WEC;
alpha_pto = p.econ_alpha_pto;
pto_power_mult = (p.econ_pto_power_coeff_base + p.econ_pto_power_coeff_scale*N_WEC^(-alpha_pto)) * p.cost_perW_mult;
pto_force_mult = (p.econ_pto_force_coeff_base + p.econ_pto_force_coeff_scale*N_WEC^(-alpha_pto)) * p.cost_perN_mult;
P_max_W = X(idx_compare,idx_P_max) * 1e5;
F_max_N = X(idx_compare,idx_F_max) * 1e6;
pto_power = pto_power_mult * P_max_W;
pto_force = pto_force_mult * F_max_N;

nexttile
bar(categorical(labels_compare), [pto_power pto_force], 'stacked')
ylabel('Cost ($)')
title('PTO Cost Breakdown')
legend({'Power','Force'},'Location','best')
improvePlot

% Structural cost stack (float, column, reaction plate, other)
alpha_struct = p.econ_alpha_struct;
cost_per_kg = (p.econ_struct_capex_base + p.econ_struct_capex_scale * N_WEC^(-alpha_struct)) / p.econ_struct_mass_ref;
struct_stack = zeros(length(idx_compare),4);
for i = 1:length(idx_compare)
    j = idx_compare(i);
    mat_idx = max(1,min(length(p.cost_perkg_mult), round(X(j,end))));
    cpk = cost_per_kg * p.cost_perkg_mult(mat_idx);
    c_float = cpk * vals(j).mass_f;
    c_col = cpk * vals(j).mass_vc;
    c_rp = cpk * vals(j).mass_rp;
    c_other = vals(j).capex_struct - (c_float + c_col + c_rp);
    struct_stack(i,:) = [c_float c_col c_rp max(0,c_other)];
end

nexttile
bar(categorical(labels_compare), struct_stack, 'stacked')
ylabel('Cost ($)')
title('Structural Cost Breakdown')
legend({'Float','Column','Reaction Plate','Other'},'Location','best')
improvePlot

% Power histogram (from power CDF neighborhood implementation)
nexttile
hold on
edges = logspace(log10(10),log10(10000),26);
for i = 1:length(idx_compare)
    [~,P_matrix] = simulation(X(idx_compare(i),:), p);
    P_matrix = P_matrix / 1e3;
    P_matrix(P_matrix==0) = 1e-3;
    P_counts = repelem(P_matrix(:), round(p.JPD(:)*1000));
    N = histcounts(P_counts,edges,'Normalization','probability');
    centers = sqrt(edges(1:end-1).*edges(2:end));
    plot(centers, N, '-o', 'Color', color{idx_compare(i)}, 'DisplayName', labels_compare{i});
end
set(gca,'XScale','log')
xlabel('Average Electrical Power (kW)')
ylabel('Probability (-)')
title('Power Histogram')
legend('Location','best')
grid on
improvePlot

%% design variable table
DV_table = array2table(X(:,1:end-1).', ...
    'VariableNames',titles, 'RowNames', b.var_names_pretty(1:end-1));

%% output table
temp_table = struct2table(vals,'RowNames',titles);
numeric_vals = varfun(@isnumeric, temp_table, 'OutputFormat', 'uniform');
vector_names = {'over_rho','phase','force_surge'};
vector_rows = contains(temp_table.Properties.VariableNames,vector_names);
out_table = rows2vars(temp_table(:,numeric_vals & ~vector_rows));
out_table.Properties.RowNames = fix_underscores(out_table.OriginalVariableNames);
out_table = removevars(out_table,'OriginalVariableNames');

%% design variable stacked number line plot
markers = {'o','x','^','v','d'};
h_stacked_dv = figure;
stacked_number_line(X(:,1:end-1).', b.X_mins, b.X_maxs, color, markers, titles, b.var_names_pretty(1:end-1))

h_stacked_out = figure;
stacked_number_line(out_table{:,:}, [], [], color, markers, titles, out_table.Properties.RowNames);
h_stacked_out.Position(3:4) = [1000  400]; % make taller

figs = [h_geom, h_hydro, h_hydro_imp, h_prob, h_power_matrix, h_cost_power, h_stacked_dv, h_stacked_out];

end

function cell = fix_underscores(cell)
    for i = 1:length(cell)
        str = cell{i};
        if contains(str,'_')
            prefix = extractBefore(str,'_');
            subscript = extractAfter(str,[prefix '_']);
            subscript = strrep(subscript,'_',','); % avoid nested subscripts
            if  length(subscript) > 1
                cell{i} = [prefix '_{' subscript '}'];
            end
        end
    end
end

function f = hydro_compare(vals,colors)
% Return figure handle so callers can capture it if desired
f = figure;

% first subplot: excitation
t = tiledlayout(1,2);
t.TileSpacing = 'compact';
nexttile
hold on
plot(NaN,NaN,['k' '-*'],NaN,NaN,['k' '-.']) % dummy for legend
colororder({'k','k'})
for i=1:length(vals)
    val = vals(i);
    col = colors{i};
    w=unique(val.w(~isnan(val.w)),'stable');
    gamma_f_over_rho_g = unique(val.gamma_f_over_rho_g(~isnan(val.gamma_f_over_rho_g)),'stable');
    gamma_phase_f = unique(val.gamma_phase_f(~isnan(val.gamma_phase_f)),'stable');
    yyaxis left
    plot(w(:,1), gamma_f_over_rho_g(:,1),[col '-*'])
    ylabel('|\gamma_{f}|/(\rhog) (m^{2})')
    yyaxis right
    plot(w(:,1), gamma_phase_f(:,1),     [col '-.'])
    ylabel('\angle\gamma_{f} (rad)')
end
title('Excitation Coefficient')
xlabel('Wave Frequency (\omega)')
xlim([0.3,1.45])
%ylim([-10, 26510])
legend({'|\gamma_{f}|/(\rhog)','\angle\gamma_{f}'})
hold off
improvePlot
h=findobj(gca().Children,"Type","line");
for j = 1:length(h)
    %h(j).MarkerSize = 6;
    %h(j).LineWidth = 1;
end

% second subplot: radiation 
nexttile
hold on
plot(NaN,NaN,['k' '--'],NaN,NaN,['k' '-']); % dummy for legend

for i=1:length(vals)
    val = vals(i);
    col = colors{i};
    w=unique(val.w(~isnan(val.w)),'stable');
    A_f_over_rho = unique(val.A_f_over_rho(~isnan(val.A_f_over_rho)),'stable');
    B_f_over_rho_w = unique(val.B_f_over_rho_w(~isnan(val.B_f_over_rho_w)),'stable');
    plot(w(:,1), A_f_over_rho(:,1),[col '--'],...
        w(:,1), B_f_over_rho_w(:,1),     [col '-'])
end
title('Radiation Coefficients')
xlabel('Wave Frequency (\omega)')
xlim([0.3,1.45])
%ylim([-10, 26900])
legend({'A_{f}/\rho','B_{f}/(\rho\omega)'});
ylabel('A_{f}/\rho (m^{3}), B_{f}/(\rho\omega) (m^{3}/(rad^{2}s^{2}))')
hold off
improvePlot

h=findobj(gca().Children,"Type","line");
for j = 1:length(h)
    %h(j).MarkerSize = 6;
    %h(j).LineWidth = 1;
end

% figure legend for design colors
axLegend = axes('Position',[0.91 0.1 0.08 0.8]);
hold(axLegend,'on')
dummy_style = {'k-','b-','r-','g-','m-'};
for i = 1:length(dummy_style)
    plot(axLegend,NaN,NaN,dummy_style{i})
end
leg = legend(axLegend,{'Nominal','Min LCOE','Min CAPEX','Max Power','Balanced'});
axLegend.Visible = 'off';
try
    leg.Layout.Tile = 'east';
catch
    leg.Location = 'eastoutside';
end

f.Position(3) = 1530;
end

function f = hydro_impedance_compare(vals,colors,p,X)
f = figure;
hold on
for i=1:length(vals)
    val = vals(i);
    col = colors{i};
    w=unique(val.w(~isnan(val.w)),'stable');
    if isempty(w)
        continue
    end
    [B_c,B_f,B_s,K_f,K_s,m_c,m_f,m_s] = linear_coeffs_for_impedance(X(i,:), p, val, w(:,1));
    if p.use_multibody
        [real_G_u,imag_G_u] = multibody_impedance(B_c,B_f,B_s,K_f,K_s,m_c,m_f,m_s,w(:,1));
    else
        resistance = B_f;
        reactance = m_f.*w(:,1) - K_f./w(:,1);
        mag_G_u_squared = 1 ./ (resistance.^2 + reactance.^2);
        real_G_u = resistance .* mag_G_u_squared;
        imag_G_u = -reactance .* mag_G_u_squared;
    end
    G_u = real_G_u + 1i * imag_G_u;
    Z_th = 1./G_u;
    yyaxis left
    plot(w(:,1), abs(Z_th), [col '-*'])
    ylabel('|Z_{th}| (N s/m)')
    yyaxis right
    plot(w(:,1), angle(Z_th), [col '-.'])
    ylabel('\angle Z_{th} (rad)')
end
title('Controlled DOF Thevenin Impedance')
xlabel('Wave Frequency (\omega)')
xlim([0.3,1.45])
legend({'|Z_{th}|','\angle Z_{th}'})
grid on
improvePlot
end

function [B_c,B_f,B_s,K_f,K_s,m_c,m_f,m_s] = linear_coeffs_for_impedance(x, p, val, w)
D_s = x(1);
D_f = x(2);
T_f_2 = x(3);
D_d = p.D_d_over_D_s * D_s;
T_s = p.T_s_over_D_s * D_s;
T = 2*pi./w;
Hs = ones(size(T));
m_float = val.mass_f;
m_spar = val.mass_vc + val.mass_rp;
[m_f,B_f,K_f,~,~,...
 m_s,B_s,K_s,~,~,...
 m_c,B_c] = get_dynamic_coeffs(Hs, T, ...
                               D_f, T_f_2, D_s, D_d, T_s, p.h, ...
                               m_float, m_spar, p.spar_excitation_coeffs,...
                               p.C_d_float, p.C_d_spar, ...
                               p.rho_w, p.g, p.use_MEEM, p.harmonics, ...
                               p.hydro, p.m_k_h_precomputed_op);
end
