function varargout = sim_catch_warning(X, p)
% SIM_CATCH_WARNING  Wrapper around simulation that silently captures warnings.
%
% Calls simulation(X, p) via run_and_catch_warnings so that any known
% warnings are intercepted and do not print to the terminal during
% optimization.  The outputs are identical to those of simulation.
%
% :param X: Design variable vector
% :param p: Parameter struct
% :returns: Same outputs as simulation (J, P_matrix_elec, g_vec, val)

    warning_ids = { ...
        'MDOcean:Simulation:InfNanImaginary', ...
        'MDOcean:GetResponseDrag:OpenLoopUnstable', ...
        'MDOcean:GetResponseDrag:StabilizingFailed', ...
        'MDOcean:GetResponseDrag:AllNanIteration', ...
        'MDOcean:RunMEEM:NegativeAddedMass', ...
        'MDOcean:RunMEEM:NegativeDamping', ...
        'MDOcean:RunMEEM:NegativeDampingGlobal', ...
        'MDOcean:RunMEEM:InvalidGeometry', ...
        'MDOcean:RunMEEM:NonFiniteA', ...
        'MDOcean:RunMEEM:NonFiniteB', ...
        'MDOcean:RunMEEM:NonFiniteC', ...
        'MDOcean:DragIntegral:OutsideLUT', ...
        'MDOcean:circle_intersect_optim:infeasible', ...
        'MDOcean:GetStiffenerEquiv:StiffenerEquivBroke', ...
        'MDOcean:PickWhichRoot:TwoValidSolutions', ...
        'MDOcean:PickWhichRoot:NoValidSolution', ...
        'MDOcean:MultibodyResponse:ZeroOverZero', ...
        'MDOcean:ConstrainedOptCtrl:InfeasibleController', ...
        'MDOcean:ConstrainedOptCtrl:NaNInMagXf', ...
        'MDOcean:ConstrainedOptCtrl:NaNInRealP', ...
        'MDOcean:ConstrainedOptCtrl:NonFiniteError', ...
        'MATLAB:nearlySingularMatrix', ...
        'MATLAB:singularMatrix', ...
        'MATLAB:integral:NonFiniteValue' ...
    };

    [sim_outputs, ~, ~] = run_and_catch_warnings( ...
        @() simulation(X, p), warning_ids, nargout);

    varargout = sim_outputs;

end
