%[AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
            
            tab_report = intermed_result_struct.tab_report;
            tab_wecsim = intermed_result_struct.tab_wecsim;
            
            % merge report and wecsim tables while preserving row order
            sharedCols = intersect(tab_report.Properties.VariableNames, tab_wecsim.Properties.VariableNames);
            tab_report.RowNum = (1:length(tab_report.Properties.RowNames))';
            tab_wecsim.RowNum = length(tab_report.Properties.RowNames) + (1:length(tab_wecsim.Properties.RowNames))';
            
            tab_validation = outerjoin(tab_report, tab_wecsim, 'Keys', [{'RowNum'},sharedCols], 'MergeKeys', true);
            tab_validation = removevars(tab_validation,'RowNum');
            tab_validation.Properties.RowNames = [tab_report.Properties.RowNames; tab_wecsim.Properties.RowNames];

            vector_cols = {'capex','capex_design','J_capex_design','capex_struct','capex_PTO','opex','LCOE'};
            idx_remove = ismember(tab_validation.Properties.VariableNames,vector_cols); 
            tab_validation_latex = rows2vars(tab_validation,'VariableNamingRule','preserve','DataVariables',~idx_remove);
            tab_validation_latex.OriginalVariableNames = remove_underscores(modify_suffix(tab_validation_latex.OriginalVariableNames));
            new_names = {'Variable','MDOcean','Actual','Error','MDOcean ','Actual ','Error '};
            tab_validation_latex = renamevars(tab_validation_latex, tab_validation_latex.Properties.VariableNames, new_names);
            
            fig_array = intermed_result_struct.fig_cost_vs_N_WEC;
            
            tab_array_display = {tab_validation};
            tab_array_latex = {tab_validation_latex};
            tab_firstrows = {'&\multicolumn{3}{c|}{DOE Report RM3 Design \cite{RM3}} & \multicolumn{3}{c}{WEC-Sim RM3 Design} \\'};
            tab_colspecs = {'>{\centering\arraybackslash}p{0.2\linewidth}|c|c|r|c|c|r'};

            end_result_struct.validation_complete = true;
            end_result_struct.validation_table = tab_validation;
end
