%[DOCS AUTOGENERATED]
function intermed_result_struct = analysis_fcn(~,b)
% Function analysis_fcn
%
% :param ~: ~
% :param b: Design variable bounds struct
% :returns: Intermediate results struct (cached heavy analyses)
    % Get constraints information
    % Store results for post-processing
    tab = cell2table(remove_underscores(b.constraint_names.'));
    tab_linear = cell2table(remove_underscores(b.lin_constraint_names.'));
    rows = 1:24; % Only show slamming constraint for one sea state
    intermed_result_struct.constraint_names = tab(rows,:);
    intermed_result_struct.linear_constraint_names = tab_linear;
end
