%[AUTOGENERATED]
function intermed_result_struct = analysis_fcn(p,b)
% Function analysis_fcn
%
% :param p: Parameter struct
% :param b: Design variable bounds struct
% :returns: Intermediate results struct (cached heavy analyses)
    % Run design space exploration experiments
    [X_ins,ratios,LCOE,cost,power,failed] = experiments(p,b);

    cd('..')
    pareto = ParetoFigFunc(p,b);
    pareto = pareto.run_analysis_from_load_if_possible();
    pareto_results_struct = pareto.intermed_result_struct.r1;
    cd('mdocean')
    
    % Store figure for post-processing
    intermed_result_struct.b = b;
    intermed_result_struct.X_ins = X_ins;
    intermed_result_struct.ratios = ratios;
    intermed_result_struct.LCOE = LCOE;
    intermed_result_struct.cost = cost;
    intermed_result_struct.power = power;
    intermed_result_struct.failed = failed;
    intermed_result_struct.pareto_results_struct = pareto_results_struct;
end
