%[AUTOGENERATED]
%[AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
            
            b = intermed_result_struct.b;
            X_ins = intermed_result_struct.X_ins;
            ratios = intermed_result_struct.ratios;
            LCOE = intermed_result_struct.LCOE;
            cost = intermed_result_struct.cost;
            power = intermed_result_struct.power;
            failed = intermed_result_struct.failed;
            pareto_results_struct = intermed_result_struct.pareto_results_struct;

            [fig_array,results_tab] = experiments_plot(b,X_ins,ratios,LCOE,...
                                                        cost,power,failed,...
                                                        pareto_results_struct);
            
            tab_array_display = {results_tab};
            tab_array_latex = {results_tab};
            
            tab_firstrows = {[]};
            tab_colspecs = {[]};
            
            end_result_struct.design_space_exploration_complete = true;
end
