%[AUTOGENERATED]
function intermed_result_struct = analysis_fcn(~,~)
% Function analysis_fcn
%
% :param ~: ~
% :param ~: ~
% :returns: Intermediate results struct (cached heavy analyses)
    % Run MEEM validation analysis
    [figPotMatch, figVelMatch, figSparsity, figHydroCoeff] = validate_MEEM();
    b_vector_fig = b_inf_numeric();
    
    % Store results for post-processing
    intermed_result_struct.figPotMatch = figPotMatch;
    intermed_result_struct.figVelMatch = figVelMatch;
    intermed_result_struct.figSparsity = figSparsity;
    intermed_result_struct.figHydroCoeff = figHydroCoeff;
    intermed_result_struct.b_vector_fig = b_vector_fig;
end
