classdef Meem < GenericAnalysis
    %MEEM Analysis class for MEEM validation figures
    %   Generates MEEM regions, sparsity, validation, matching, and convergence figures

    properties
        fig_names = {'meem_sparsity',...
                     'meem_validation',...
                     'meem_matching',...
                     'meem_convergence_vs_omega',...
                     'meem_convergence_vs_NMK',...
                     'asymptotic_b_vector'};
        tab_names = {};
    end

    methods
        function obj = Meem(varargin)
            obj = obj@GenericAnalysis(varargin{:});
            obj.extra_analysis_outputs = { ...
                'results/Meem/intermed_b_vector_fig_1.fig', ...
                'results/Meem/intermed_figHydroCoeff_1.fig', ...
                'results/Meem/intermed_figSparsity_1.fig', ...
                'results/Meem/intermed_figVelMatch_1.fig', ...
                'results/Meem/intermed_figPotMatch_1.fig', ...
                'results/Meem/intermed_fig_convergence_vs_omega_1.fig', ...
                'results/Meem/intermed_fig_convergence_vs_NMK_1.fig' ...
            };
        end
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
