%[DOCS AUTOGENERATED]
function intermed_result_struct = analysis_fcn(~,~)
% Function analysis_fcn
%
% :param ~: ~
% :param ~: ~
% :returns: Intermediate results struct (cached heavy analyses)
    % Run damping plate structural analysis
    r_primve_vec = linspace(.05,4,40);
    r_vec = 1./r_primve_vec;
    theta_vec = 0:pi/48:2*pi;
    kappa_vec = 0:3;
    [R,TH,K] = meshgrid(r_vec,theta_vec,kappa_vec);
    
    [B, G_real, G_imag] = compute_drag_integral(R,TH,K);
    
    G = G_real + 1i * G_imag;
    G_mag = abs(G);
    G_phase = angle(G);
    
    intermed_result_struct.B       = B;
    intermed_result_struct.G_real  = G_real;
    intermed_result_struct.G_imag  = G_imag;
    intermed_result_struct.G_mag   = G_mag;
    intermed_result_struct.G_phase = G_phase;

    intermed_result_struct.R = R;
    intermed_result_struct.TH = TH;
    intermed_result_struct.kappa_vec = kappa_vec;
end
