classdef DragIntegral < GenericAnalysis
    %DRAGINTEGRAL Analysis class for damping plate structural figures
    %   Generates damping plate moment, deflection, and aspect ratio figures

    properties
        fig_names = {'drag_integral_B',...
                     'drag_integral_G_r',...
                     'drag_integral_G_i',...
                     'drag_integral_G_m',...
                     'drag_integral_G_p'};
        tab_names = {};
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
