flowchart LR
    N[ ] --> |Time-Domain <br />Constraints|M
    M[Linearization with Constraint DFs] --> |Frequency-Domain Constraints|C
    A[ ] --> |Time-Domain <br />Nonlinear Plant|B[Linearization <br />with Plant DFs]
    B -->|Frequency-Domain <br />Linear Plant| C[Numerical or Analytical<br />Linear Frequency-Domain Constrained Optimal Control]
    C -->|Frequency-Domain Linear Optimal Controller| E[Nonlinear Signal Reconstruction with <br />Inverse Control DF]
    E -->|Time-Domain Nonlinear Optimal Controller| F[" "]

    classDef hidden fill:transparent,stroke:transparent,color:transparent;
    class A,N,F hidden;