%[AUTOGENERATED]
function intermed_result_struct = analysis_fcn(~,b)
% Function analysis_fcn
%
% :param ~: ~
% :param b: Design variable bounds struct
% :returns: Intermediate results struct (cached heavy analyses)
    % Run parameter sweep analysis
    [ratios, LCOE, LCOE_nom, P_var, Pvar_nom, ...
     param_names, num_DVs, X_LCOE, X_LCOE_nom, ...
     dvar_names, X_Pvar, X_Pvar_nom,...
     slope_LCOE_norm, slope_Pvar_norm, ...
     slope_X_LCOE_norm, slope_X_Pvar_norm, ...
     param_table, par_J_par_p_local, ...
     dJ_star_dp_quad_local, dJ_star_dp_lin_local,...
     dJstar_dp_global, par_x_star_par_p_local, ...
     par_x_star_par_p_global, ...
     delta_p_change_activity_local, ...
     delta_p_change_activity_global,...
     runtime_post_optim, runtime_re_optim] = param_sweep(b.filename_uuid);
    
    % Store results for post-processing
    intermed_result_struct.ratios = ratios;
    intermed_result_struct.LCOE = LCOE;
    intermed_result_struct.LCOE_nom = LCOE_nom;
    intermed_result_struct.P_var = P_var;
    intermed_result_struct.Pvar_nom = Pvar_nom;
    intermed_result_struct.param_names = param_names;
    intermed_result_struct.num_DVs = num_DVs;
    intermed_result_struct.X_LCOE = X_LCOE;
    intermed_result_struct.X_LCOE_nom = X_LCOE_nom;
    intermed_result_struct.dvar_names = dvar_names;
    intermed_result_struct.X_Pvar = X_Pvar;
    intermed_result_struct.X_Pvar_nom = X_Pvar_nom;
    intermed_result_struct.slope_LCOE_norm = slope_LCOE_norm;
    intermed_result_struct.slope_Pvar_norm = slope_Pvar_norm;
    intermed_result_struct.slope_X_LCOE_norm = slope_X_LCOE_norm;
    intermed_result_struct.slope_X_Pvar_norm = slope_X_Pvar_norm;
    intermed_result_struct.param_table = param_table;

    intermed_result_struct.par_J_par_p_local = par_J_par_p_local;
    intermed_result_struct.dJ_star_dp_quad_local = dJ_star_dp_quad_local;
    intermed_result_struct.dJ_star_dp_lin_local = dJ_star_dp_lin_local;
    intermed_result_struct.dJstar_dp_global = dJstar_dp_global;
    intermed_result_struct.par_x_star_par_p_local = par_x_star_par_p_local;
    intermed_result_struct.par_x_star_par_p_global = par_x_star_par_p_global;
    intermed_result_struct.delta_p_change_activity_local = delta_p_change_activity_local;
    intermed_result_struct.delta_p_change_activity_global = delta_p_change_activity_global;

    intermed_result_struct.runtime_post_optim = runtime_post_optim;
    intermed_result_struct.runtime_re_optim = runtime_re_optim;
    intermed_result_struct.b = b;
end
