classdef ParamSensitivities < GenericAnalysis
    %PARAMSENSITIVITIES Analysis class for parameter sensitivity figures
    %   Generates parameter sensitivity analysis figures including tornado plots and grids

    properties
        fig_names = {'re_optim_constraint_grid', ...
                    'post_optim_constraint_grid', ...
                    're_optim_design_grid', ...
                    'post_optim_design_grid', ...
                    're_optim_objective_grid', ...
                    'post_optim_re_optim_objective_grid', ...
                    ...
                    'nonlinear_objectives',...
                    'nonlinear_design_J1',...
                    'nonlinear_design_J2', ...
                    're_optim_objective_tornado', ...
                    ...
                    're_optim_design_tornado_x1',...
                    're_optim_design_tornado_x2',...
                    're_optim_design_tornado_x3',...
                    're_optim_design_tornado_x4',...
                    're_optim_design_tornado_x5',...
                    're_optim_design_tornado_x6',...
                    're_optim_design_tornado_x7',...
                    're_optim_design_tornado_x8',...
                    're_optim_design_tornado_x9',...
                    're_optim_design_tornado_x10',...
                    're_optim_design_tornado_x11',...
                    're_optim_design_tornado_x12',...
                    ...
                    're_optim_design_tornado_J1', ...
                    're_optim_design_tornado_J2', ...
                    };

        tab_names = {};
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
