%[DOCS AUTOGENERATED]
function [F_heave_storm, F_surge_storm, ...
    F_heave_op, F_surge_op, F_ptrain_max, ...
    P_var, P_avg_elec, P_matrix_elec, ...
    X_constraints, B_p, K_p, mag_U, ...
    X_u, X_f, X_s, ...
    P_matrix_mech,P_sat_ratio,...
    A_f_over_rho, A_s_over_rho, A_c_over_rho,...
    B_f_over_rho_w, B_s_over_rho_w,B_c_over_rho_w,...
    gamma_f_over_rho_g, gamma_s_over_rho_g,...
    gamma_phase_f,gamma_phase_s,w,phase_X_f,phase_X_u,...
    F_drag_f,F_drag_s,phase_F_drag_f,phase_F_drag_s] = dynamics(in,m_float,m_spar)
% Function dynamics
%
% :param in: in
% :param m_float: m_float
% :param m_spar: m_spar
% :returns: F_heave_storm
% :returns: F_surge_storm
% :returns: F_heave_op
% :returns: F_surge_op
% :returns: F_ptrain_max
% :returns: P_var
% :returns: P_avg_elec
% :returns: Electrical power matrix
% :returns: X_constraints
% :returns: B_p
% :returns: K_p
% :returns: mag_U
% :returns: X_u
% :returns: X_f
% :returns: X_s
% :returns: P_matrix_mech
% :returns: P_sat_ratio
% :returns: A f / $\\rho$
% :returns: A s / $\\rho$
% :returns: A c / $\\rho$
% :returns: B f / $\\rho$ w
% :returns: B s / $\\rho$ w
% :returns: B c / $\\rho$ w
% :returns: $\\gamma$ f / $\\rho$ g
% :returns: $\\gamma$ s / $\\rho$ g
% :returns: $\\gamma$ phase f
% :returns: $\\gamma$ phase s
% :returns: Angular wave frequency (rad/s)
% :returns: phase_X_f
% :returns: phase_X_u

    % use probabilistic sea states for power and PTO force and max amplitude
    [T,Hs] = meshgrid(in.T,in.Hs);
    zero_prob_idxs = in.JPD==0;
    T(zero_prob_idxs) = NaN;
    Hs(zero_prob_idxs) = NaN;

    if in.use_force_sat
        F_limit = in.F_max;
    else
        F_limit = Inf;
    end

    T_f_slam_op    = min(in.T_f_1, in.h_f - in.T_f_2);
    T_f_slam_storm = min(in.T_f_2, in.h_f - in.T_f_2);

    [P_matrix_mech,X_constraints_op,B_p,...
    K_p,mag_U,X_u,X_f,X_s,F_heave_op,...
    F_surge_op,F_ptrain_max,P_sat_ratio,...
    A_f_over_rho,A_s_over_rho, A_c_over_rho,...
    B_f_over_rho_w, B_s_over_rho_w, B_c_over_rho_w, ...
    gamma_f_over_rho_g, gamma_s_over_rho_g, ...
    gamma_phase_f, gamma_phase_s,w,...
    phase_X_f,phase_X_u,F_drag_f,F_drag_s,...
    phase_F_drag_f,phase_F_drag_s] = get_power_force(in,T,Hs,m_float,m_spar,...
                                            F_limit, zero_prob_idxs, ...
                                            T_f_slam_op, in.power_scale_coeffs,...
                                            in.operational_dynamics_debug_plots_on);
    
    % account for powertrain electrical losses
    P_matrix_elec = P_matrix_mech * in.eff_pto;
    
    % saturate maximum power
    if in.use_power_sat
        P_matrix_elec = min(P_matrix_elec,in.P_max,'includenan');
    end
    
    % weight power across all sea states
    P_weighted = P_matrix_elec .* in.JPD / 100;
    P_avg_elec = sum(P_weighted(:),'omitnan'); 
    
    assert(isreal(P_avg_elec))
    
    % use max sea states for structural forces
    in.use_multibody = false; % storm is alway singlebody dynamics because brake clamps float to spar
    [~,X_constraints_storm,...
     ~,~,~,~,~,~,F_heave_storm,...
     F_surge_storm]             = get_power_force(in, in.T_struct, in.Hs_struct, ...
                                                  m_float, m_spar, 0, ...
                                                  false(size(in.T_struct)), ...
                                                  T_f_slam_storm, [1 0 0 1], false);
    F_heave_storm = F_heave_storm * in.F_heave_mult;
    
    % use all X constraints operationally, only use slamming in storm
    X_constraints_storm = X_constraints_storm(8:end);
    X_constraints_storm = 1 + 0*X_constraints_storm; % fixme this overrides the constraint
    X_constraints = [X_constraints_op X_constraints_storm];

    % coefficient of variance (normalized standard deviation) of power
    P_var = std(P_matrix_elec(:), in.JPD(:),'omitnan') / P_avg_elec;
    P_var = P_var * 100; % convert to percentage
    

end

function [P_matrix, X_constraints, B_p, K_p, mag_U, mag_X_u, mag_X_f, mag_X_s,...
          F_heave_f_max, F_surge, F_ptrain_max, P_sat_ratio,...
          A_f_over_rho, A_s_over_rho, A_c_over_rho, ...
        B_f_over_rho_w, B_s_over_rho_w, B_c_over_rho_w, ...
        gamma_f_over_rho_g, gamma_s_over_rho_g, ...
        gamma_f_phase, gamma_s_phase,w,phase_X_f,phase_X_u,...
        F_drag_f, F_drag_s, phase_F_drag_f, phase_F_drag_s] = get_power_force(in,T,Hs, m_float, m_spar, ...
                                                            F_max, idx_constraint, T_f_slam, power_scale_coeffs,...
                                                            dynamics_debug_plots_on)

    if dynamics_debug_plots_on
        drag_convergence_plot_on = true;
        plot_slamming = true;
    else
        drag_convergence_plot_on = false;
        plot_slamming = false;
    end

    % get dynamic coefficients for float and spar
    % fixme: eventually should use in.D_f_in to allow a radial gap between float and spar
    [m_f,B_h_f,K_h_f,gamma_f_mag,gamma_f_phase,...
     m_s,B_h_s,K_h_s,gamma_s_mag,gamma_s_phase,...
     m_c,B_c,drag_const_f,drag_const_s,...
     mag_v0_f,mag_v0_s,H,w,k_wvn,A_f_over_rho, ...
     A_s_over_rho, A_c_over_rho, B_f_over_rho_w, ...
     B_s_over_rho_w, B_c_over_rho_w, ...
     gamma_f_over_rho_g, gamma_s_over_rho_g] = get_dynamic_coeffs(Hs,T, ...
                                            in.D_f, in.T_f_2, in.D_s, in.D_d, in.T_s, in.h, ...
                                            m_float, m_spar, in.spar_excitation_coeffs,...
                                            in.C_d_float, in.C_d_spar, ...
                                            in.rho_w, in.g, ...
                                            in.use_MEEM, in.harmonics, in.hydro);

    X_u_max = 1e6;%min(Hs / (2*sqrt(2)), in.T_f);

    % get response: includes drag and force saturation
    [mag_U,phase_U,...
     real_P,reactive_P,...
     mag_X_u,phase_X_u,...
     mag_X_f,phase_X_f,...
     mag_X_s,phase_X_s,...
     B_p,K_p,P_sat_ratio,...
     F_drag_f,F_drag_s,...
     phase_F_drag_f,phase_F_drag_s] = get_response_drag(H,w,k_wvn,m_f,m_s,m_c,B_h_f,B_h_s,B_c,K_h_f,K_h_s,...
                                            gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,F_max,...
                                            drag_const_f,drag_const_s,mag_v0_f,mag_v0_s, ...
                                            X_u_max,in.control_type,in.use_multibody,...
                                            in.X_tol,in.phase_X_tol,in.F_lim_tol,in.X_lim_tol,...
                                            in.max_drag_iters_fxp,in.max_drag_iters_slv,...
                                            drag_convergence_plot_on,in.drag_fcn,...
                                            in.D_f, in.D_f_in, in.D_d);

% FIXME: check stability of closed loop multibody system
    
    % apply empirical fitted freq-dependent scale factor to adjust power from 
    % singlebody to multibody, to match RM3 report
    if in.use_multibody==false
        c = power_scale_coeffs;
        power_scale_factor = c(1) ./ ( c(2) * T.^2 + c(3) * T + c(4) );
        P_matrix = real_P .* power_scale_factor;
    else
        P_matrix = real_P * in.power_scale_multibody;
    end
    
    % set values where JPD=0 or response=Inf (unstable) to 0 to not include them in constraint
    idx_constraint = idx_constraint | isinf(mag_X_f);
    mag_X_u_const = mag_X_u;
    mag_X_u_const(idx_constraint) = 0;
    mag_X_f_const = mag_X_f;
    mag_X_f_const(idx_constraint) = 0;
    mag_X_s_const = mag_X_s;
    mag_X_s_const(idx_constraint) = 0;

    % amplitude constraints
    [X_constraints,wave_amp] = amplitude_constraints(mag_X_u_const, mag_X_f_const, mag_X_s_const,...
                                                phase_X_f, phase_X_s, in, Hs, T,...
                                                k_wvn, T_f_slam, plot_slamming);

    % calculate forces
    if nargout > 3
        % set values where JPD=0 to 0 to not include them in constraint
        mag_U_const = mag_U;
        mag_U_const(idx_constraint) = 0;
            
        % powertrain force
        F_ptrain_max = max(mag_U_const,[],'all');
        F_ptrain_max = min(F_ptrain_max, F_max);

        % heave force: includes powertrain force and D'Alembert force        
        F_heave_f = combine_ptrain_dalembert_forces(m_float, w, mag_X_f_const, phase_X_f, mag_U_const, phase_U, F_max);
        F_heave_s = combine_ptrain_dalembert_forces(m_spar,  w, mag_X_s_const, phase_X_s, mag_U_const, phase_U, F_max);

        F_heave_f_max = max(F_heave_f,[],'all');
        F_heave_s_max = max(F_heave_s,[],'all');

        % surge force - from Eq 25 Newman 1963 - assumes slender kR << 1
        % https://apps.dtic.mil/sti/tr/pdf/AD0406333.pdf  
        F_surge_coeff = 2 * in.rho_w * w.^2 .* wave_amp ./ k_wvn;
        F_surge_f = F_surge_coeff * pi * in.D_f^2/4 .* (       1             - exp(-k_wvn*in.T_f_2));
        F_surge_s = F_surge_coeff * pi * in.D_s^2/4 .* (exp(-k_wvn*in.T_f_2) - exp(-k_wvn*in.T_s));

        F_surge_f_max = max(F_surge_f(~idx_constraint),[],'all');
        F_surge_s_max = max(F_surge_s(~idx_constraint),[],'all');

        F_surge = [F_surge_f_max F_surge_s_max 0];

    end
end

function [X_constraints,wave_amp] = amplitude_constraints(mag_X_u_const, mag_X_f_const, ...
                                                mag_X_s_const,phase_X_f, ...
                                                phase_X_s, in, Hs, T,...
                                                k_wvn, T_f_slam, plot_slamming)

    X_u_max = max(mag_X_u_const,[],'all');
    X_f_max = max(mag_X_f_const,[],'all');
    X_s_max = max(mag_X_s_const,[],'all');

    % extra height on spar after accommodating relative displacement
    h_s_extra_up = (in.h_s - in.T_s - (in.h_f - in.T_f_2) - X_u_max) / in.h_s;
    h_s_extra_down = (in.T_s - in.T_f_2 - in.h_d - X_u_max) / in.h_s;

    % sufficient length of float support tube
    h_fs_extra = in.h_fs_clear / X_u_max - 1;

    % prevent violation of linear wave theory - notebook p153 9/20/25
    X_max_linear_f = 1/10 * (in.h - in.T_f_2);
    X_max_linear_s = 1/10 * (in.h - in.T_s);
    
    X_below_linear_f = 1 - X_f_max / X_max_linear_f;
    X_below_linear_s = 1 - X_s_max / X_max_linear_s;

    % prevent bottom rising out of the water and top going into water (slamming/submersion)
    wave_amp = Hs/(2*sqrt(2));
    [X_below_wave_f,D_f_margin] = slamming(wave_amp, k_wvn, in.D_f, phase_X_f, mag_X_f_const, T_f_slam, plot_slamming, T, Hs);
    [X_below_wave_s,D_s_margin] = slamming(wave_amp, k_wvn, in.D_d, phase_X_s, mag_X_s_const, in.T_s,   plot_slamming, T, Hs);

    X_below_wave = min(X_below_wave_f,X_below_wave_s); % constraint aggregation
    X_below_wave(~isfinite(X_below_wave)) = 1; % constraint always satisfied when JPD=0

    % all amplitude constraints together
    X_constraints = [h_s_extra_up, h_s_extra_down, h_fs_extra, ...
        X_below_linear_f, X_below_linear_s, D_f_margin, D_s_margin, X_below_wave(:).'];
end

function [X_below_wave,diameter_margin] = slamming(A, k, D, phase_X, mag_X, delta_z, plot_slamming, T, Hs)
    idx_large_wave = A > delta_z;

    theta_small_wave = pi + max(0, -k * D / 2 + abs(pi - phase_X));
    theta_large_wave = phase_X + k * D / 2 .* sign(pi - phase_X);
    theta = theta_small_wave;
    theta(idx_large_wave) = theta_large_wave(idx_large_wave);

    sqrt_term = sqrt( delta_z^2 - (A .* sin(theta)).^2 );
    X_slam_max =  sqrt_term + A .* cos(theta);
    X_slam_min = -sqrt_term + A .* cos(theta);

    X_below_wave_max = X_slam_max ./ mag_X - 1;
    X_below_wave_min = 1 - X_slam_min ./ mag_X;
    X_below_wave = min(X_below_wave_max, X_below_wave_min);

    idx_imag = imag(sqrt_term)~=0; % case where slamming occurs even for stationary body
    X_below_wave( idx_imag ) = -abs(imag(X_below_wave(idx_imag))); % set the amount of infeasibility to be the amount of imaginary content
    X_slam_min( idx_imag ) = NaN;
    X_slam_max( idx_imag ) = NaN;

    if any(idx_large_wave(:))
        k_max_large_wave = max(k(idx_large_wave),[],'all');
        A_max_large_wave = max(A(idx_large_wave),[],'all');
        diameter_margin = asin(delta_z/A_max_large_wave) - k_max_large_wave * D/2;
    else
        diameter_margin = 1; % always ok if no large waves
    end

    if plot_slamming
        make_slamming_plot(T,Hs,phase_X,theta,X_slam_max,X_slam_min,mag_X);
    end
end

function F_heave = combine_ptrain_dalembert_forces(mass, w, mag_X, phase_X, mag_U, phase_U, F_max)
    F_dAlembert_mag = mass .* w.^2 .* mag_X;
    F_dAlembert_phase = phase_X;

    F_heave_real = F_dAlembert_mag .* cos(F_dAlembert_phase) + mag_U .* cos(phase_U);
    F_heave_imag = F_dAlembert_mag .* sin(F_dAlembert_phase) + mag_U .* sin(phase_U);

    F_heave_fund = sqrt(F_heave_real.^2 + F_heave_imag.^2);

    F_heave = min(F_heave_fund, F_max + F_dAlembert_mag);

end
