function [a_q,b_q,c_q] = get_abc_symbolic(f,m,b,k,w,r_b,r_k)
%GET_ABC_SYMBOLIC
%    [A_Q,B_Q,C_Q] = GET_ABC_SYMBOLIC(F,M,B,K,W,R_B,R_K)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    09-Jan-2023 02:00:40

t2 = b.^2;
t3 = f.^2;
t4 = k.^2;
t5 = m.^2;
t6 = r_b.^2;
t7 = r_k.^2;
t8 = w.^2;
t9 = t8.^2;
t10 = t4.*t6;
t13 = t2.*t7.*t8;
a_q = -t3.*(t10+t13)+t6.*t7.*(t4+t2.*t8+t5.*t9-k.*m.*t8.*2.0);
if nargout > 1
    t14 = k.*m.*r_k.*t6.*t8.*2.0;
    t11 = r_k.*t10.*2.0;
    t15 = r_b.*t13.*2.0;
    t12 = -t11;
    t16 = -t15;
    b_q = t3.*(t10.*2.0+t12+t13.*2.0+t14+t16);
end
if nargout > 2
    c_q = -t3.*(t10+t12+t13+t14+t16+t7.*t10+t6.*t13+t5.*t6.*t7.*t9-k.*m.*t6.*t7.*t8.*2.0);
end
