%[AUTOGENERATED]
%[AUTOGENERATED]
function [a_q,b_q,c_q] = get_abc_symbolic(f,m,b,k,w,r_b,r_k)
% Function get_abc_symbolic
%
% :param f: f
% :param m: m
% :param b: Design variable bounds struct
% :param k: Wavenumber (1/m)
% :param w: Angular wave frequency (rad/s)
% :param r_b: r_b
% :param r_k: r_k
% :returns: a_q
% :returns: b_q
% :returns: c_q
%GET_ABC_SYMBOLIC
%    [A_Q,B_Q,C_Q] = GET_ABC_SYMBOLIC(F,M,B,K,W,R_B,R_K)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    12-Jan-2023 02:31:32

t2 = b.^2;
t3 = k.^2;
t4 = m.^2;
t5 = r_b.^2;
t6 = r_k.^2;
t7 = w.^2;
t8 = t7.^2;
t9 = t3.*t5;
t12 = t2.*t6.*t7;
t13 = k.*m.*r_k.*t5.*t7.*2.0;
t10 = r_k.*t9.*2.0;
t11 = -t9;
t14 = r_b.*t12.*2.0;
t15 = -t12;
a_q = t11+t15+1.0./f.^2.*t5.*t6.*(t3+t2.*t7+t4.*t8-k.*m.*t7.*2.0);
if nargout > 1
    b_q = t9.*2.0-t10+t12.*2.0+t13-t14;
end
if nargout > 2
    c_q = t10+t11-t13+t14+t15+t6.*t11+t5.*t15-t4.*t5.*t6.*t8+k.*m.*t5.*t6.*t7.*2.0;
end
