function [mag_U,phase_U,...
         real_P,reactive_P,...
         mag_X_u,phase_X_u,...
         mag_X_f,phase_X_f,...
         mag_X_s,phase_X_s,...
         B_p,K_p,P_sat_ratio,...
         F_drag_f,F_drag_s,...
    phase_F_drag_f,phase_F_drag_s] = get_response_drag(H,w,k_wvn,m_f,m_s,m_c,B_h_f,B_h_s,B_c,K_h_f,K_h_s,...
                                        gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,F_max,...
                                        drag_const_f,drag_const_s,mag_v0_f,mag_v0_s,...
                                        X_max,control_type,multibody,merge_bodies,...
                                        X_tol,phase_X_tol,F_lim_tol,X_lim_tol,...
                                        max_drag_iters_fixed_point,max_drag_iters_solver,...
                                        drag_convergence_plot_on,drag_fcn,D_f,D_f_in,D_d)

    % initial guess: 2m float amplitude, 0.5m spar amplitude, unsaturated
    X_f_guess = 2 * ones(size(w));
    phase_X_f_guess = zeros(size(w));
    X_s_guess = .5 * ones(size(w));
    phase_X_s_guess = zeros(size(w));
    if F_max == 0
        ctrl_mult_guess = zeros(size(w));
    else
        ctrl_mult_guess = ones(size(w));
    end
    phase_ctrl_mult_guess = zeros(size(w));

    % package inputs
    dynam_inputs = {H,w,k_wvn,m_f,m_s,m_c,B_h_f,B_h_s,B_c,K_h_f,K_h_s,...
                    gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,F_max,...
                    drag_const_f,drag_const_s,mag_v0_f,mag_v0_s,...
                    X_max,control_type,multibody,merge_bodies,...
                    X_tol,phase_X_tol,F_lim_tol,X_lim_tol,...
                    drag_convergence_plot_on,drag_fcn,D_f,D_f_in,D_d};

    % first do fixed point iteration
    if max_drag_iters_fixed_point > 0
        [mag_U,phase_U,...
         real_P,reactive_P,...
         mag_X_u,phase_X_u,...
         mag_X_f,phase_X_f,...
         mag_X_s,phase_X_s,...
         B_p,K_p,P_sat_ratio,...
         ctrl_mult,phase_ctrl_mult,...
         F_drag_f,F_drag_s,...
         phase_F_drag_f,phase_F_drag_s] = fixed_point_iteration(X_f_guess,X_s_guess,...
                                                    phase_X_f_guess,phase_X_s_guess,...
                                                    ctrl_mult_guess,phase_ctrl_mult_guess,...
                                                    dynam_inputs{:}, ...
                                                    max_drag_iters_fixed_point);

        idx_use = ((ctrl_mult >= 0 & ctrl_mult < 1e4) & isfinite(mag_X_f)) | isnan(B_h_f);

        % update guesses
        [X_f_guess(idx_use),phase_X_f_guess(idx_use),...
         X_s_guess(idx_use),phase_X_s_guess(idx_use),...
         ctrl_mult_guess(idx_use),phase_ctrl_mult_guess(idx_use)] = deal(mag_X_f(idx_use),phase_X_f(idx_use),...
                                                       mag_X_s(idx_use),phase_X_s(idx_use),...
                                                       ctrl_mult(idx_use),phase_ctrl_mult(idx_use));

    end
    % then do nonlinear solver to finish
    if max_drag_iters_solver > 0
        
        [mag_U,phase_U,...
         real_P,reactive_P,...
         mag_X_u,phase_X_u,...
         mag_X_f,phase_X_f,...
         mag_X_s,phase_X_s,...
         B_p,K_p,P_sat_ratio,...
         F_drag_f,F_drag_s,...
         phase_F_drag_f,phase_F_drag_s] = solver(X_f_guess,X_s_guess,...
                                        phase_X_f_guess,phase_X_s_guess,...
                                        ctrl_mult_guess,phase_ctrl_mult_guess,...
                                        dynam_inputs{:},max_drag_iters_solver);
    end

    % zero any negative power
    real_P(real_P<0) = 0;
end

function [mag_U,phase_U,...
     real_P,reactive_P,...
     mag_X_u,phase_X_u,...
     mag_X_f,phase_X_f,...
     mag_X_s,phase_X_s,...
     B_p,K_p,P_sat_ratio,...
     F_drag_f,F_drag_s,...
     phase_F_drag_f,...
     phase_F_drag_s] = solver(X_f_guess,X_s_guess,phase_X_f_guess,phase_X_s_guess,...
                                    ctrl_mult_guess,phase_ctrl_mult_guess,...
                                                H,w,k_wvn,m_f,m_s,m_c,B_h_f,B_h_s,B_c,K_h_f,K_h_s,...
                                                gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,...
                                                F_max,drag_const_f,drag_const_s,mag_v0_f,mag_v0_s,...
                                                X_max,control_type,multibody,merge_bodies,...
                                                X_tol,phase_X_tol,F_lim_tol,X_lim_tol,...
                                                drag_convergence_plot_on,...
                                                drag_fcn,D_f,D_f_in,D_d,max_drag_iters)

    % anonymous function to take collapsed row vector and turn into the nth sea state matrix
    sz = size(w);
    idx_not_nan = isfinite(B_h_f);
    [row,col] = find(idx_not_nan);
    if ~iscolumn(row) % ensure row and col are column vectors so accumarray works
        row = row.';
        col = col.';
    end
    N_ss_nz = nnz(idx_not_nan); % number of nonzero sea states (so not including NaNs)
    fill_nan_matrix = @(x) accumarray([row col], x, sz, [], NaN) ; 
    unflatten = @(x,n) fill_nan_matrix( x( (1:N_ss_nz) + (n-1)*N_ss_nz ) );

    % anonymous function to take 6 sea state matrices and turn into collapsed row vector
    flatten = @(X1,X2,X3,X4,X5,X6) [reshape(X1(idx_not_nan),[],1);...
                                    reshape(X2(idx_not_nan),[],1);...
                                    reshape(X3(idx_not_nan),[],1);...
                                    reshape(X4(idx_not_nan),[],1);...
                                    reshape(X5(idx_not_nan),[],1);...
                                    reshape(X6(idx_not_nan),[],1)    ];

    % prepare inputs for solver
    x0 = flatten(X_f_guess, X_s_guess, phase_X_f_guess, phase_X_s_guess,...
                ctrl_mult_guess, phase_ctrl_mult_guess);

    % fun_inner takes 1 input and returns the 6+ outputs of dynamics_error_wrapper
    fun_inner = @(x) dynamics_error_wrapper(unflatten(x,1),unflatten(x,2),...
                                    unflatten(x,3),unflatten(x,4),...
                                    unflatten(x,5),unflatten(x,6),...
                                    H,w,k_wvn,m_f,m_s,m_c,B_h_f,B_h_s,B_c,K_h_f,K_h_s,...
                                    gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,F_max,...
                                    drag_const_f,drag_const_s,mag_v0_f,mag_v0_s,...
                                    X_max,control_type,multibody,merge_bodies,...
                                    drag_fcn, D_f, D_f_in, D_d);
    
    sparsity = repmat(eye(N_ss_nz),6);
    opts = optimoptions('fsolve','JacobPattern',sparsity,...
                                 'MaxIterations',max_drag_iters,...
                                 'Algorithm','trust-region',...
                                 ...%'StepTolerance',min([X_tol,phase_X_tol,F_lim_tol,X_lim_tol]),...
                                 'Display','off');
    if drag_convergence_plot_on
        opts.PlotFcn = {'optimplotx','optimplotfval'};
    end

    % solve
    [x_solved,err,flag,out] = fsolve(@(x)fun_outer(x,fun_inner,flatten),x0,opts);

    % unpack
    [X_f_solved,X_s_solved,...
     phase_X_f_solved,phase_X_s_solved,...
     ctrl_mult_solved,phase_ctrl_mult_solved] = deal(unflatten(x_solved,1),...
                                                     unflatten(x_solved,2),...
                                                     unflatten(x_solved,3),...
                                                     unflatten(x_solved,4),...
                                                     unflatten(x_solved,5),...
                                                     unflatten(x_solved,6));

    [mag_U,phase_U,...
     real_P,reactive_P,...
     mag_X_u,phase_X_u,...
     mag_X_f,phase_X_f,...
     mag_X_s,phase_X_s,...
     B_p,K_p,P_sat_ratio,...
     ~,~,...
     F_drag_f,F_drag_s,...
     phase_F_drag_f,...
     phase_F_drag_s] = dynamics_from_guess(X_f_solved, phase_X_f_solved, mag_v0_f, drag_const_f, ...
                                    X_s_solved, phase_X_s_solved, mag_v0_s, drag_const_s, ...
                                    B_c,B_h_f,B_h_s,K_h_f,K_h_s,m_c,m_f,m_s,H,w,k_wvn,...
                                    gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,...
                                    control_type,multibody,merge_bodies,F_max,X_max,...
                                    ctrl_mult_solved,phase_ctrl_mult_solved,...
                                    drag_fcn, D_f, D_f_in, D_d);

end
function out_flat = fun_outer(x,fun_inner,flatten)
    [Y1,Y2,Y3,Y4,Y5,Y6] = fun_inner(x);
    out_flat = flatten(Y1,Y2,Y3,Y4,Y5,Y6);
end

function [mag_U,phase_U,...
     real_P,reactive_P,...
     mag_X_u,phase_X_u,...
     mag_X_f,phase_X_f,...
     mag_X_s,phase_X_s,...
     B_p,K_p,P_sat_ratio,...
     ctrl_mult_guess,...
     phase_ctrl_mult_guess,...
     F_drag_f,F_drag_s,...
     phase_F_drag_f,...
     phase_F_drag_s] = fixed_point_iteration(X_f_guess,X_s_guess,phase_X_f_guess,phase_X_s_guess,...
                                                ctrl_mult_guess,phase_ctrl_mult_guess,...
                                                H,w,k_wvn,m_f,m_s,m_c,B_h_f,B_h_s,B_c,K_h_f,K_h_s,...
                                                gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,...
                                                F_max,drag_const_f,drag_const_s,mag_v0_f,mag_v0_s,...
                                                X_max,control_type,multibody,merge_bodies,...
                                                X_tol,phase_X_tol,F_lim_tol,X_lim_tol,...
                                                drag_convergence_plot_on,drag_fcn,...
                                                D_f, D_f_in, D_d, max_drag_iters)

    converged = false;
    iters = 0;

    % loop until converged
    while ~converged
        if drag_convergence_plot_on
            % record guesses
            % 5,11 was found manually to be a problem sea state
            sea_state_plot = {5,11};
            X_f_guesses(iters+1) = X_f_guess(sea_state_plot{:});
            X_s_guesses(iters+1) = X_s_guess(sea_state_plot{:});
            phase_X_f_guesses(iters+1) = phase_X_f_guess(sea_state_plot{:});
            phase_X_s_guesses(iters+1) = phase_X_s_guess(sea_state_plot{:});
        end

        [X_f_err,X_s_err,...
         phase_X_f_err,phase_X_s_err,...
         force_lim_err,amp_lim_err,...
         mag_U,phase_U,...
         real_P,reactive_P,...
         mag_X_u,phase_X_u,...
         mag_X_f,phase_X_f,...
         mag_X_s,phase_X_s,...
         B_p,K_p,P_sat_ratio,...
         F_drag_f,F_drag_s,...
         phase_F_drag_f,phase_F_drag_s] = dynamics_error_wrapper(X_f_guess,X_s_guess,...
                                                       phase_X_f_guess,phase_X_s_guess,...
                                                       ctrl_mult_guess,phase_ctrl_mult_guess,...
                                                H,w,k_wvn,m_f,m_s,m_c,B_h_f,B_h_s,B_c,K_h_f,K_h_s,...
                                                gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,F_max,...
                                                drag_const_f,drag_const_s,mag_v0_f,mag_v0_s,...
                                                X_max,control_type,multibody,merge_bodies,...
                                                drag_fcn, D_f, D_f_in, D_d);

        X_err       = max( abs([X_f_err,X_s_err]),             [], 'all');
        phase_X_err = max( abs([phase_X_f_err,phase_X_s_err]), [], 'all');
        F_lim_err   = max( abs(force_lim_err),                 [], 'all');
        X_lim_err   = max( abs(amp_lim_err),                   [], 'all');

        % new guesses
        X_f_guess = mag_X_f;
        X_s_guess = mag_X_s;
        phase_X_f_guess = phase_X_f;
        phase_X_s_guess = phase_X_s;
        ctrl_mult_guess = ctrl_mult_guess ./ (force_lim_err+1);
        phase_ctrl_mult_guess = eps + zeros(size(ctrl_mult_guess)); % fixme: If reactive control, phase should be nonzero, based on eq4 of IFAC paper.

        % check convergence
        X_converged = X_err < X_tol;
        phase_X_converged = phase_X_err < phase_X_tol;

        F_lim_converged = F_lim_err < F_lim_tol;
        X_lim_converged = X_lim_err < X_lim_tol;
        converged = X_converged && phase_X_converged && ...
                    F_lim_converged && X_lim_converged;

        if all(isnan(X_f_guess))
            error('all nan')
        end

        % increment iterations and check max iters
        iters = iters + 1;
        if iters > max_drag_iters
            break
        end
    end

    if drag_convergence_plot_on % fixme: have guesses as output of dynamics and save it to vals and plot outside of the sim
        plot_drag_convergence(X_f_guesses, X_s_guesses, phase_X_f_guesses, phase_X_s_guesses, ...
                              iters, multibody, X_tol, phase_X_tol);
    end

end

function [X_f_err,X_s_err,...
          phase_X_f_err,phase_X_s_err,...
          force_lim_err,amp_lim_err,...
          mag_U,phase_U,...
          real_P,reactive_P,...
          mag_X_u,phase_X_u,...
          mag_X_f,phase_X_f,...
          mag_X_s,phase_X_s,...
          B_p,K_p,P_sat_ratio,...
          F_drag_f,F_drag_s,...
     phase_F_drag_f,phase_F_drag_s] = dynamics_error_wrapper(X_f_guess,X_s_guess,...
                                                        phase_X_f_guess,phase_X_s_guess,...
                                                        ctrl_mult_guess,phase_ctrl_mult_guess,...
                                                H,w,k_wvn,m_f,m_s,m_c,B_h_f,B_h_s,B_c,K_h_f,K_h_s,...
                                                gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,...
                                                F_max,drag_const_f,drag_const_s,mag_v0_f,mag_v0_s,...
                                                X_max,control_type,multibody,merge_bodies,drag_fcn,D_f,D_f_in,D_d)
    [mag_U,phase_U,...
     real_P,reactive_P,...
     mag_X_u,phase_X_u,...
     mag_X_f,phase_X_f,...
     mag_X_s,phase_X_s,...
     B_p,K_p,P_sat_ratio,...
     force_lim_err,amp_lim_err,...
     F_drag_f,F_drag_s,...
     phase_F_drag_f,phase_F_drag_s] = dynamics_from_guess(X_f_guess, phase_X_f_guess, mag_v0_f, drag_const_f, ...
                                    X_s_guess, phase_X_s_guess, mag_v0_s, drag_const_s, ...
                                    B_c,B_h_f,B_h_s,K_h_f,K_h_s,m_c,m_f,m_s,H,w,k_wvn,...
                                    gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,...
                                    control_type,multibody,merge_bodies,F_max,X_max,...
                                    ctrl_mult_guess,phase_ctrl_mult_guess,...
                                    drag_fcn, D_f, D_f_in, D_d); % closed loop dynamics
    % error
    X_f_err = X_f_guess - mag_X_f;
    X_s_err = X_s_guess - mag_X_s;
    phase_X_f_err = wrapToPi(phase_X_f_guess - phase_X_f); % wrapping error -pi to pi maintains continuity at zero,
    phase_X_s_err = wrapToPi(phase_X_s_guess - phase_X_s); % allowing for the solution to oscillate between +pi and -pi

    % Fixme: when response = Inf (closed loop unstable), this should be considered 
    % controller error when it's the controller's fault (system stabilizable)
    % and only zeroed when it's inevitable (system not stabilizable). 
    % For now, we zero these Infs in both cases.
    % Also handle finite precision errors that return nan.
    idx_unstable_or_fp_error = mag_X_f==Inf | (isnan(mag_X_f) & ~isnan(X_f_guess));
    X_f_err(idx_unstable_or_fp_error) = 0;
    X_s_err(idx_unstable_or_fp_error) = 0;
    phase_X_f_err(idx_unstable_or_fp_error) = 0;
    phase_X_s_err(idx_unstable_or_fp_error) = 0;
    force_lim_err(idx_unstable_or_fp_error) = 0;
    amp_lim_err(idx_unstable_or_fp_error) = 0;
end

function [mag_U,phase_U,...
         real_P,reactive_P,...
         mag_X_u,phase_X_u,...
         mag_X_f,phase_X_f,...
         mag_X_s,phase_X_s,...
         B_p_sat,K_p_sat,...
         P_sat_ratio,...
         force_lim_err,...
         amp_lim_err,...
     mag_F_drag_f,mag_F_drag_s,...
     phase_F_drag_f,phase_F_drag_s] = dynamics_from_guess(X_f_guess, phase_X_f_guess, mag_v0_f, drag_const_f, ...
                                        X_s_guess, phase_X_s_guess, mag_v0_s, drag_const_s, ...
                                        B_c,B_h_f,B_h_s,K_h_f,K_h_s,m_c,m_f,m_s,H,w,k_wvn,...
                                        gamma_f_mag,gamma_f_phase,gamma_s_mag,gamma_s_phase,...
                                        control_type,multibody,merge_bodies,F_max,X_max,...
                                        ctrl_mult_guess,phase_ctrl_mult_guess,drag_fcn,...
                                        D_f, D_f_in, D_d)

    % linear system
    [control_evaluation_fcn,...
     real_G_u, imag_G_u, ...
     B_drag_f, B_drag_s, ...
     gamma_drag_f, gamma_drag_s] = linearize_around_guessed_response(X_f_guess, X_s_guess, ...
                                                                phase_X_f_guess, phase_X_s_guess, ...
                                                                mag_v0_f, mag_v0_s, H, w, k_wvn, ...
                                                                drag_const_f, drag_const_s,...
                                                                B_h_f, B_h_s, B_c, K_h_f, K_h_s, ...
                                                                m_c, m_f, m_s, gamma_f_mag, ...
                                                                gamma_f_phase, gamma_s_mag, ...
                                                                gamma_s_phase, multibody, merge_bodies,...
                                                                drag_fcn, D_f, D_f_in, D_d);



    if F_max==0
        [B_p,K_p] = deal(zeros(size(w)));
    else
        % unsaturated optimal control gains
        [B_p,K_p] = controller(real_G_u, imag_G_u, w, control_type);
    end
    % unsaturated response (stabilized)
    stabilize_B = true;
    stabilize_K = strcmpi(control_type,'reactive');
    [mag_U_unsat,~,P_unsat,...
     ~,~,~,mag_X_f_unsat,~,~,~,...
     B_p_stabilized,K_p_stabilized] = control_evaluation_fcn(K_p,B_p,stabilize_B,stabilize_K);
    Z_p = B_p_stabilized + K_p_stabilized ./ (1i * w);

    % saturated response and error
    [mag_U,phase_U,...
     real_P,reactive_P,...
     mag_X_u,phase_X_u,...
     mag_X_f,phase_X_f,...
     mag_X_s,phase_X_s,...
     B_p_sat,K_p_sat,...
     force_lim_err,...
     amp_lim_err] = response_and_ctrl_err_from_ctrl_guess(ctrl_mult_guess,...
                                                    phase_ctrl_mult_guess,...
                                                    F_max, mag_U_unsat,...
                                                    X_max, mag_X_f_unsat, Z_p, w,...
                                                    control_evaluation_fcn);
    P_sat_ratio = real_P ./ P_unsat;
    F_drag_f = -B_drag_f .* mag_X_f .* w .* exp(1i * (phase_X_f + pi/2)) + gamma_drag_f .* H/2;
    F_drag_s = -B_drag_s .* mag_X_s .* w .* exp(1i * (phase_X_s + pi/2)) + gamma_drag_s .* H/2;
    mag_F_drag_f = abs(F_drag_f);
    mag_F_drag_s = abs(F_drag_s);
    phase_F_drag_f = angle(F_drag_f);
    phase_F_drag_s = angle(F_drag_s);
end

function [mag_U,phase_U,real_P,reactive_P,...
        mag_X_u,phase_X_u,mag_X_f,phase_X_f,...
        mag_X_s,phase_X_s,B_p_sat,K_p_sat,...
        force_lim_err,amp_lim_err] = response_and_ctrl_err_from_ctrl_guess(...
                                                    ctrl_mult_guess,...
                                                    phase_ctrl_mult_guess,...
                                                    F_max, mag_U_unsat,...
                                                    X_max, mag_X_f_unsat, Z_p, w,...
                                                    control_evaluation_fcn)

    % saturated control gains from guess
    mult = ctrl_mult_guess .* exp(1i*phase_ctrl_mult_guess);
    Z_p_sat = Z_p .* mult;
    B_p_sat =       real(Z_p_sat);
    K_p_sat = -w .* imag(Z_p_sat);

    % saturated response (stabilized)
    stabilize_B = true;
    stabilize_K = true;
    [mag_U,phase_U,...
     real_P,reactive_P,...
     mag_X_u,phase_X_u,...
     mag_X_f,phase_X_f,...
     mag_X_s,phase_X_s] = control_evaluation_fcn(K_p_sat,B_p_sat,stabilize_B,stabilize_K);

    % control error: uses saturated and unsaturated response
    [force_lim_err,amp_lim_err] = control_errors_from_sat_results(F_max,mag_U_unsat,mag_U,...
                                                    X_max,mag_X_f_unsat,mag_X_f,B_p_sat);
end

function [control_evaluation_fcn,...
          real_G_u, imag_G_u,...
          B_drag_f, B_drag_s,...
          gamma_drag_f, gamma_drag_s] = linearize_around_guessed_response(X_f_guess, X_s_guess, ...
                                                                    phase_X_f_guess, phase_X_s_guess, ...
                                                                    mag_v0_f, mag_v0_s, H, w, k_wvn, ...
                                                                    drag_const_f, drag_const_s,...
                                                                    B_h_f, B_h_s, B_c, K_f, K_s, ...
                                                                    m_c, m_f, m_s, gamma_f_lin_mag, ...
                                                                    gamma_f_lin_phase, gamma_s_lin_mag, ...
                                                                    gamma_s_lin_phase, multibody, merge_bodies,...
                                                                    drag_fcn, D_f, D_f_in, D_d)
    % drag coefficients linearized around guess response
    [B_drag_f, gamma_drag_f] = get_drag_dynamic_coeffs(X_f_guess, phase_X_f_guess, mag_v0_f, w, drag_const_f, drag_fcn, k_wvn, H, D_f/2, D_f_in/2);
    [B_drag_s, gamma_drag_s] = get_drag_dynamic_coeffs(X_s_guess, phase_X_s_guess, mag_v0_s, w, drag_const_s, drag_fcn, k_wvn, H, D_d/2, 0);

    % total linear system coefficients
    B_f = B_h_f + B_drag_f;
    B_s = B_h_s + B_drag_s;
    
    gamma_f_lin = gamma_f_lin_mag .* exp(1i * gamma_f_lin_phase);
    gamma_s_lin = gamma_s_lin_mag .* exp(1i * gamma_s_lin_phase);

    gamma_f = gamma_f_lin + gamma_drag_f;
    gamma_s = gamma_s_lin + gamma_drag_s;

    F_f = gamma_f .* H / 2;               % excitation force of wave
    F_s = gamma_s .* H / 2;

    F_f_mag   = abs(F_f);
    F_s_mag   = abs(F_s);
    F_f_phase = angle(F_f);
    F_s_phase = angle(F_s);

    % thevenin admittance of the controlled DOF as seen from load
    if multibody
        [real_G_u,imag_G_u] = multibody_impedance(B_c,B_f,B_s,K_f,K_s,m_c,m_f,m_s,w);
        
%         X_f = m_f.*w - K_f./w;
%         X_s = m_s.*w - K_s./w;
%         X_c = m_c.*w;
% 
%         Z_f = B_f + 1i*X_f;
%         Z_s = B_s + 1i*X_s;
%         Z_c = B_c + 1i*X_c;
% 
%         det_Z = Z_f .* Z_s - Z_c.^2;
%         sum_Z = Z_f + Z_s + 2 * Z_c;
%         Z_th = det_Z ./ sum_Z;
%         G_u = 1./Z_th;
% 
%         mag_G_u_squared = abs(G_u).^2;
%         real_G_u = real(G_u);
%         imag_G_u = imag(G_u);
    else
        % derived on page 58 of notebook
        resistance = B_f;
        reactance = m_f.*w - K_f./w;
        mag_G_u_squared = 1 ./ (resistance.^2 + reactance.^2);
        real_G_u = resistance .* mag_G_u_squared;
        imag_G_u = -reactance .* mag_G_u_squared;
    end

    idx_not_stabilizable = real_G_u < 0; % controlled dof sees negative source 
                                         % impedance, so it's not only unstable
                                         % but also not stabilizable


    % function to evaluate any controller for fixed linear system
    control_evaluation_fcn = @(K_p,B_p,stabilize_B,stabilize_K) evaluate_any_controller(...
                                        B_c, B_f, B_s, K_f, K_s, ...
                                        m_c, m_f, m_s, w, K_p, B_p, ...
                                        F_f_mag, F_f_phase, F_s_mag, ...
                                        F_s_phase, multibody, merge_bodies,...
                                        idx_not_stabilizable, ...
                                        stabilize_B, stabilize_K);
end

function [B_p,K_p] = controller(real_G_u, imag_G_u, w, control_type)

    mag_G_u_squared = real_G_u.^2 + imag_G_u.^2;

    % control - set powertrain coefficients
    if strcmpi(control_type,'reactive')
        K_p = -w .* imag_G_u ./ mag_G_u_squared;
        B_p = real_G_u ./ mag_G_u_squared;
    elseif strcmpi(control_type, 'damping')
        B_p = 1 ./ sqrt(mag_G_u_squared);
        K_p = 1e-8; % can't be quite zero because r_k = Inf
    end

end

function [B_drag_2, gamma_drag] = get_drag_dynamic_coeffs(X_guess, phase_X_guess, mag_v0, w, drag_const, drag_fcn, k_wvn, H, R, R_in)

    idx_inf = isinf(X_guess); % override unstable guesses to prevent extra nans
    X_guess(idx_inf) = 1;
    phase_X_guess(idx_inf) = 0;

    idx_neg = X_guess < 0;
    X_guess(idx_neg) = 0.01;

    mag_v = w .* X_guess;
    phase_v = phase_X_guess + pi/2;
    mag_v0_v_ratio = mag_v0 ./ mag_v;
    mag_v0_v_ratio(mag_v==0) = 0; % prevent divide by zero
    
    % integral method: force should equal above method when k is small
    % (long waves, large T). We don't expect old Bd=new Bd because they are
    % defined differently (how much of K vs gamma goes into Bd).
    r = mag_v0_v_ratio;
    kappa = k_wvn * R;
    theta = phase_v;
    alpha = R_in / R;
    [B_int_1,G_int_real_1,G_int_imag_1] = drag_fcn(r,theta,kappa);
    [B_int_2,G_int_real_2,G_int_imag_2] = drag_fcn(r,theta,alpha*kappa);
    % derived p127 of notebook 9 2/25/26
    B_integral_weighted      = B_int_1      - alpha.^2 .* B_int_2;
    G_integral_real_weighted = G_int_real_1 - alpha.^2 .* G_int_real_2;
    G_integral_imag_weighted = G_int_imag_1 - alpha.^2 .* G_int_imag_2;
    G_integral_weighted = G_integral_real_weighted + 1i*G_integral_imag_weighted;

    % excitation only when mag_v = 0
    mag_v_or_v0 = mag_v;
    mag_v_or_v0(mag_v == 0) = mag_v0(mag_v == 0);

    % derived p141 of notebook 9 3/5/26
    mag_v_constant_term = drag_const / (pi*(1-alpha^2)) * 2 * mag_v_or_v0;
    B_drag_2   = mag_v_constant_term           .* B_integral_weighted;
    assert(all( B_drag_2(isfinite(B_drag_2)) >= 0 ),'negative damping from integral method')
    gamma_drag = mag_v_constant_term .* (mag_v0 ./ (H/2)) .* G_integral_weighted;

    plot_on = false;
    drag_debug = false; % set true to plot new integral drag vs old drag
    if drag_debug
        % uncomment the following to plot once solver has converged
        converged = any(strcmp({dbstack().name},'solver')   & [dbstack().line]==166);
        op_seas   = any(strcmp({dbstack().name},'dynamics') & [dbstack().line]==72);
        if converged && op_seas
            plot_on = true;
        end
    end
    if plot_on
        phase_v_prime = atan2( cos(phase_X_guess) - mag_v0_v_ratio, -sin(phase_X_guess)); % derived on p67 of notebook #6 (10/4/24)
    
        alpha_v = sqrt(1 + mag_v0_v_ratio.^2 - 2 * mag_v0_v_ratio .* cos(phase_X_guess)); % derived on p48 of notebook #5 (6/7/24)
        phi_alpha = phase_v_prime; % - phase_v;
        mag_cf = drag_const * alpha_v.^2 .* mag_v; % eq 52 in Water paper

        B_drag = -1*mag_cf .* cos(phi_alpha); % real part of c_f
    %     B_drag = max(B_drag,zeros(size(B_drag))); % prevent negative damping
        K_drag = - w .* mag_cf .* sin(phi_alpha); % -w times imag part of c_f

        plot_drag_integral_debug(B_drag, mag_v, phase_v, K_drag, X_guess,...
                                 phase_X_guess, B_drag_2, gamma_drag);
    end
end

function [mag_U,phase_U,...
     real_P,reactive_P,...
     mag_X_u,phase_X_u,...
     mag_X_f,phase_X_f,...
     mag_X_s,phase_X_s,...
     B_l,K_l] = evaluate_any_controller(...
                            B_c, B_f, B_s, K_f, K_s, ...
                            m_c, m_f, m_s, w, K_l, B_l, ...
                            F_f_mag, F_f_phase, F_s_mag, F_s_phase, ...
                            multibody, merge_bodies, idx_not_stabilizable,...
                            stabilize_B,stabilize_K)

    % check stability
    [idx_closed_loop_unstable,...
     recommended_increase_Bl,...
     recommended_increase_Kl] = check_cl_stability(B_c, B_f, B_s, K_f, K_s, ...
                                                    m_c, m_f, m_s, w, ...
                                                    K_l, B_l, ...
                                                    idx_not_stabilizable, ...
                                                    multibody, merge_bodies);
    % stabilize if specified
    B_l = B_l + stabilize_B * recommended_increase_Bl;
    K_l = K_l + stabilize_K * recommended_increase_Kl;
    
    % check that stabilizing worked
    if stabilize_K || stabilize_B
        [idx_closed_loop_unstable,...
             recommended_increase_Bl,...
             recommended_increase_Kl] = check_cl_stability(B_c, B_f, B_s, K_f, K_s, ...
                                                            m_c, m_f, m_s, w, ...
                                                            K_l, B_l, idx_not_stabilizable, ...
                                                            multibody, merge_bodies);

        need_more_stabilizing = stabilize_K * max(abs(recommended_increase_Kl),[],'all') ...
                              + stabilize_B * max(abs(recommended_increase_Bl),[],'all');


        if need_more_stabilizing~=0 % allow double stabilizing due to finite precision
            B_l = B_l + stabilize_B * recommended_increase_Bl;
            K_l = K_l + stabilize_K * recommended_increase_Kl;

            [idx_closed_loop_unstable,...
             recommended_increase_Bl,...
             recommended_increase_Kl] = check_cl_stability(B_c, B_f, B_s, K_f, K_s, ...
                                                            m_c, m_f, m_s, w, ...
                                                            K_l, B_l, idx_not_stabilizable, ...
                                                            multibody, merge_bodies);

            need_more_stabilizing = stabilize_K * max(abs(recommended_increase_Kl),[],'all') ...
                                  + stabilize_B * max(abs(recommended_increase_Bl),[],'all');
            if need_more_stabilizing~=0
                warning('Stabilizing did not work after 2 tries. This could be a finite precision issue.')
            end

        end

        idx_closed_loop_unstable(recommended_increase_Kl==0 & recommended_increase_Bl==0) = 0; % required for finite precision
    end

    % response
    if merge_bodies
        B_m = B_f + B_s + 2*B_c;
        m_m = m_f + m_s + 2*m_c;
        K_m = K_f + K_s;
        
        F_exc = F_f_mag .* exp(1i*F_f_phase) + F_s_mag .* exp(1i*F_s_phase);
        F_m_mag = abs(F_exc);
        F_m_phase = angle(F_exc);

        [mag_X_f,phase_X_f] = second_order_transfer_fcn(w, m_m, B_m, K_m, F_m_mag, F_m_phase);
        mag_X_s = mag_X_f;
        phase_X_s = phase_X_f;
        [mag_X_u,phase_X_u,real_P,reactive_P] = deal(0*phase_X_f);

        Z_f = B_f + 1i * (m_f.*w.^2 - K_f ./ w);
        Z_s = B_s + 1i * (m_s.*w.^2 - K_s ./ w);
        Z_c = B_c + 1i * (m_c.*w.^2);
        F_brake_f = 1i*w .* (Z_f + Z_c) .* mag_X_f .* exp(1i*phase_X_f) - F_f_mag .* exp(1i*F_f_phase);
        F_brake_s = 1i*w .* (Z_s + Z_c) .* mag_X_f .* exp(1i*phase_X_f) - F_s_mag .* exp(1i*F_s_phase);
        mag_U_f = abs(F_brake_f);
        phase_U_f = angle(F_brake_f);
        mag_U_s = abs(F_brake_s);
        phase_U_s = angle(F_brake_s);
        % fixme it should be mag_U = mag_U_s and phase_U = pi+phase_U_s,
        % take the max and use float phase for now
        mag_U = max(mag_U_f,mag_U_s);
        phase_U = phase_U_f;

    else
        if multibody
            [mag_U,phase_U,...
                real_P,reactive_P,...
                mag_X_u,phase_X_u,...
                mag_X_f,phase_X_f,...
                mag_X_s,phase_X_s] = multibody_response(B_c, B_f, B_s, K_f, K_s, ...
                                                        m_c, m_f, m_s, w, ...
                                                        K_l, B_l, ...
                                                        F_f_mag, F_f_phase, ...
                                                        F_s_mag, F_s_phase);
        else
            b_sat = B_f + B_l;
            k_sat = K_f + K_l;
    
            [mag_X_f,phase_X_f] = second_order_transfer_fcn(w, m_f, b_sat, k_sat, F_f_mag, F_f_phase);
            mag_X_u = mag_X_f;   phase_X_u = phase_X_f;
            mag_X_s = 0*mag_X_f; phase_X_s = 0*phase_X_f;
            F_ptrain_over_x = sqrt( (B_l .* w).^2 + (K_l).^2 );
            mag_U = F_ptrain_over_x .* mag_X_f;
            
            phase_Z_u = atan2(-K_l./w, B_l);    % phase of control impedance
            phase_V_u = pi/2 + phase_X_u;               % phase of control velocity
            phase_U = phase_V_u + phase_Z_u;            % phase of control force
    
            real_P = 1/2 * B_l .* w.^2 .* mag_X_u.^2; % this is correct even if X and U are out of phase
            check_P = 1/2 * w .* mag_X_u .* mag_U .* cos(phase_U - phase_V_u); % so is this, they match
            reactive_P = 0; % fixme this is incorrect but doesn't affect anything rn
        end
    end

    % set values to Inf when closed loop unstable
    mag_U(idx_closed_loop_unstable)      = Inf;
    phase_U(idx_closed_loop_unstable)    = Inf;
    real_P(idx_closed_loop_unstable)     = Inf;
    reactive_P(idx_closed_loop_unstable) = Inf;
    mag_X_u(idx_closed_loop_unstable)    = Inf;
    phase_X_u(idx_closed_loop_unstable)  = Inf;
    mag_X_f(idx_closed_loop_unstable)    = Inf;
    phase_X_f(idx_closed_loop_unstable)  = Inf;
    mag_X_s(idx_closed_loop_unstable)    = Inf;
    phase_X_s(idx_closed_loop_unstable)  = Inf;
end

function [idx_closed_loop_unstable,...
          recommended_increase_Bl,...
          recommended_increase_Kl] = check_cl_stability(B_c, B_f, B_s, K_f, K_s, ...
                            m_c, m_f, m_s, w, K_l_sat, B_l_sat, ...
                            idx_not_stabilizable, multibody, merge_bodies)
    % Check if the closed loop system is stable in all stabilizable sea states.
    % Must be checked individually for every sea state because eig doesn't 
    % accept arrays of more than 2 dimensions. This check must consider all
    % modes of the system (2 for multibody), not just the controlled mode.
    % Only checking closed loop means open loop unstable is allowed (intentionally).

    % The unstable sea states (idx_closed_loop_unstable) are then the union 
    % of unstable stabilizable sea states (idx_ctrl_makes_closed_loop_unstable)
    % and unstabilizable sea states (idx_not_stabilizable). The latter is 
    % from a previous check that Re(G_u)>0. idx_not_stabilizable = false 
    % means that even if the open loop system is unstable, there exists a 
    % controller that can stabilize it (ie, the unstable mode is controllable).

    recommended_increase_Bl = zeros(size(B_f));
    recommended_increase_Kl = zeros(size(B_f));

    Z_l = B_l_sat - 1i*K_l_sat./w;
    Z_p = Z_l; % fixme apply cascase here
    % uncomment and vectorize these once PTO dynamics are added
%     if multibody
%         cascade_VI_to_FXdot = eye(2);
%         T = [1, -1];
%     else
%         cascade_VI_to_FXdot = 1;
%         T = 1;
%     end
%     num = [1 0] * cascade_VI_to_FXdot * [Z_l(idx_H,idx_T); 1];
%     den = [0 1] * cascade_VI_to_FXdot * [Z_l(idx_H,idx_T); 1];
%     Z_pto = num ./ den;
%     Z_p = T.' * Z_pto * T; % transform PTO impedance onto body DOFs
    B_p =  real(Z_p);
    K_p = -imag(Z_p).*w;

    if merge_bodies
        ol_stable = (m_f + 2*m_c + m_s > 0) & (B_f + 2*B_c + B_s > 0) & (K_f + K_s > 0);
        cl_stable = ol_stable;
    else
        if multibody
            ol_stable = check_posdef_three_2x2s(m_f, m_c, m_c, m_s, ...
                                                B_f, B_c, B_c, B_s,...
                                                K_f, 0,   0,   K_s);
            cl_stable = check_posdef_three_2x2s(m_f,     m_c,     m_c,     m_s, ...
                                                B_f+B_p, B_c-B_p, B_c-B_p, B_s+B_p,...
                                                K_f+K_p,    -K_p,    -K_p, K_s+K_p);
        else 
            ol_stable = (m_f > 0) & (B_f     > 0) & (K_f     > 0);
            cl_stable = (m_f > 0) & (B_f+B_p > 0) & (K_f+K_p > 0);
        end
    end
    ol_unstable = ~ol_stable & ~isnan(w);
    if any(ol_unstable)
        % open loop matrices should all be stable, otherwise
        % indicates an error with the coefficients
        [idx_H,idx_T] = find(ol_unstable);
        if merge_bodies
            det_m_ol = m_f + 2*m_c + m_s;
            det_b_ol = B_f + 2*B_c + B_s;
            det_k_ol = K_f + K_s;
        else
            if multibody
                det_m_ol = m_f.*m_s - m_c.^2;
                det_b_ol = B_f.*B_s - B_c.^2;
                det_k_ol = K_f.*K_s;
            else
                det_m_ol = m_f;
                det_b_ol = B_f;
                det_k_ol = K_f;
            end
        end
        warning(['Open loop dynamics are unstable for idx_H=[%s], ' ...
               'idx_T=[%s]. det(M)=[%s], det(B)=[%s], det(K)=[%s].'], ...
            num2str(idx_H.'), ...
            num2str(idx_T.'), ...
            num2str(det_m_ol(ol_unstable).','%.2g '), ...
            num2str(det_b_ol(ol_unstable).','%.2g '), ...
            num2str(det_k_ol(ol_unstable).','%.2g '));
    end

    idx_ctrl_makes_closed_loop_unstable = ~cl_stable & ~isnan(w) & ~idx_not_stabilizable;

    if any(idx_ctrl_makes_closed_loop_unstable(:)) && ~merge_bodies
        % compute required change in control to create
        % stability - see notebook 9 p117 2/21/26
        if multibody
            det_B = (B_f+B_p).*(B_s+B_p) - (B_c-B_p).^2;
            sum_B = B_f + B_s + 2*B_c;
            denom_B = sum_B;

            det_K = (K_f+K_p).*(K_s+K_p) - (-K_p).^2;
            sum_K = K_f + K_s;
            denom_K = sum_K;
        else
            det_B = B_f + B_p;
            denom_B = 1;
            
            det_K = K_f + K_p;
            denom_K = 1;
        end

        rec_incr_Bp = abs(det_B) ./ denom_B * 1.01;
        %rec_incr_Bp(det_B==0) = eps;
        rec_incr_Bl = rec_incr_Bp; % fixme this should use cascade matrix

        rec_incr_Kp = abs(det_K) ./ denom_K * 1.01;
        %rec_incr_Kp(det_K==0) = eps;
        rec_incr_Kl = rec_incr_Kp; % fixme this should use cascade matrix

        idx_change_B = idx_ctrl_makes_closed_loop_unstable & det_B <= 0;
        idx_change_K = idx_ctrl_makes_closed_loop_unstable & det_K <= 0;
        recommended_increase_Bl(idx_change_B) = rec_incr_Bl(idx_change_B);
        recommended_increase_Kl(idx_change_K) = rec_incr_Kl(idx_change_K);
    end
                    
    idx_closed_loop_unstable = idx_not_stabilizable | idx_ctrl_makes_closed_loop_unstable;
end

function all_posdef = check_posdef_three_2x2s(a11,a12,a21,a22, b11,b12,b21,b22, c11,c12,c21,c22)
    all_posdef = ...
            a11 > 0 & (a11.*a22 - a21.*a12) >= 0 & ...
            b11 > 0 & (b11.*b22 - b21.*b12) >= 0 & ...
            c11 > 0 & (c11.*c22 - c21.*c12) >= 0;
end

function [F_err,X_err] = control_errors_from_sat_results(F_max,mag_U_unsat,mag_U,...
                                                    X_max,mag_X_f_unsat,mag_X_f,B_p_sat)
    % what the force and amp would be if the force-sat and amp-sat
    % solutions applied - notebook p106 2/2/25
    force_saturated_U = min(4/pi * F_max, mag_U_unsat);
    amp_saturated_X   = min(       X_max, mag_X_f_unsat);

    % indices where sat and unsat solutions violate which constraint
%         idx_force_viol_sat   = mag_U         > force_saturated_U;
%         idx_force_viol_unsat = mag_U_unsat   > force_saturated_U;
%         idx_amp_viol_sat     = mag_X_f       > amp_saturated_X;
%         idx_amp_viol_unsat   = mag_X_f_unsat > amp_saturated_X;

%         both_ok_unsat       = ~idx_force_viol_unsat & ~idx_amp_viol_unsat;
%         only_force_ok_unsat = ~idx_force_viol_unsat &  idx_amp_viol_unsat;
%         only_amp_ok_unsat   =  idx_force_viol_unsat & ~idx_amp_viol_unsat;

    % indices where each solution applies. currently overriding amp
    % constraint. commented forumlas attempt to incorporate both but
    % should not actually be based purely on whether the 
    % saturated and/or unsaturated solution violates, it should also
    % depend on alpha and the limits (see notebook p142-144 9/15/25).
    if isinf(F_max)
        idx_force_sat_applies = false(size(mag_X_f));
    else
        idx_force_sat_applies = true(size(mag_X_f));
    end
    idx_amp_sat_applies   = false(size(mag_X_f));
%         idx_force_sat_applies = both_ok_unsat | idx_force_viol_sat;   % | (idx_amp_viol_sat & idx_force_viol_sat);
%         idx_amp_sat_applies   = both_ok_unsat | only_force_ok_unsat; % | (idx_amp_viol_sat & idx_force_viol_sat);

    F_err_from_force_sat = mag_U   ./ force_saturated_U - 1;
    X_err_from_amp_sat   = mag_X_f ./ amp_saturated_X   - 1;

    F_err = Inf(size(F_err_from_force_sat));
    X_err = Inf(size(X_err_from_amp_sat));

    % at sea states where the force-saturated solution applies, 
    % set F_err as deviation from that solution. Otherwise, set F_err=0
    % to allow any force to occur.
    F_err(idx_force_sat_applies) = F_err_from_force_sat(idx_force_sat_applies);
    F_err(~idx_force_sat_applies) = 0;

    % at sea states where the amplitude-saturated solution applies, 
    % set X_err as deviation from that solution. Otherwise, set X_err = 0
    % to allow any amplitude to occur.
    X_err(idx_amp_sat_applies) = X_err_from_amp_sat(idx_amp_sat_applies);
    X_err(~idx_amp_sat_applies) = 0;

    % prevent 0/0=NaN when limit of zero is set
    if F_max==0
        F_err(mag_U==0) = 0;
        F_err(mag_U~=0) = mag_U(mag_U~=0) ./ mag_U_unsat(mag_U~=0);
    else
        % add penalty for B_p<0 (negative power)
        tol = 1;
        B_p_violation = max(-B_p_sat+tol,0);
        F_err = F_err + B_p_violation;
    end
    
end

function [X,angle_X] = second_order_transfer_fcn(w,m,b,k,F,F_phase)
    imag_term = b .* w;
    real_term = k - m .* w.^2;
    X_over_F_mag = ((real_term).^2 + (imag_term).^2).^(-1/2);
    X = X_over_F_mag .* F;
    if nargout > 1
        angle_F_over_X = atan2(imag_term,real_term);
        angle_X = F_phase - angle_F_over_X;
    end
end

function mult = get_multiplier(f_sat,m,b,k,w,r_b,r_k)
    % m, k, and r_k are scalars.
    % All other inputs are 2D arrays, the dimension of the sea state matrix.

    % speedup: only do math for saturated sea states, since unsat will = 1
    % likewise, don't do math for uncontrolled sea states (f_sat=0)
    idx_no_sat = f_sat == 1;
    idx_zero = f_sat == 0;
    idx_nan = idx_no_sat | idx_zero;
    f_sat(idx_nan) = NaN;
    b(idx_nan) = NaN;
    w(idx_nan) = NaN;
    r_b(idx_nan) = NaN;

    [a_quad, b_quad, c_quad]  = get_abc_symbolic(f_sat,m,b,k,w,r_b,r_k);

    % solve the quadratic formula
    determinant = sqrt(b_quad .^ 2 - 4 * a_quad .* c_quad);
    num = -b_quad + determinant;
    num(:,:,2) = -b_quad - determinant;
    den = 2 * a_quad;
    roots = num ./ den;

    % choose which of the two roots to use
    mult = pick_which_root(roots, idx_no_sat, idx_zero, a_quad, b_quad, c_quad);
    assert(all(~isnan(mult),'all'))
end
