%[DOCS AUTOGENERATED]
function [mag_U,real_P,mag_X_u,mag_X_f,mag_X_s,phase_X_f,phase_X_s,phase_U,imag_P,phase_X_u] = multibody_response(B_c,B_f,B_s,K_f,K_s,m_c,m_f,m_s,w,K_p,B_p,F_f_mag,F_f_phase,F_s_mag,F_s_phase,D_sys,h)
% Function multibody_response
%
% :param B_c: B_c
% :param B_f: B_f
% :param B_s: B_s
% :param K_f: K_f
% :param K_s: K_s
% :param m_c: m_c
% :param m_f: m_f
% :param m_s: m_s
% :param w: Angular wave frequency (rad/s)
% :param K_p: K_p
% :param B_p: B_p
% :param F_f_mag: F_f_mag
% :param F_f_phase: F_f_phase
% :param F_s_mag: F_s_mag
% :param F_s_phase: F_s_phase
% :returns: mag_U
% :returns: real_P
% :returns: mag_X_u
% :returns: mag_X_f
% :returns: mag_X_s
% :returns: phase_X_f
% :returns: phase_X_s
% :returns: phase_U
% :returns: imag_P
% :returns: phase_X_u
%MULTIBODY_RESPONSE
%    [mag_U,real_P,mag_X_u,mag_X_f,mag_X_s,phase_X_f,phase_X_s,phase_U,imag_P,phase_X_u] = MULTIBODY_RESPONSE(B_c,B_f,B_s,K_f,K_s,M_C,M_F,M_S,W,K_p,B_p,F_f_mag,F_f_phase,F_s_mag,F_s_phase)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    24-Apr-2025 17:58:41

if nargin >= 17 && ~isempty(h) && isstruct(h)
    % Fast path: unpack pre-computed controller-independent terms supplied
    % by get_multibody_helper_terms, skipping their recomputation.
    t18       = h.t18;
    t9        = h.t9;
    t108      = h.t108;
    t121      = h.t121;
    t_110_118 = h.t_110_118;
    t144      = h.t144;
    t109      = h.t109;
    t119      = h.t119;
    D_sys     = h.D_sys;
    t145      = h.t145;
    t103      = h.t103;
    t126      = h.t126;
    t130      = h.t130;
    t129      = h.t129;
    t131      = h.t131;
    t102      = h.t102;
    t124      = h.t124;
else

% Slow path: compute all controller-independent intermediate variables.
s = w*1i;
t3 = B_c.*w;
t4 = B_f.*w;
t5 = B_s.*w;
K_s_B_f = K_s .* B_f;
K_f_B_s = K_f .* B_s;
t6 = K_f.*w;
t8 = m_c.^2;
t9 = w.^2;
t10 = t9 .* w;
t12 = K_f.*K_s;
t16 = -K_f;
t17 = -K_s;
t18 = 1.0./w;
% exp(1i*x) = cos(x) + 1i*sin(x); using real trig avoids complex exp and
% the intermediate 1i-multiply that would be needed to form the argument.
t30 = complex(cos(F_f_phase), sin(F_f_phase));
t31 = complex(cos(F_s_phase), sin(F_s_phase));
t27 = K_f.*1i;
t28 = K_s.*1i;
t34 = m_c.*s;
t11 = t9.^2;
t13 = t3.*2.0;
t14 = K_s_B_f .* w;
t15 = K_f_B_s .* w;
t19 = -t6;
t21 = m_c.*t10;
t22 = m_f.*t9;
t23 = m_f.*t10;
t24 = m_s.*t9;
t29 = -t12;
t33 = t5.*1i;
t37 = m_c.*t9.*2.0;
t40 = -t27;
t41 = -t28;
t42 = t4.*t5;
t45 = m_s.*t6.*w;
t47 = t12.*1i;
t56 = t3.^2;
t62 = t3.*s;
t63 = t4.*s;
t65 = 1i*t37;
t64 = t65/2;
t68 = B_c+t34;
t32 = m_f.*m_s.*t11;
t43 = t4.*t24;
t44 = t5.*t22;
t46 = K_s.*t22;
t48 = t8.*t11;
t49 = 1.0./t30;
t50 = 1.0./t31;
t51 = K_s_B_f .* s;
t52 = K_f_B_s .* s;
t53 = -t21;
t54 = -t23;
t55 = -t24;
t57 = m_c.*t9.*t13;
t58 = -t47;
t66 = t22.*1i;
t67 = t24.*1i;
t74 = -t64;
t75 = -t65;
t78 = t4.*t33;
t79 = -t56;
t80 = t3.*t65;
t83 = t45.*1i;
t84 = t22.*t28;
t88 = t56.*1i;
t93 = t4+t5+t13;
t95 = t3+t64;
t100 = t16+t17+t22+t24+t37;
t105 = t19+t21+t23+t62+t63;
t59 = -t32;
t70 = -t43;
t71 = -t44;
t72 = t32.*1i;
t76 = -t66;
t77 = -t67;
t81 = t43.*1i;
t85 = t48.*1i;
t91 = t44.*-1i;
t94 = -t88;
t97 = t93.^2;
t98 = K_s+t33+t55;
t99 = t4+t40+t66;
t101 = t100.^2;
t103 = t5+t41+t67+t95;
t106 = t6+t53+t54+t62+t63;
t109 = t40+t41+t65+t66+t67+t93;
t86 = -t72;
t90 = -t81;
t102 = t95+t99;
t104 = t3+t5+t28+t74+t77;
t107 = t97+t101;
t110 = t27+t28+t75+t76+t77+t93;
% Use precomputed D_sys (= -t34_impedance + i*w*t31_impedance) if provided by
% the caller (e.g. already returned from multibody_impedance).  D_sys is the
% complex system determinant that is independent of the controller (B_p, K_p)
% and would otherwise be recomputed identically on every controller evaluation.
if nargin < 16
    D_sys = t12+t32-t42-t48+t51+t52+t56+t80+t90+t91+t17.*t22+m_s.*t19.*w;
end
t111 = 1.0./t109;
t108 = sqrt(t107);
t112 = conj(t111);  % t110 = conj(t109)
t_Ff30 = F_f_mag.*t30;
t113 = t_Ff30.*t103.*t111;
t115 = t29+t42+t45+t46+t48+t51+t52+t59+t79+t80+t90+t91;
t117 = abs(t115);  % t116 = conj(t115), so abs is equal
t119 = -1.0./D_sys;
t122 = t14+t15+t57+t58+t70+t71+t78+t83+t84+t85+t86+t94;
t114 = F_f_mag.*t49.*t104.*t112;
t118 = 1.0./t115;
t121 = 1.0./t117;
t124 = 1.0./t122;
t_110_118 = t110.*t118;
t_Fs31_124 = F_s_mag.*t31.*t124;
t_Ff30_124w = t_Ff30.*t124.*w;
% Denominator 1i.*conj(D_sys) = complex(imag(D_sys),real(D_sys)); avoids
% a complex multiply by 1i in the denominator.
t142 = (F_s_mag.*t18.*t50.*t105.*t112.*t115)./complex(imag(D_sys),real(D_sys));
% z.*1i = complex(-imag(z),real(z)): multiplication by i is a 90° rotation,
% handled with a swap+negate rather than a full complex multiply.  Applies
% to t126, t128, and t131 below.
t_Fs31_t9_t68 = t_Fs31_124.*t9.*t68;
t126 = complex(-imag(t_Fs31_t9_t68), real(t_Fs31_t9_t68));
t127 = t_Ff30_124w.*t98;
t_Ff30w_t95 = t_Ff30_124w.*t95;
t128 = complex(-imag(t_Ff30w_t95), real(t_Ff30w_t95));
t_Fs31_t99w = t_Fs31_124.*t99.*w;
t131 = complex(-imag(t_Fs31_t99w), real(t_Fs31_t99w));
t143 = t_Fs31_124.*t18.*t106.*t111.*D_sys;
t145 = t114+t142;
t129 = -t128;
t130 = -t127;
t144 = t113+t143;

end % fast-path / slow-path

% Controller-dependent computations
t73  = K_p.*t18.*1i;
t92  = B_p+t73;
t96  = B_p-t73;
t133 = t96.*t109.*t119.*w;
t132 = t92.*t_110_118.*w;
t135 = t133+1.0;
t134 = t132+1.0;
t136 = abs(t135);
t137 = 1.0./t134;
t139 = 1.0./t136;
mag_X_u = t108.*t121.*t139.*abs(t144);
mag_U = mag_X_u .* abs(t96) .* w;
if nargout > 1
    t_denom = t135.*D_sys;              % = ((t96.*t109.*w)./D_sys-1.0).*D_sys
    t_numer = t9.*t96.*t109.*t144;      % shared factor in t146, t150
    t_n_d = t_numer./t_denom;
    % Guard against 0/0 = NaN: can occur when the excitation force vanishes at
    % the system resonant frequency (wave-cancellation + resonance coincidence).
    % The physical response in this degenerate case is zero (no drive → no motion).
%     if any(isnan(t_n_d),'all')
%         warning('0/0 in multibody_response: setting degenerate t_n_d to 0')
%         t_n_d(isnan(t_n_d)) = 0;
%     end
    % t146–t149 are only needed for mag/phase of X_f and X_s (nargout>3/4/5/6),
    % not for real_P, so their computation is deferred to those blocks below.
    t150 = -t_n_d.*t_110_118.*t137.*t145;
    real_P = real(t150)./2.0;
end
if nargout > 3
    t146 = -t_n_d.*t103.*t119;
    t148 = t126+t130+t146;
    mag_X_f = t18.*abs(t148);
end
if nargout > 4
    % -z.*1i = complex(imag(z),-real(z)): same 90° rotation pattern.
    t_nd_t102_t124 = t_n_d.*t102.*t124;
    t147 = complex(imag(t_nd_t102_t124), -real(t_nd_t102_t124));
    t149 = t129+t131+t147;
    mag_X_s = t18.*abs(t149);
end
if nargout > 5
    % angle(-t18*t148*1i): avoid complex *1i by using real/imag directly.
    % angle(-1i*z) = atan2(-re(z), im(z)); multiply both atan2 args by t18>0 (=1/w).
    phase_X_f = atan2(-t18.*real(t148), t18.*imag(t148));
end
if nargout > 6
    % angle(t18*t149*1i): avoid complex *1i by using real/imag directly.
    % angle(1i*z) = atan2(re(z), -im(z)); multiply both atan2 args by t18>0.
    phase_X_s = atan2(t18.*real(t149), -t18.*imag(t149));
end
if nargout > 7
    phase_U = angle(-t133.*t144./t135);  % (t96.*t109.*w)./D_sys-1 == -t135
end
if nargout > 8
    imag_P = imag(t150)./2.0;
end
if nargout > 9
    % angle(-1i*z) = atan2(-real(z), imag(z))
    t_tu = t109.*t144./t_denom;
    phase_X_u = atan2(-real(t_tu), imag(t_tu));
end
