function [real_G_u, imag_G_u] = multibody_impedance(B_c, B_f, B_s, K_f, K_s, m_c, m_f, m_s, w)
    % MULTIBODY_IMPEDANCE
    %    [real_G_u,imag_G_u] = MULTIBODY_IMPEDANCE(B_c,B_f,B_s,K_f,K_s,M_C,M_F,M_S,W)

    %    This function was generated by the Symbolic Math Toolbox version 9.1.
    %    21-Nov-2024 13:59:39

    t2 = B_c .* 2.0;
    t3 = B_c.^2;
    t4 = m_c.^2;
    t5 = w.^2;
    t7 = B_f .* K_s;
    t8 = B_s .* K_f;
    t9 = K_f .* K_s;
    t10 = -K_f;
    t11 = -K_s;
    t6 = t5.^2;
    t12 = m_f .* t5;
    t13 = m_s .* t5;
    t14 = -t9;
    t16 = B_f + B_s + t2;
    t17 = m_c .* t5 .* 2.0;
    t18 = B_f .* B_s .* t5;
    t24 = t3 .* t5;
    t25 = m_c .* t2 .* t5;
    t15 = m_f .* m_s .* t6;
    t19 = B_f .* t13;
    t20 = B_s .* t12;
    t21 = K_f .* t13;
    t22 = K_s .* t12;
    t23 = t4 .* t6;
    t29 = -t24;
    t30 = t10 + t11 + t12 + t13 + t17;
    t26 = -t15;
    t27 = -t19;
    t28 = -t20;
    t31 = t7 + t8 + t25 + t27 + t28;
    t34 = t14 + t18 + t21 + t22 + t23 + t26 + t29;
    t32 = t31.^2;
    t35 = t34.^2;
    t33 = t5 .* t32;
    t36 = t33 + t35;
    t37 = 1.0 ./ t36;
    real_G_u = t5 .* t16 .* t34 .* t37 - t5 .* t30 .* t31 .* t37;
    if nargout > 1
        imag_G_u = t30 .* t34 .* t37 .* w + t16 .* t31 .* t37 .* w.^3;
    end
