function [mag_U,phase_U,real_P,imag_P,mag_X_u,phase_X_u,mag_X_f,phase_X_f,mag_X_s,phase_X_s] = multibody_response(B_c,B_f,B_s,K_f,K_s,m_c,m_f,m_s,w,K_p,B_p,F_f_mag,F_f_phase,F_s_mag,F_s_phase)
%MULTIBODY_RESPONSE
%    [mag_U,phase_U,real_P,imag_P,mag_X_u,phase_X_u,mag_X_f,phase_X_f,mag_X_s,phase_X_s] = MULTIBODY_RESPONSE(B_c,B_f,B_s,K_f,K_s,M_C,M_F,M_S,W,K_p,B_p,F_f_mag,F_f_phase,F_s_mag,F_s_phase)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Apr-2026 16:50:42

t2 = abs(w);
t3 = B_c.*w;
t4 = B_f.*w;
t5 = B_s.*w;
t6 = K_f.*w;
t7 = B_c.^2;
t8 = m_c.^2;
t9 = w.^2;
t10 = w.^3;
t12 = K_f.*K_s;
t15 = -K_s;
t16 = 1.0./w;
t25 = F_f_phase.*1i;
t26 = F_s_phase.*1i;
t27 = K_f.*1i;
t28 = K_s.*1i;
t34 = m_c.*w.*1i;
t11 = t9.^2;
t13 = K_s.*t4;
t14 = K_f.*t5;
t17 = -t4;
t18 = -t5;
t19 = -t6;
t20 = 1.0./t2;
t21 = m_c.*t10;
t22 = m_f.*t9;
t23 = m_f.*t10;
t24 = m_s.*t9;
t29 = -t12;
t30 = exp(t25);
t31 = exp(t26);
t33 = t5.*1i;
t37 = -t25;
t38 = -t26;
t39 = -t27;
t40 = -t28;
t41 = t4.*t5;
t44 = m_s.*t6.*w;
t46 = t12.*1i;
t56 = t3.^2;
t57 = m_c.*t3.*t9.*2.0;
t62 = t3.*w.*1i;
t63 = t4.*w.*1i;
t64 = m_c.*t9.*1i;
t67 = B_c+t34;
t72 = K_p.*t16.*1i;
t79 = m_c.*t3.*t9.*2.0i;
t32 = m_f.*m_s.*t11;
t35 = -t13;
t36 = -t14;
t42 = t4.*t24;
t43 = t5.*t22;
t45 = K_s.*t22;
t47 = t8.*t11;
t48 = 1.0./t30;
t49 = 1.0./t31;
t50 = t13.*1i;
t51 = t14.*1i;
t52 = -t21;
t53 = -t22;
t54 = -t23;
t55 = -t24;
t58 = -t46;
t65 = t22.*1i;
t66 = t24.*1i;
t68 = -t57;
t69 = t17.*t24;
t70 = t18.*t22;
t73 = t4+t18;
t74 = -t64;
t77 = t4.*t33;
t78 = -t56;
t81 = t22.*t33;
t82 = t44.*1i;
t83 = t22.*t28;
t86 = -t72;
t87 = t56.*1i;
t88 = -t79;
t91 = B_p+t72;
t94 = t3+t64;
t105 = t19+t21+t23+t62+t63;
t59 = -t32;
t60 = -t50;
t61 = -t51;
t71 = t32.*1i;
t75 = -t65;
t76 = -t66;
t80 = t42.*1i;
t84 = t47.*1i;
t90 = t43.*-1i;
t92 = -t87;
t93 = t73.^2;
t95 = B_p+t86;
t96 = K_s+t33+t55;
t97 = K_f+t15+t24+t53;
t98 = t4+t39+t65;
t100 = t5+t40+t66+t94;
t106 = t6+t52+t54+t62+t63;
t85 = -t71;
t89 = -t80;
t99 = t97.^2;
t101 = t3+t5+t28+t74+t76;
t102 = t17+t27+t75+t94;
t103 = t18+t28+t76+t94;
t108 = t27+t40+t66+t73+t75;
t109 = t5+t17+t27+t40+t66+t75;
t115 = t29+t41+t44+t45+t47+t59+t60+t61+t78+t80+t81+t88;
t124 = -1.0./(t13+t14-t41.*1i-t45.*1i+t46+t57+t69+t70+t71-t82-t84+t87);
t104 = t93+t99;
t110 = 1.0./t108;
t111 = 1.0./t109;
t114 = t29+t41+t44+t45+t47+t50+t51+t59+t78+t79+t89+t90;
t116 = abs(t115);
t118 = -1.0./(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w);
t119 = 1.0./(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w).^2;
t121 = t13+t14+t57+t58+t69+t70+t77+t82+t83+t84+t85+t92;
t122 = t35+t36+t42+t43+t58+t68+t77+t82+t83+t84+t85+t92;
t137 = -1.0./((t95.*t109.*w)./(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w)-1.0);
t107 = sqrt(t104);
t112 = F_f_mag.*t30.*t100.*t111;
t113 = F_f_mag.*t48.*t101.*t110;
t117 = 1.0./t114;
t120 = 1.0./t116;
t123 = 1.0./t121;
t132 = t95.*t109.*t118.*w;
t139 = F_s_mag.*t16.*t49.*t105.*t110.*t114.*t124;
t141 = (F_s_mag.*t16.*t49.*t105.*t110.*t114)./(t13+t14-t41.*1i-t45.*1i+t46+t57+t69+t70+t71-t82-t84+t87);
t125 = F_s_mag.*t9.*t31.*t67.*t123.*1i;
t127 = F_f_mag.*t30.*t96.*t123.*w;
t128 = F_f_mag.*t30.*t94.*t123.*w.*1i;
t130 = F_s_mag.*t31.*t98.*t123.*w.*1i;
t131 = t91.*t108.*t117.*w;
t134 = t132+1.0;
t140 = -F_s_mag.*t16.*t31.*t106.*t111.*t123.*(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w);
t142 = F_s_mag.*t16.*t31.*t106.*t111.*t123.*(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w);
t144 = t113+t141;
t126 = -t125;
t129 = -t128;
t133 = t131-1.0;
t135 = abs(t134);
t143 = t112+t142;
t136 = 1.0./t133;
t138 = 1.0./t135;
mag_U = t107.*t120.*t138.*abs(t95.*t143.*w);
if nargout > 1
    phase_U = angle((t95.*t109.*t143.*w)./(((t95.*t109.*w)./(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w)-1.0).*(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w)));
end
if nargout > 2
    t145 = (t9.*t95.*t103.*t109.*t118.*t143)./(((t95.*t109.*w)./(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w)-1.0).*(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w));
    t146 = (t9.*t95.*t102.*t109.*t123.*t143.*1i)./(((t95.*t109.*w)./(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w)-1.0).*(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w));
    t147 = t126+t127+t145;
    t148 = t129+t130+t146;
    t149 = (t9.*t95.*t108.*t109.*t117.*t136.*t143.*t144)./(((t95.*t109.*w)./(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w)-1.0).*(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w));
    real_P = real(t149).*(-1.0./2.0);
end
if nargout > 3
    imag_P = imag(t149).*(-1.0./2.0);
end
if nargout > 4
    mag_X_u = t107.*t120.*t138.*abs(t143);
end
if nargout > 5
    phase_X_u = angle((t109.*t143.*-1i)./(((t95.*t109.*w)./(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w)-1.0).*(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w)));
end
if nargout > 6
    mag_X_f = t20.*abs(t147);
end
if nargout > 7
    phase_X_f = angle(t16.*(t125-t127+(t9.*t95.*t103.*t109.*t119.*t143)./((t95.*t109.*w)./(t12+t32-t47+t50+t51+t56+t79+t89+t90+t5.*t17+t15.*t22+m_s.*t19.*w)-1.0)).*1i);
end
if nargout > 8
    mag_X_s = t20.*abs(t148);
end
if nargout > 9
    phase_X_s = angle(t16.*t148.*-1i);
end
