function [real_G_u,imag_G_u] = multibody_impedance(B_c,B_f,B_s,K_f,K_s,m_c,m_f,m_s,w)
%MULTIBODY_IMPEDANCE
%    [real_G_u,imag_G_u] = MULTIBODY_IMPEDANCE(B_c,B_f,B_s,K_f,K_s,M_C,M_F,M_S,W)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    10-Apr-2026 16:50:41

t2 = B_c.^2;
t3 = m_c.^2;
t4 = w.^2;
t6 = B_f.*K_s;
t7 = B_s.*K_f;
t8 = K_f.*K_s;
t9 = -B_s;
t10 = -K_s;
t5 = t4.^2;
t11 = m_f.*t4;
t12 = m_s.*t4;
t13 = -t8;
t15 = B_f+t9;
t16 = B_f.*B_s.*t4;
t23 = t2.*t4;
t24 = B_c.*m_c.*t4.*2.0;
t14 = m_f.*m_s.*t5;
t17 = B_f.*t12;
t18 = B_s.*t11;
t19 = K_f.*t12;
t20 = K_s.*t11;
t21 = t3.*t5;
t22 = -t11;
t27 = t9.*t11;
t28 = -t23;
t25 = -t14;
t26 = -t17;
t29 = K_f+t10+t12+t22;
t30 = t6+t7+t24+t26+t27;
t33 = t13+t16+t19+t20+t21+t25+t28;
t31 = t30.^2;
t34 = t33.^2;
t32 = t4.*t31;
t35 = t32+t34;
t36 = 1.0./t35;
real_G_u = -t4.*t15.*t33.*t36-t4.*t29.*t30.*t36;
if nargout > 1
    imag_G_u = t29.*t33.*t36.*w-t15.*t30.*t36.*w.^3;
end
