function P_avg_sat_over_P_avg_unsat = power_saturation_ratio(limit_to_peak_ratio, peak_to_average_ratio)
%POWER_SATURATION_RATIO
%    P_avg_sat_over_P_avg_unsat = POWER_SATURATION_RATIO(limit_to_peak_ratio, peak_to_average_ratio)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    29-Jan-2025 01:17:12

LTPR = limit_to_peak_ratio;
PTAR = peak_to_average_ratio;

num = LTPR - 1./PTAR;
den = 1 - 1./PTAR;
P_max_ratio = num ./ den;

cos_phase_delta_PTO_force_to_velocity = 1./ (PTAR - 1);
t2 = acos(P_max_ratio);
t3 = cos_phase_delta_PTO_force_to_velocity;
t4 = P_max_ratio.^2;
t5 = t3.*2.0;
t6 = P_max_ratio.*t2;
t7 = t3.*pi;
t9 = 1.0./t3;
t10 = -t4;
t11 = P_max_ratio+t5;
t13 = t10+1.0;
t12 = acos(t11);
t14 = sqrt(t13);
t15 = -t14;

idx_use_1 = t11 < 1.0;

result1 = (t6+t7+t15-P_max_ratio.*t12-t3.*t12.*2.0+sqrt(t13-P_max_ratio.*t3.*4.0-1.0./t9.^2.*4.0))./t7;
result2 = (t6+t7+t15)./t7;

P_avg_sat_over_P_avg_unsat = result2;
P_avg_sat_over_P_avg_unsat(idx_use_1) = result1(idx_use_1);

P_avg_sat_over_P_avg_unsat(P_avg_sat_over_P_avg_unsat < 0) = 0;
