function P_avg_sat_over_P_avg_unsat = power_saturation_ratio(P_max_ratio,phi)
%POWER_SATURATION_RATIO
%    P_avg_sat_over_P_avg_unsat = POWER_SATURATION_RATIO(P_max_ratio,PHI)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    29-Jan-2025 01:17:12

t2 = acos(P_max_ratio);
t3 = cos(phi);
t4 = P_max_ratio.^2;
t8 = 1.0./pi;
t5 = t3.*2.0;
t6 = P_max_ratio.*t2;
t7 = t3.*pi;
t9 = 1.0./t3;
t10 = -t4;
t11 = P_max_ratio+t5;
t13 = t10+1.0;
t12 = acos(t11);
t14 = sqrt(t13);
t15 = -t14;
if (t11 < 1.0)
    P_avg_sat_over_P_avg_unsat = (t6+t7+t15-P_max_ratio.*t12-t3.*t12.*2.0+sqrt(t13-P_max_ratio.*t3.*4.0-1.0./t9.^2.*4.0))./t7;
else
    P_avg_sat_over_P_avg_unsat = (t6+t7+t15)./t7;
end
