
function [LCOE, capex, opex] = econ(m_m, M, cost_m, N_WEC, P_elec, FCR, efficiency)

structural_cost = m_m.* cost_m;
devicestructure =  N_WEC * structural_cost(M);

% costs taken from 'CBS (Total)' tab of the RM3 cost breakdown structure
% https://catalog.data.gov/ne/dataset/reference-model-3-cost-breakdown-rm3-wave-point-absorber
development     = 4553000;
infrastructure  = 990000;
mooring         = N_WEC * 525000;
pto             = N_WEC * 623000;
profitmargin    = 356000;
installation    = 5909000;
contingency     = 1590000;

capex = development + infrastructure + mooring + devicestructure + pto ...
        + profitmargin + installation + contingency; 

% opex reflects cost of operation, postinstall, replacement, consumables, and
% insurance
% opex equation was generated by Casio online power regression calculator
opex = 1193000 * N_WEC^0.4433;

hr_per_yr = 8766;
P_avg = N_WEC * P_elec * efficiency;
aep = P_avg * hr_per_yr / 1000; % annual energy production: W to kWh per year

LCOE = (FCR*capex + opex)/aep;

end