
%[AUTOGENERATED]
%[AUTOGENERATED]
function net_eco_value = enviro(steel_mass, distance_from_shore, fiberglass_area, ...
                                CEM_CO2, CEM_WEC_capacity, rated_power_per_wec, ...
                                eco_cost_steel, eco_cost_fiberglass, ...
                                eco_cost_distance, social_cost_carbon)
% Function enviro
%
% :param steel_mass: steel_mass
% :param distance_from_shore: distance from shore (miles)
% :param fiberglass_area: fiberglass_area
% :param CEM_CO2: CEM_CO2
% :param CEM_WEC_capacity: CEM_WEC_capacity
% :param rated_power_per_wec: rated_power_per_wec
% :param eco_cost_steel: eco-cost of steel ($/kg)
% :param eco_cost_fiberglass: eco-cost of steel ($/m^2)
% :param eco_cost_distance: eco-cost per mile from shore of fuel for boat travel ($/mi)
% :param social_cost_carbon: social_cost_carbon
% :returns: net_eco_value
% Function enviro
%
% :param steel_mass: steel_mass
% :param distance_from_shore: distance from shore (miles)
% :param fiberglass_area: fiberglass_area
% :param CEM_CO2: CEM_CO2
% :param CEM_WEC_capacity: CEM_WEC_capacity
% :param rated_power_per_wec: rated_power_per_wec
% :param eco_cost_steel: eco-cost of steel ($/kg)
% :param eco_cost_fiberglass: eco-cost of steel ($/m^2)
% :param eco_cost_distance: eco-cost per mile from shore of fuel for boat travel ($/mi)
% :param social_cost_carbon: social_cost_carbon
% :returns: net_eco_value

    % units: [steel_kg, distance_miles, fiberglass_meters_sq, CEM_CO2_tonne]

    CEM_CO2_kg = CEM_CO2 * 1e3; % ton to kg
    num_wecs_CEM = 100; %CEM_WEC_capacity / rated_power_per_wec;

    % cost and value
    eco_value_total = CEM_CO2_kg * social_cost_carbon;
    eco_cost_per_wec = eco_cost_steel * steel_mass + eco_cost_fiberglass * fiberglass_area + eco_cost_distance * distance_from_shore;
    eco_cost_total = eco_cost_per_wec * num_wecs_CEM;

    % convert eco
    net_eco_value = (eco_value_total - eco_cost_total);
end