%[AUTOGENERATED]
%[AUTOGENERATED]
function intermed_result_struct = analysis_fcn(~,~)
% Function analysis_fcn
%
% :param ~: ~
% :param ~: ~
% :returns: Intermediate results struct (cached heavy analyses)
    % Run describing function demo and capture returned figure handles
    figs = sin_desc_fcn_demo();
    intermed_result_struct.created_figs = figs;
end
