classdef DescFcns < GenericAnalysis
    %DESCFCNS Analysis class for describing function figures
    %   Generates drag and saturation describing function figures

    properties
        fig_names = {'saturation_desc_fcn',...
                     'saturation_desc_fcn_alpha',...
                     'drag_desc_fcn'};
        tab_names = {};
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
