%[AUTOGENERATED]
%[AUTOGENERATED]
function intermed_result_struct = analysis_fcn(~,~)
% Function analysis_fcn
%
% :param ~: ~
% :param ~: ~
% :returns: Intermediate results struct (cached heavy analyses)
    % Run spar hydrodynamic analysis
    fig = spar_hydro_plot();
    
    % Store figure for post-processing
    intermed_result_struct.figure_handle = fig;
end
