function [hydro_nondim_NMK,phi_i1_NMK,phi_i2_NMK,phi_e_NMK,phi_p_i1_NMK,phi_p_i2_NMK,phi_h_i1_NMK,phi_h_i2_NMK,v_1_r_NMK,v_1_z_NMK,v_2_r_NMK,v_2_z_NMK,v_e_r_NMK,v_e_z_NMK] = hydro_potential_velocity_fields_N3_M3_K3_heaving_outer(a1,a2,d1,d2,h,m0,m_k_const1,m_k_const2,m_k_const3,C_1n_1_const1,C_1n_1_const2,C_1n_1_const3,C_1n_1_const4,C_1m_2_const1,C_1m_2_const2,C_1m_2_const3,C_1m_2_const4,C_2m_2_const1,C_2m_2_const2,C_2m_2_const3,C_2m_2_const4,B_k_const1,B_k_const2,B_k_const3,B_k_const4,r,z)
%hydro_potential_velocity_fields_N3_M3_K3_heaving_outer
%    [hydro_nondim_NMK,phi_i1_NMK,phi_i2_NMK,phi_e_NMK,phi_p_i1_NMK,phi_p_i2_NMK,phi_h_i1_NMK,phi_h_i2_NMK,v_1_r_NMK,v_1_z_NMK,v_2_r_NMK,v_2_z_NMK,v_e_r_NMK,v_e_z_NMK] = hydro_potential_velocity_fields_N3_M3_K3_heaving_outer(A1,A2,D1,D2,H,M0,M_K_CONST1,M_K_CONST2,M_K_CONST3,C_1n_1_const1,C_1n_1_const2,C_1n_1_const3,C_1n_1_const4,C_1m_2_const1,C_1m_2_const2,C_1m_2_const3,C_1m_2_const4,C_2m_2_const1,C_2m_2_const2,C_2m_2_const3,C_2m_2_const4,B_k_const1,B_k_const2,B_k_const3,B_k_const4,R,Z)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Jan-2025 16:25:41

t2 = log(a2);
t3 = log(r);
t4 = a2.*m0;
t5 = a2.*m_k_const1;
t6 = a2.*m_k_const2;
t7 = a2.*m_k_const3;
t8 = m0.*r;
t9 = m_k_const1.*r;
t10 = m_k_const2.*r;
t11 = m_k_const3.*r;
t12 = h+z;
t13 = a1.^2;
t14 = a2.^2;
t15 = d2.*2.0;
t16 = h.*2.0;
t17 = r.^2;
t22 = 1.0./pi;
t23 = -h;
t25 = 1.0./h;
t26 = 1.0./m_k_const1;
t27 = 1.0./m_k_const2;
t28 = 1.0./m_k_const3;
t33 = sqrt(2.0);
t43 = C_1n_1_const1./2.0;
t44 = C_1m_2_const1./2.0;
t49 = sqrt(h);
t50 = m0.^(3.0./2.0);
t18 = m0.*t16;
t19 = m_k_const1.*t16;
t20 = m_k_const2.*t16;
t21 = m_k_const3.*t16;
t24 = -t16;
t29 = m0.*t12;
t30 = m_k_const1.*t12;
t31 = m_k_const2.*t12;
t32 = m_k_const3.*t12;
t34 = besselh(0.0,1,t4);
t35 = besselk(0,t5);
t36 = besselk(0,t6);
t37 = besselk(0,t7);
t38 = besselh(0.0,1,t8);
t39 = t12.^2;
t40 = besselk(0,t9);
t41 = besselk(0,t10);
t42 = besselk(0,t11);
t51 = t2./2.0;
t52 = t3./2.0;
t57 = d1+t23;
t58 = d2+t23;
t59 = t17./2.0;
t45 = sinh(t18);
t46 = sin(t19);
t47 = sin(t20);
t48 = sin(t21);
t53 = cosh(t29);
t54 = cos(t30);
t55 = cos(t31);
t56 = cos(t32);
t60 = -t52;
t61 = -t59;
t62 = t15+t24;
t63 = t58.^2;
t64 = 1.0./t34;
t65 = 1.0./t35;
t66 = 1.0./t36;
t67 = 1.0./t37;
t68 = 1.0./t57;
t69 = 1.0./t58;
t70 = t18+t45;
t71 = 1.0./t62;
t72 = r.*t68.*pi;
t73 = r.*t69.*pi;
t74 = a2.*t68.*pi;
t75 = a2.*t69.*pi;
t87 = t39+t61;
t92 = t51+t60;
t93 = t12.*t68.*pi;
t94 = t12.*t69.*pi;
t124 = (t25.*t26.*t46)./2.0;
t125 = (t25.*t27.*t47)./2.0;
t126 = (t25.*t28.*t48)./2.0;
t76 = t72.*2.0;
t77 = t72.*3.0;
t78 = t73.*2.0;
t79 = t73.*3.0;
t80 = t74.*2.0;
t81 = t74.*3.0;
t82 = t75.*2.0;
t83 = t75.*3.0;
t84 = -t73;
t88 = besseli(0,t74);
t89 = besseli(0,t75);
t90 = besseli(0,t72);
t91 = besseli(0,t73);
t95 = -t75;
t98 = cos(t93);
t99 = cos(t94);
t108 = 1.0./sqrt(t70);
t109 = t93.*2.0;
t110 = t93.*3.0;
t111 = t94.*2.0;
t112 = t94.*3.0;
t120 = C_2m_2_const1.*t92;
t137 = t124+1.0;
t138 = t125+1.0;
t139 = t126+1.0;
t143 = t71.*t87;
t85 = -t78;
t86 = -t79;
t96 = -t82;
t97 = -t83;
t100 = besseli(0,t80);
t101 = besseli(0,t81);
t102 = besseli(0,t82);
t103 = besseli(0,t83);
t104 = besseli(0,t76);
t105 = besseli(0,t77);
t106 = besseli(0,t78);
t107 = besseli(0,t79);
t113 = cos(t109);
t114 = cos(t110);
t115 = cos(t111);
t116 = cos(t112);
t117 = besselk(0,t95);
t121 = besselk(0,t84);
t127 = 1.0./t88;
t128 = 1.0./t89;
t129 = -t120;
t140 = 1.0./sqrt(t137);
t141 = 1.0./sqrt(t138);
t142 = 1.0./sqrt(t139);
t144 = -t143;
t118 = besselk(0,t96);
t119 = besselk(0,t97);
t122 = besselk(0,t85);
t123 = besselk(0,t86);
t130 = 1.0./t100;
t131 = 1.0./t101;
t132 = 1.0./t102;
t133 = 1.0./t103;
t134 = 1.0./t117;
t145 = C_1m_2_const2.*t91.*t128;
t151 = C_1n_1_const2.*t90.*t98.*t127;
t135 = 1.0./t118;
t136 = 1.0./t119;
et1 = (C_1m_2_const1.*t13)./4.0-(C_1m_2_const1.*t14)./4.0-C_2m_2_const1.*log(a2.^(t13./4.0).*a2.^(t14.*(-1.0./4.0)))+(t13.^2.*t71)./8.0-(t14.^2.*t71)./8.0+(C_2m_2_const1.*((t13.*(log(a1)-1.0./2.0))./2.0-(t14.*(t2-1.0./2.0))./2.0))./2.0-(t13.*t63.*t71)./2.0+(t14.*t63.*t71)./2.0+C_2m_2_const2.*t22.*t33.*t58.*t134.*(a2.*besselk(1,t95)-a1.*besselk(1,-a1.*t69.*pi))-(C_2m_2_const3.*t22.*t33.*t58.*t135.*(a2.*besselk(1,t96)-a1.*besselk(1,a1.*t69.*pi.*-2.0)))./2.0+(C_2m_2_const4.*t22.*t33.*t58.*t136.*(a2.*besselk(1,t97)-a1.*besselk(1,a1.*t69.*pi.*-3.0)))./3.0;
et2 = C_1m_2_const2.*t22.*t33.*t58.*t128.*(a1.*besselj(1,a1.*t69.*pi.*1i)-a2.*besselj(1,t75.*1i)).*1i-C_1m_2_const3.*t22.*t33.*t58.*t132.*(a1.*besselj(1,a1.*t69.*pi.*2.0i)-a2.*besselj(1,t75.*2.0i)).*5.0e-1i+C_1m_2_const4.*t22.*t33.*t58.*t133.*(a1.*besselj(1,a1.*t69.*pi.*3.0i)-a2.*besselj(1,t75.*3.0i)).*3.333333333333333e-1i;
hydro_nondim_NMK = 1.0./a2.^3.*1.0./t25.^3.*(et1+et2).*-2.0;
if nargout > 1
    t146 = C_1m_2_const3.*t106.*t132;
    t147 = C_1m_2_const4.*t107.*t133;
    t148 = C_2m_2_const2.*t121.*t134;
    t152 = C_1n_1_const3.*t104.*t113.*t130;
    t153 = C_1n_1_const4.*t105.*t114.*t131;
    t149 = C_2m_2_const3.*t122.*t135;
    t150 = C_2m_2_const4.*t123.*t136;
    t154 = t145+t148;
    t160 = t151+t152+t153;
    t155 = t146+t149;
    t156 = t147+t150;
    t157 = t99.*t154;
    t161 = t33.*t160;
    t158 = t115.*t155;
    t159 = t116.*t156;
    t162 = t43+t161;
    phi_i1_NMK = t162;
end
if nargout > 2
    t163 = t157+t158+t159;
    t164 = t33.*t163;
    phi_i2_NMK = t44+t129+t144+t164;
end
if nargout > 3
    phi_e_NMK = t33.*(B_k_const2.*t40.*t54.*t65.*t140+B_k_const3.*t41.*t55.*t66.*t141+B_k_const4.*t42.*t56.*t67.*t142)+B_k_const1.*sqrt(m0).*t38.*t49.*t53.*t64.*t108.*2.0;
end
if nargout > 4
    phi_p_i1_NMK = 0.0;
end
if nargout > 5
    phi_p_i2_NMK = t144;
end
if nargout > 6
    phi_h_i1_NMK = t162;
end
if nargout > 7
    phi_h_i2_NMK = t44+t129+t164;
end
if nargout > 8
    v_1_r_NMK = t33.*t68.*pi.*(C_1n_1_const2.*t98.*t127.*besseli(1,t72)+C_1n_1_const3.*t113.*t130.*besseli(1,t76).*2.0+C_1n_1_const4.*t114.*t131.*besseli(1,t77).*3.0);
end
if nargout > 9
    v_1_z_NMK = -t33.*t68.*pi.*(C_1n_1_const2.*t90.*t127.*sin(t93)+C_1n_1_const3.*t104.*t130.*sin(t109).*2.0+C_1n_1_const4.*t105.*t131.*sin(t110).*3.0);
end
if nargout > 10
    v_2_r_NMK = r.*t71+C_2m_2_const1./(r.*2.0)+t33.*(t99.*(C_1m_2_const2.*t69.*t128.*pi.*besseli(1,t73)+C_2m_2_const2.*t69.*t134.*pi.*besselk(1,t84))+t115.*(C_1m_2_const3.*t69.*t132.*pi.*besseli(1,t78).*2.0+C_2m_2_const3.*t69.*t135.*pi.*besselk(1,t85).*2.0)+t116.*(C_1m_2_const4.*t69.*t133.*pi.*besseli(1,t79).*3.0+C_2m_2_const4.*t69.*t136.*pi.*besselk(1,t86).*3.0));
end
if nargout > 11
    v_2_z_NMK = t12.*t71.*-2.0-t33.*t69.*pi.*(t154.*sin(t94)+t155.*sin(t111).*2.0+t156.*sin(t112).*3.0);
end
if nargout > 12
    v_e_r_NMK = -t33.*(B_k_const2.*m_k_const1.*t54.*t65.*t140.*besselk(1,t9)+B_k_const3.*m_k_const2.*t55.*t66.*t141.*besselk(1,t10)+B_k_const4.*m_k_const3.*t56.*t67.*t142.*besselk(1,t11))-B_k_const1.*t49.*t50.*t53.*t64.*t108.*besselh(1.0,1,t8).*2.0;
end
if nargout > 13
    v_e_z_NMK = -t33.*(B_k_const2.*m_k_const1.*t40.*t65.*t140.*sin(t30)+B_k_const3.*m_k_const2.*t41.*t66.*t141.*sin(t31)+B_k_const4.*m_k_const3.*t42.*t67.*t142.*sin(t32))+B_k_const1.*t38.*t49.*t50.*t64.*t108.*sinh(t29).*2.0;
end
end
