%[DOCS AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
                 
    p = intermed_result_struct.p;
    b = intermed_result_struct.b;
    Xs = intermed_result_struct.Xs;
    vals = intermed_result_struct.vals;
    [DV_table, out_table, fig_array] = compare(p,b,Xs,vals);
    
    tab_array_display = {DV_table, ...
                         out_table};
    tab_array_latex = tab_array_display;
    
    tab_firstrows = {[], []};
    tab_colspecs = {[], []};
    
    end_result_struct.comparison_complete = true;

    end_result_struct.powerAvgAtMinCapex = vals(3).power_avg;
    end_result_struct.capexDesignMinCapex = vals(3).capex_design;

    end_result_struct.powerAvgMaxPower = vals(4).power_avg;
    end_result_struct.capexDesignMaxPower = vals(4).capex_design;

    end_result_struct.powerBalanced = vals(5).power_avg;

    cost_savings_PTO = vals(2).capex_PTO - vals(3).capex_PTO;
    cost_savings_total = vals(2).capex - vals(3).capex;
    end_result_struct.pctCostSavingsFromPTO = cost_savings_PTO / cost_savings_total * 100;
end
