classdef LocationSensitivity < GenericAnalysis
    %LOCATIONSENSITIVITY Analysis class for location sensitivity tables
    %   Generates location sensitivity analysis table

    properties
        fig_names = {'location_1_power_matrix',...
                     'location_2_power_matrix',...
                     'location_3_power_matrix',...
                     'location_4_power_matrix',...
                     'location_probability_PDF'};
        tab_names = {'location_sensitivity'};
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
