%[AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
    
    p = intermed_result_struct.p;
    b = intermed_result_struct.b;
    flux = intermed_result_struct.flux;
    BW = intermed_result_struct.BW;
    storm = intermed_result_struct.storm;
    depths = intermed_result_struct.depths;
    locs = intermed_result_struct.locs;
    most_common_wave = intermed_result_struct.most_common_wave;
    X_opts = intermed_result_struct.X_opts;
    obj_opts = intermed_result_struct.obj_opts;
    flags = intermed_result_struct.flags;

    [tab, pct_diff, ...
     location_flags, ...
     tablatex] = location_post_process(p, b, flux, BW, storm, depths, ...
                                        locs, most_common_wave, ...
                                        X_opts, obj_opts, flags);
    
    fig_array = [intermed_result_struct.h_power_matrix; ...
                 intermed_result_struct.h_probability_PDF];
    
    tab_array_display = {tab};
    tab_array_latex = {tablatex};
    
    tab_colspecs = {['>{\centering\arraybackslash}p{0.22\linewidth}' ...
               '>{\centering\arraybackslash}p{0.08\linewidth}' ...
               '>{\centering\arraybackslash}p{0.17\linewidth}' ...
               '>{\centering\arraybackslash}p{0.17\linewidth}' ...
               '>{\centering\arraybackslash}p{0.17\linewidth}' ...
               '>{\centering\arraybackslash}p{0.18\linewidth}']};
    tab_firstrows = {'&& \multicolumn{4}{c}{Location}\\  \cline{3-6}'};

    end_result_struct.location_flags = location_flags;
    end_result_struct.pct_diff_lcoe_hawaii = pct_diff;
end
