classdef SweepGeoms < GenericAnalysis
    %SWEEPGEOMS Analysis class for geometry sweep figures
    %   Sweeps six geometric ratios and water depth to explore how the
    %   non-dimensional wave-body parameter m_0*h and the geometry
    %   influence the ratio CW/CW_max.  Also produces capture-width-ratio
    %   (CWR = CW / charac_dim) variants using three characteristic
    %   dimensions: float radius a_2, cube-root of displaced volume, and
    %   square-root of wetted surface area.

    properties
        fig_names = {'sweep_geoms_parallel', ...
                     'sweep_geoms_scatter', ...
                     'sweep_geoms_line', ...
                     'sweep_geoms_scatter_cwr_a2', ...
                     'sweep_geoms_scatter_cwr_vol', ...
                     'sweep_geoms_scatter_cwr_sa', ...
                     'sweep_geoms_line_cwr_a2', ...
                     'sweep_geoms_line_cwr_vol', ...
                     'sweep_geoms_line_cwr_sa', ...
                     'sweep_geoms_pareto', ...
                     'sweep_geoms_pareto_nondim', ...
                     'sweep_geoms_grid_scatter',...
                     'factor_grid'};
        tab_names = {};
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
    end
end
