%[DOCS AUTOGENERATED]
function [figPotMatch, figVelMatch, figAMatrixSparsity, figHydroCoeff] = validate_MEEM()
% Function validate_MEEM
%
% :returns: figPotMatch
% :returns: figVelMatch
% :returns: figAMatrixSparsity
% :returns: figHydroCoeff

    %% settings 
    auto_BCs = false;

    NMK_sparsity = 4;
    NMK_validate = 10;
    
    N_num = NMK_validate;
    M_num = NMK_validate;
    K_num = NMK_validate;

    heaving_OC = true;
    heaving_IC = false;

    plot_phi = true;
    show_A = true;

    %% set numerical values
    a1_num = .5;
    a2_num = 1;
    d1_num = .5;
    d2_num = .25;
    h_num = 1.001;
    m0_num = 1;
    spatial_res = 30;

    %% run with small NMK for sparsity
    warning('off','MATLAB:nearlySingularMatrix')
    warning('off','MATLAB:singularMatrix')

    run_MEEM(heaving_IC, heaving_OC, auto_BCs, NMK_sparsity, NMK_sparsity, NMK_sparsity, ...
                        a1_num, a2_num, d1_num, d2_num, h_num, m0_num, spatial_res, show_A, plot_phi);
    n = gcf().Number;
    figAMatrixSparsity = figure(n-8);

    %% run validation of potential for single frequency
    % produces 8 figures if plot_phi is on, + 3 more if show_A is on
    run_MEEM(heaving_IC, heaving_OC, auto_BCs, N_num, M_num, K_num, ...
                        a1_num, a2_num, d1_num, d2_num, h_num, m0_num, spatial_res, show_A, plot_phi);
    n = gcf().Number;
    figVelMatch  = figure(n);
    figPotMatch  = figure(n-1);
    figVelArrows = figure(n-2);
    figVelZ      = figure(n-3);
    figVelR      = figure(n-4);
    figPhiP      = figure(n-5);
    figPhiH      = figure(n-6);
    figPhiTotal  = figure(n-7);

    %figAMatrixSparsity = figure(n-8);
    figAMatrixImag     = figure(n-9);
    figAMatrixReal     = figure(n-10);

    figure(figPotMatch);
    plot_potential_validation()

    %% run validation of hydro coeffs for various frequencies
    m0_nums = [linspace(0.01,0.1,10), linspace(0.1,6,100)];
    plot_phi = false;
    show_A = false;
    [mu_nondim, lambda_nondim] = run_MEEM(heaving_IC, heaving_OC, auto_BCs, N_num, M_num, K_num, ...
                        a1_num, a2_num, d1_num, d2_num, h_num, m0_nums, spatial_res, show_A, plot_phi);

    figHydroCoeff = figure;
    plot(m0_nums, mu_nondim, m0_nums, lambda_nondim)
    ylabel('Nondimensional Hydro Coeff','Interpreter','latex')
    xlabel('Nondimensional Wavenumber $m_0h$','Interpreter','latex')
    legend('Added Mass: MDOcean','Damping: MDOcean','Interpreter','latex')
    grid on
    hold on
    plot_hydro_coeff_validation()

    warning('on','MATLAB:nearlySingularMatrix')
    warning('on','MATLAB:singularMatrix')
end

%% validation functions
function plot_potential_validation()
    a1_potential = readmatrix("inputs/validation/MEEM_validation/potential_a1.csv");
    a2_potential = readmatrix("inputs/validation/MEEM_validation/potential_a2.csv");
    plot(a1_potential(:,1),a1_potential(:,2),'m-*','DisplayName','Chau \& Yeung 2012 at $a_1$')
    plot(a2_potential(:,1),a2_potential(:,2),'b-*','DisplayName','Chau \& Yeung 2012 at $a_2$')
    legend('interpreter','latex')
    improvePlot
end

function plot_hydro_coeff_validation()
    mu_nondim = readmatrix("inputs/validation/MEEM_validation/added_mass.csv");
    lambda_nondim = readmatrix("inputs/validation/MEEM_validation/damping.csv");
    excitation_nondim = readmatrix("inputs/validation/MEEM_validation/excitation.csv");
    excitation_phase_nondim = readmatrix("inputs/validation/MEEM_validation/excitation_phase.csv");

    plot(mu_nondim(:,1),     mu_nondim(:,2),    'c--','DisplayName','Added Mass: Chau \& Yeung 2012')
    plot(lambda_nondim(:,1), lambda_nondim(:,2),'m--','DisplayName','Damping: Chau \& Yeung 2012')
    legend('interpreter','latex')
    improvePlot
    xlim([0 mu_nondim(end,1)])
end