%[DOCS AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
            
            tab = intermed_result_struct.params_table;

            % replace drag_fcn function handle with string for display purposes
            tab(strcmp(tab.name, 'drag_fcn'),{'value','value_normalize'}) = {'drag_fcn'};

            fig_array = [];
            
            tab_array_display = {tab};
            tab_array_latex = {tab};
            
            tab_firstrows = {[]};
            tab_colspecs = {[]};
            
            end_result_struct.forceScaleFactor = tab.value(strcmp(tab.name, 'F_heave_mult'));
            end_result_struct.powerScaleFactor = tab.value(strcmp(tab.name, 'power_scale_multibody'));
            end_result_struct.massScaleFactor  = tab.value(strcmp(tab.name, 'm_scale'));
end
