%[AUTOGENERATED]
function intermed_result_struct = analysis_fcn(p,b)
% Function analysis_fcn
%
% :param p: Parameter struct
% :param b: Design variable bounds struct
% :returns: Intermediate results struct (cached heavy analyses)
    % Run force saturation analysis
    [fig1, fig2] = force_sat_results(p, b);
    
    % Store figures for post-processing
    intermed_result_struct.fig1 = fig1;
    intermed_result_struct.fig2 = fig2;
end
