%[DOCS AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs

    fig_array = [intermed_result_struct.fig1, intermed_result_struct.fig2];
    
    tab_array_display = {};
    tab_array_latex = {};
    
    tab_firstrows = {};
    tab_colspecs = {};

    val_sat   = intermed_result_struct.val_sat;
    val_nosat = intermed_result_struct.val_nosat;

    % Re-optimized comparison: no-sat vs sat optimized designs
    % "power gain" when running without force saturation (more power, but higher cost)
    end_result_struct.pctPowerGainForceSatOptMinLCOE  = (val_nosat.power_avg - val_sat.power_avg) / val_sat.power_avg * 100;
    end_result_struct.pctPTOCostIncreaseForceSatOptMinLCOE = (val_nosat.capex_PTO - val_sat.capex_PTO) / val_sat.capex_PTO * 100;
    end_result_struct.pctStructCostIncreaseForceSatOptMinLCOE = (val_nosat.capex_struct - val_sat.capex_struct) / val_sat.capex_struct * 100;
    LCOE_sat   = intermed_result_struct.objs_sat(1);
    LCOE_nosat = intermed_result_struct.objs_nosat(1);
    end_result_struct.pctLCOEIncreaseForceSatOptMinLCOE = (LCOE_nosat - LCOE_sat) / LCOE_sat * 100;
    end_result_struct.force_saturation_analysis_complete = true;
end
