%[DOCS AUTOGENERATED]
function [m_f,B_h_f,K_h_f,gamma_f_mag,gamma_f_phase,...
         m_s,B_h_s,K_h_s,gamma_s_mag,gamma_s_phase,...
         m_c,B_h_c,drag_const_f,drag_const_s,...
         mag_v0_f,mag_v0_s,H,w,k,A_f_over_rho, ...
         A_s_over_rho, A_c_over_rho, ...
        B_f_over_rho_w, B_s_over_rho_w, B_c_over_rho_w, ...
        gamma_f_over_rho_g, gamma_s_over_rho_g] = get_dynamic_coeffs(Hs, T, ...
                                                D_f, T_f, D_s, D_d, T_s, h, ...
                                                m_float, m_spar, spar_excitation_coeffs,...
                                                C_d_float, C_d_spar, ...
                                                rho_w, g, use_MEEM, harmonics, ...
                                                hydro, m_k_h_precomputed)
% Function get_dynamic_coeffs
%
% :param Hs: significant wave height (m)
% :param T: wave energy period (s)
% :param D_f: Float Diameter
% :param T_f: T_f
% :param D_s: Spar Diameter
% :param D_d: Diameter of damping plate (m)
% :param T_s: Draft of spar (m)
% :param h: water depth (m)
% :param m_float: m_float
% :param m_spar: m_spar
% :param spar_excitation_coeffs: spar excitation hydro coeffs from WAMIT for nominal RM3
% :param C_d_float: coefficient of drag for float
% :param C_d_spar: spar coefficient of drag
% :param rho_w: water density (kg/m3)
% :param g: acceleration of gravity (m/s2)
% :param use_MEEM: whether to use MEEM for hydro coeffs (boolean)
% :param harmonics: number of harmonics to use for MEEM (int)
% :param hydro: function from WECSim
% :param m_k_h_precomputed: m_k_h_precomputed
% :returns: m_f
% :returns: B_h_f
% :returns: K_h_f
% :returns: $\\gamma$ f mag
% :returns: $\\gamma$ f phase
% :returns: m_s
% :returns: B_h_s
% :returns: K_h_s
% :returns: $\\gamma$ s mag
% :returns: $\\gamma$ s phase
% :returns: m_c
% :returns: B_h_c
% :returns: drag_const_f
% :returns: drag_const_s
% :returns: mag_v0_f
% :returns: mag_v0_s
% :returns: H
% :returns: Angular wave frequency (rad/s)
% :returns: Wavenumber (1/m)
% :returns: A f / $\\rho$
% :returns: A s / $\\rho$
% :returns: A c / $\\rho$
% :returns: B f / $\\rho$ w
% :returns: B s / $\\rho$ w
% :returns: B c / $\\rho$ w
% :returns: $\\gamma$ f / $\\rho$ g
% :returns: $\\gamma$ s / $\\rho$ g
    w = 2*pi./T;            % angular frequency
    k = dispersion(w,h,g);  % wave number (dispersion relation for finite depth water)

    a2 = D_f / 2;        % radius
    a1 = D_s / 2;
    a3 = D_d / 2;

    d2 = T_f;        % draft below waterline
    d1 = T_s;
    A_w_f = pi * (a2^2 - a1^2);     % waterplane area
    A_w_s = pi/4 * D_s^2; % fixme: for drag, should the area be the damping plate area, not the waterplane area?
    
    if use_MEEM
        [A_f_over_rho, A_s_over_rho, A_c_over_rho, ...
        B_f_over_rho_w, B_s_over_rho_w, B_c_over_rho_w, ...
        gamma_f_over_rho_g, gamma_s_over_rho_g, ...
        gamma_f_phase, gamma_s_phase] = get_hydro_coeffs_MEEM(a2, k, d2, a1, d1, a3, h, g, w, ...
                                                              harmonics, spar_excitation_coeffs, ...
                                                              m_k_h_precomputed); 
    else
        [A_f_over_rho, A_s_over_rho, A_c_over_rho, ...
        B_f_over_rho_w, B_s_over_rho_w, B_c_over_rho_w, ...
        gamma_f_over_rho_g, gamma_s_over_rho_g, ...
        gamma_f_phase, gamma_s_phase] = get_hydro_coeffs(a2, k, d2, hydro);
    end

    A_f = rho_w * A_f_over_rho;               % added mass
    A_s = rho_w * A_s_over_rho;
    A_c = rho_w * A_c_over_rho;

    m_f = A_f + m_float;                      % total mass
    m_s = A_s + m_spar;
    m_c = A_c;

    B_h_f   = rho_w * w .* B_f_over_rho_w;    % radiation damping
    B_h_s   = rho_w * w .* B_s_over_rho_w;
    B_h_c   = rho_w * w .* B_c_over_rho_w;

    gamma_f_mag = rho_w * g * gamma_f_over_rho_g; % excitation coefficient
    gamma_s_mag = rho_w * g * gamma_s_over_rho_g;

    K_h_f   = rho_w * g * A_w_f * ones(size(w));              % hydrostatic stiffness
    K_h_s   = rho_w * g * A_w_s * ones(size(w));

    A_drag_s = pi/4 * D_d^2;

                                              % values used for drag
    drag_const_f = 4/(3*pi) * rho_w * A_w_f * C_d_float;
    drag_const_s = 4/(3*pi) * rho_w * A_drag_s * C_d_spar;
    H = Hs / sqrt(2);                   % equivalent regular wave height
    mag_v0_f = H/2 * g .* k ./ w .* exp(-k * T_f); % finite depth velocity of incident wave
    mag_v0_s = H/2 * g .* k ./ w .* exp(-k * T_s);
end


