%[DOCS AUTOGENERATED]
function m_k_h_num = get_m_k_h(m0_h_num, K_num)
% Function get_m_k_h
%
% :param m0_h_num: m0_h_num
% :param K_num: K_num
% :returns: m_k_h_num
% solve for m_k from m_0 and h  

    m_k_h_num = zeros(1,K_num);
    % using tand instead of tan because finite precision of pi means
    % inconsistent behaviour around tan(pi/2)
    eqn = @(m_k_h_deg) (m_k_h_deg * pi/180) .* tand(m_k_h_deg) + m0_h_num * tanh(m0_h_num);

    for k_num = 1:K_num
        bounds = 180 * [k_num-1/2, k_num];
        % apply tweak determined experimentally to be the smallest tweak
        % that doesn't return +-Inf - see p17 of notebook
        expo = floor( log(bounds(1)) / log(2) );
        bound_tweak = eps * (2^(expo - 1) + 1);
        bounds(1) = bounds(1) + bound_tweak;

        m_k_h_deg = fzero(eqn, bounds);
        m_k_h_num(k_num) = m_k_h_deg * pi/180;
    end    

end