classdef GradientOptimFigFunc < GenericAnalysis
    %GRADIENTOPTIMFIGFUNC Analysis class for gradient optimization figures
    %   Generates single objective optimization convergence and visualization figures

    properties
        fig_names = {'single_obj_opt_power_matrix',...
                    'single_obj_opt_geometry', ...
                    'lagrange_multipliers',...
                    'delta_x', ...
                    'single_obj_convergence'};
        tab_names = {'single_obj_optim_results'};
    end

    methods (Static)
        intermed_result_struct = analysis_fcn(p,b)

        [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct] = post_process_fcn(intermed_result_struct)
    end
end
