%[DOCS AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
    
    p = intermed_result_struct.p;
    b = intermed_result_struct.b;
    which_objs = intermed_result_struct.which_objs;
    Xs_opt = intermed_result_struct.Xs_opt;
    objs_opt = intermed_result_struct.objs_opt;
    flags = intermed_result_struct.flags;
    lambdas = intermed_result_struct.lambdas;
    grads = intermed_result_struct.grads;
    hesses = intermed_result_struct.hesses;
    fmincon_outputs = intermed_result_struct.fmincon_outputs;

    [fig_array,tab] = SOO_result_plots(Xs_opt,lambdas,grads,hesses,objs_opt,which_objs,p,b);
    
    fig_array(end+1) = intermed_result_struct.convergence_plot;

    tab_array_display = {tab};
    tab_array_latex = {tab};
    
    tab_firstrows = {[]};
    tab_colspecs = {[]};
    
    [~,~,~,val] = simulation(Xs_opt,p);

    end_result_struct.convergence_achieved = all(flags > 0);
    end_result_struct.minLCOE = objs_opt(1,which_objs==1);
    end_result_struct.powerAvgAtMinLCOE = val.power_avg;
    end_result_struct.powerMaxAtMinLCOE = val.power_max;
    end_result_struct.forceMaxAtMinLCOE = val.force_heave;
    end_result_struct.structMassAtMinLCOE = val.mass_tot;
    end_result_struct.capexAtMinLCOE = val.capex;
    end_result_struct.capexDesignAtMinLCOE = val.capex_design;
    end_result_struct.DfoptMinLCOE = Xs_opt(b.var_names=="D_f",which_objs==1);
    end_result_struct.surgeForceFloatAtMinLCOE = val.force_surge(1);
    end_result_struct.surgeForceSparAtMinLCOE = val.force_surge(2);

    % Compute minimum power saturation ratio (P_sat/P_unsat) across operating sea states.
    % Named lowestFmaxFactorMinLCOE because it is the power factor attributable to the F_max force limit.
    P_sat_ratio = val.P_sat_ratio;
    operating_mask = p.JPD > 0 & isfinite(P_sat_ratio) & P_sat_ratio > 0;
    if any(operating_mask, 'all')
        end_result_struct.lowestFmaxFactorMinLCOE = min(P_sat_ratio(operating_mask));
    else
        end_result_struct.lowestFmaxFactorMinLCOE = NaN;
    end
    end_result_struct.lowestFsatMinLCOE = NaN; % requires unsaturated force per sea state, not yet computed

    % Extract total iterations and function evaluations from fmincon output for LCOE objective
    lcoe_obj_idx = find(which_objs == 1, 1);
    if ~isempty(lcoe_obj_idx) && ~isempty(fmincon_outputs{lcoe_obj_idx})
        out_lcoe = fmincon_outputs{lcoe_obj_idx};
        end_result_struct.singleObjIters = out_lcoe.total_iterations;
        end_result_struct.singleObjFcnEvals = out_lcoe.total_funcCount;
    else
        end_result_struct.singleObjIters = NaN;
        end_result_struct.singleObjFcnEvals = NaN;
    end
    end_result_struct.singleObjRuntime = intermed_result_struct.singleObjRuntime;

    % Force saturation: compare optimal design with and without force saturation applied
    X_opt_LCOE = Xs_opt(:, which_objs==1);
    p_nosat = p;
    p_nosat.use_force_sat = false;
    [J_nosat, ~, ~, val_nosat] = simulation(X_opt_LCOE, p_nosat);
    LCOE_nosat = J_nosat(1);
    % power lost due to force saturation (val = with sat, val_nosat = without sat)
    end_result_struct.powerLossForceSatMinLCOE = val_nosat.power_avg - val.power_avg;
    end_result_struct.pctPowerLossForceSatMinLCOE = (val_nosat.power_avg - val.power_avg) / val_nosat.power_avg * 100;
    end_result_struct.pctPTOSavingsForceSatMinLCOE = (val_nosat.capex_PTO - val.capex_PTO) / val_nosat.capex_PTO * 100;
    end_result_struct.pctImproveLCOEForceSatMinLCOE = (LCOE_nosat - val.LCOE) / LCOE_nosat * 100;

    % Generate qualitative description of optimal design compared to nominal
    bulk_dims = ["D_s","D_f","T_f_2","h_s","h_fs_clear"];
    pto_vars = ["F_max","P_max"];
    struct_vars = ["t_fb","t_sr", "t_d","h_stiff_f","h1_stiff_d"];

    idx_bulk = ismember(b.var_names,bulk_dims);
    idx_pto = ismember(b.var_names,pto_vars);
    idx_struct = ismember(b.var_names,struct_vars);

    bulk_ratio = Xs_opt(idx_bulk,which_objs==1) ./ b.X_noms(idx_bulk);
    pto_ratio = Xs_opt(idx_pto,which_objs==1) ./ b.X_noms(idx_pto);
    struct_ratio = Xs_opt(idx_struct,which_objs==1) ./ b.X_noms(idx_struct);

    check_results = false;
    desc = "";
    if all(bulk_ratio > 1)
        desc = desc + "larger in all bulk dimensions";
    else
        bulk_dims
        Xs_opt(idx_bulk,which_objs==1).'
        b.X_noms(idx_bulk).'
        warning("Bulk dimensions are no longer all larger after optimization. Check results qualitatively to ensure accurate interpretation.");
        check_results = true;
    end
    if all(pto_ratio > 0.75 & pto_ratio < 1.25)
        desc = desc + " with a similarly sized PTO";
    else
        pto_vars
        Xs_opt(idx_pto,which_objs==1).'
        b.X_noms(idx_pto).'
        warning("PTO dimensions are no longer all within 25% of the nominal after optimization. Check results qualitatively to ensure accurate interpretation.");
        check_results = true;
    end
    if all(struct_ratio < 1)
        desc = desc + " and smaller structural thicknesses";
    else
        struct_vars
        Xs_opt(idx_struct,which_objs==1).'
        b.X_noms(idx_struct).'
        warning("Structural thicknesses are no longer all smaller after optimization. Check results qualitatively to ensure accurate interpretation.");
        check_results = true;
    end

    if check_results
        desc = NaN;
    end
    end_result_struct.optDesignDescriptionMinLCOE = desc;