%[AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
    
    p = intermed_result_struct.p;
    b = intermed_result_struct.b;
    which_objs = intermed_result_struct.which_objs;
    Xs_opt = intermed_result_struct.Xs_opt;
    objs_opt = intermed_result_struct.objs_opt;
    flags = intermed_result_struct.flags;
    lambdas = intermed_result_struct.lambdas;
    grads = intermed_result_struct.grads;
    hesses = intermed_result_struct.hesses;

    [fig_array,tab] = SOO_result_plots(Xs_opt,lambdas,grads,hesses,objs_opt,which_objs,p,b);
    
    fig_array(end+1) = intermed_result_struct.convergence_plot;

    tab_array_display = {tab};
    tab_array_latex = {tab};
    
    tab_firstrows = {[]};
    tab_colspecs = {[]};
    
    [~,~,~,val] = simulation(Xs_opt,p);

    end_result_struct.convergence_achieved = all(flags > 0);
    end_result_struct.minLCOE = objs_opt(1,which_objs==1);
    end_result_struct.powerAvgAtMinLCOE = val.power_avg;
    end_result_struct.powerMaxAtMinLCOE = val.power_max;
    end_result_struct.forceMaxAtMinLCOE = val.force_heave;
    end_result_struct.structMassAtMinLCOE = val.mass_tot;
    end_result_struct.capexAtMinLCOE = val.capex;
    end_result_struct.capexDesignAtMinLCOE = val.capex_design;
    end_result_struct.DfoptMinLCOE = Xs_opt(b.var_names=="D_f",which_objs==1);
    end_result_struct.surgeForceFloatAtMinLCOE = val.force_surge(1);
    end_result_struct.surgeForceSparAtMinLCOE = val.force_surge(2);
    end_result_struct.lowestFmaxFactorMinLCOE = NaN; % fixme
    end_result_struct.lowestFsatMinLCOE = NaN; % fixme

    % Generate qualitative description of optimal design compared to nominal
    bulk_dims = ["D_s","D_f","T_f_2","h_s","h_fs_clear"];
    pto_vars = ["F_max","P_max"];
    struct_vars = ["t_fb","t_sr", "t_d","h_stiff_f","h1_stiff_d"];

    idx_bulk = ismember(b.var_names,bulk_dims);
    idx_pto = ismember(b.var_names,pto_vars);
    idx_struct = ismember(b.var_names,struct_vars);

    bulk_ratio = Xs_opt(idx_bulk,which_objs==1) ./ b.X_noms(idx_bulk);
    pto_ratio = Xs_opt(idx_pto,which_objs==1) ./ b.X_noms(idx_pto);
    struct_ratio = Xs_opt(idx_struct,which_objs==1) ./ b.X_noms(idx_struct);

    check_results = false;
    desc = "";
    if all(bulk_ratio > 1)
        desc = desc + "larger in all bulk dimensions";
    else
        bulk_dims
        Xs_opt(idx_bulk,which_objs==1).'
        b.X_noms(idx_bulk).'
        warning("Bulk dimensions are no longer all larger after optimization. Check results qualitatively to ensure accurate interpretation.");
        check_results = true;
    end
    if all(pto_ratio > 0.75 & pto_ratio < 1.25)
        desc = desc + " with a similarly sized PTO";
    else
        pto_vars
        Xs_opt(idx_pto,which_objs==1).'
        b.X_noms(idx_pto).'
        warning("PTO dimensions are no longer all within 25% of the nominal after optimization. Check results qualitatively to ensure accurate interpretation.");
        check_results = true;
    end
    if all(struct_ratio < 1)
        desc = desc + " and smaller structural thicknesses";
    else
        struct_vars
        Xs_opt(idx_struct,which_objs==1).'
        b.X_noms(idx_struct).'
        warning("Structural thicknesses are no longer all smaller after optimization. Check results qualitatively to ensure accurate interpretation.");
        check_results = true;
    end

    if check_results
        desc = NaN;
    end
    end_result_struct.optDesignDescriptionMinLCOE = desc;