%[DOCS AUTOGENERATED]
function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct,...
                 tab_firstrows,...
                 tab_colspecs] = post_process_fcn(intermed_result_struct)
% Function post_process_fcn
%
% :param intermed_result_struct: Intermediate results struct (cached heavy analyses)
% :returns: fig_array
% :returns: tab_array_display
% :returns: tab_array_latex
% :returns: end_result_struct
% :returns: tab_firstrows
% :returns: tab_colspecs
            
            figs = pareto_curve_heuristics(intermed_result_struct.r1, ...
                                           intermed_result_struct.r2);
            
            % Get the figures created by pareto functions
            pareto_heuristics_fig = figs(6);
            pareto_heuristics_nondim_fig = figs(8);
            pareto_lcoe_tangent_contours_fig = figs(9);
            pareto_front_with_design_images_fig = figs(4);
            pareto_front_LCOE_contours_fig = figs(3);
            pareto_constraint_activity_fig_damping = figs(1);
            pareto_constraint_activity_fig_reactive = figs(7);
            
            % Adjust figure position
            pareto_constraint_activity_fig_damping.Position  = [1 41 1536 844.8000];
            pareto_constraint_activity_fig_reactive.Position = [1 41 1536 844.8000];
            
            fig_array = [pareto_front_with_design_images_fig, ...
                        pareto_front_LCOE_contours_fig, ...
                        pareto_heuristics_fig, ...
                        pareto_heuristics_nondim_fig, ...
                        pareto_lcoe_tangent_contours_fig, ...
                        pareto_constraint_activity_fig_damping, ...
                        pareto_constraint_activity_fig_reactive];
            
            tab_array_display = {};
            tab_array_latex = {};
            
            tab_firstrows = {};
            tab_colspecs = {};
            
            end_result_struct.paretoPctTimeSeeds = intermed_result_struct.paretoPctTimeSeeds;
            end_result_struct.paretoPctTimePatternSearch = intermed_result_struct.paretoPctTimePatternSearch;
            end_result_struct.paretoRuntime = intermed_result_struct.paretoTotalRuntime;
            end_result_struct.paretoFcnEvals = intermed_result_struct.paretoFcnEvals;

            % Compute pareto shape heuristics
            b = var_bounds();
            % [powerWhereCusp, powerWhereNonconvexEnds, dampingReactivePowerIntersect] = ...
            %     compute_pareto_shape_heuristics(intermed_result_struct.r1, intermed_result_struct.r2, ...
            %                                     intermed_result_struct.r1.p, b);
            % end_result_struct.powerWhereCusp = powerWhereCusp;
            % end_result_struct.powerWhereNonconvexEnds = powerWhereNonconvexEnds;
            % end_result_struct.dampingReactivePowerIntersect = dampingReactivePowerIntersect;
end
