%[DOCS AUTOGENERATED]
function [C,h_fig] = contourx(X_data,Y_data,Z_data,varargin)
% Function contourx
%
% :param X_data: X_data
% :param Y_data: Y_data
% :param Z_data: Z_data
% :param varargin: varargin
% :returns: C
% :returns: h_fig
% wrapper around contourf that avoids "contour not rendered for constant
% zdata" warning by using imagesc when Z is constant

    Z_is_constant = numel(unique(Z_data(~isnan(Z_data)))) == 1;

    if Z_is_constant
        x = [min(X_data,[],'all') max(X_data,[],'all')];
        y = [min(Y_data,[],'all') max(Y_data,[],'all')];
        h_fig = imagesc('XData',x,'YData',y,'CData',Z_data,'AlphaData',~isnan(Z_data));
        C = [];
    else
        [C,h_fig] = contourf(X_data,Y_data,Z_data,varargin{:});
    end
end
