%[DOCS AUTOGENERATED]
function [diagnostic] = save_fig_with_diagnostic(fig, fig_name, pdf_prefix)
% Function save_fig_with_diagnostic
%
% :param fig: Figure handle
% :param fig_name: fig_name
% :param pdf_prefix: pdf_prefix
% :returns: diagnostic
% saves a pdf of a figure, robustly handling cases of gobjects, deleted
% handles, and invalid figures
    
    if nargin<3
        pdf_prefix = '';
    end
    % Coerce inputs to single string/char to avoid passing string arrays
    fig_name = char(string(fig_name));
    pdf_prefix = char(string(pdf_prefix));
    pdf_name = char([fullfile(pdf_prefix, fig_name) '.pdf']);
    
    if isgraphics(fig) % if figure exists (didn't error first and wasn't deleted)
        if ~isempty(fig.UserData) && (ischar(fig.UserData) || isstring(fig.UserData))
            % pdf already exists in files, just copy to folder
            src = char(string(fig.UserData));
            try
                copyfile(src, pdf_name);
            catch
                warning([src ' does not exist, saving image to results folder.']);
                % Try export with sanitized filename; if it fails, retry minimal call and report
                try
                    exportgraphics(fig, pdf_name);
                catch ex
                    % Retry with char coercion and minimal args
                    try
                        exportgraphics(fig, char(string(pdf_name)));
                    catch
                        rethrow(ex)
                    end
                end
            end
        else
            fig = check_fig_size(fig);
            % save .fig for later editing
            try
                savefig(fig, [fullfile(pdf_prefix, fig_name) '.fig']);
            catch
                % if savefig fails for unexpected input types, coerce and retry
                savefig(fig, char(string(fullfile(pdf_prefix, fig_name) + '.fig')));
            end

            % save pdf from matlab figure output; guard against passing string arrays
            try
                exportgraphics(fig, pdf_name);
            catch ex
                % Retry with coerced char filename
                try
                    exportgraphics(fig, char(string(pdf_name)));
                catch
                    rethrow(ex)
                end
            end
        end

        if nargout>0
            % in either case, use figure itself, not pdf, for printing the diagnostic
            diagnostic = matlab.unittest.diagnostics.FigureDiagnostic(fig,'Prefix',fig_name + '_');
        end

    elseif ~isvalid(fig)
        msg = 'Figure has been deleted, probably because of a "close all" in a subsequent script.';
        err = MException('MDOcean:deletedFigure',msg);
        throw(err)

    else % placeholder gobjects figure - don't save
        if nargout > 0
            diagnostic = matlab.unittest.diagnostics.DisplayDiagnostic('');
        end
    end   
end
