%[DOCS AUTOGENERATED]
function [diagnostic] = save_fig_with_diagnostic(fig, fig_name, pdf_prefix)
% Function save_fig_with_diagnostic
%
% :param fig: Figure handle
% :param fig_name: fig_name
% :param pdf_prefix: pdf_prefix
% :returns: diagnostic
% saves a pdf of a figure, robustly handling cases of gobjects, deleted
% handles, and invalid figures
    
    if nargin < 2 || isempty(fig_name)
        fig_name = "unnamed_figure";
    end
    fig_name = string(fig_name);
    fig_name = fig_name(1);

    if nargin < 3 || isempty(pdf_prefix)
        pdf_prefix = '';
    end
    pdf_prefix = string(pdf_prefix);
    pdf_prefix = pdf_prefix(1);

    base_name = string(fullfile(char(pdf_prefix), char(fig_name)));
    pdf_name = base_name + ".pdf";
    fig_file = base_name + ".fig";
    
    if isgraphics(fig) % if figure exists (didn't error first and wasn't deleted)
        if ~isempty(fig.UserData) && ischar(fig.UserData)
            % pdf already exists in files, just copy to folder
            try
                copyfile(fig.UserData, pdf_name)
            catch
                warning([fig.UserData ' does not exist, saving image to results folder.'])
                exportgraphics(fig, pdf_name) % if pdf does not exist, save the image
            end
        else
            fig = check_fig_size(fig);
            % save .fig for later editing
            savefig(fig, fig_file)
            
            % save pdf from matlab figure output
            exportgraphics(fig, pdf_name)
        end

        if nargout>0
            % in either case, use figure itself, not pdf, for printing the diagnostic
            diagnostic = matlab.unittest.diagnostics.FigureDiagnostic(fig, 'Prefix', char(fig_name + "_"));
        end

    elseif ~isvalid(fig)
        msg = 'Figure has been deleted, probably because of a "close all" in a subsequent script.';
        err = MException('MDOcean:deletedFigure',msg);
        throw(err)

    else % placeholder gobjects figure - don't save
        if nargout > 0
            diagnostic = matlab.unittest.diagnostics.DisplayDiagnostic('');
        end
    end   
end
