%[DOCS AUTOGENERATED]
function cb = signed_log(Z_data,C,levels,X_data,Y_data,contour_on)
% Function signed_log
%
% :param Z_data: Z_data
% :param C: C
% :param levels: levels
% :param X_data: X_data
% :param Y_data: Y_data
% :param contour_on: contour_on
% :returns: cb
% modified from the following
% https://www.mathworks.com/matlabcentral/answers/1700655-symmetric-diverging-log-color-scale#answer_1380451
    
    % assign default arguments if not provided
    if nargin<2
        C = [];
    end
    if nargin<3
        levels = [];
    end
    if nargin<4
        use_XY = false;
    elseif nargin>=5
        use_XY = true;
    else
        error('Wrong number of input arguments')
    end
    if nargin<6
        contour_on = false;
    end


    if isempty(C)
        % controls smallest order of magnitude near zero
        if all(Z_data==0,'all') 
            C = 1;
        else
            C = log10(min(nonzeros(abs(Z_data)),[],'all')) - 1; 
        end
    end

    % capital Z is the data, lowercase z is the signed-log-transformed data
    z = signedlog10cont(Z_data,C); 

    % get the maximum value of abs(Z)
    Z_range = max(abs(imrange(Z_data(~isinf(Z_data)))));
    if Z_range==0
        Z_range = 1;
    end

    % get color range. this needs to be symmetric unless you also make a 
    % custom asymmetric divergent colormap
    % the bluewhitered colormap is smart and adjusts to all pos/neg so need
    % to account for this in crange.
    if all(z>=0,'all')
        c_ends = [0 1];
    elseif all(z<=0,'all')
        c_ends = [-1 0];
    else
        c_ends = [-1 1];
    end
    crange_Z = Z_range * c_ends;
    crange_z = signedlog10cont(crange_Z,C);

    round = true; % control whether to round up colorbar to integer exponent
    if round
        crange_z = c_ends + fix(crange_z);
    end

    % create ticks, ticklabels
    % choose nticks as desired
    if ~isempty(levels)
        % add the maximum abs value to the specified levels to avoid unfilled 
        % color between [-Inf levels(1)]
        pos_tick_Z_values = sort([Z_range levels]);
    else % find levels automatically if not provided
        max_nticks = 17;
        min_expo = floor(C)+1;
        max_expo = max(crange_z);
        nticks_temp = max_expo - min_expo + 1;
        if all(c_ends==[-1 1])
            nticks_temp = nticks_temp * 2; % account for negative and positive ticks
        end
        count_by = ceil(nticks_temp/max_nticks);
        expos = min_expo:count_by:max_expo;
        pos_tick_Z_values = 10.^expos;
        if ~all(isfinite(pos_tick_Z_values))
            pos_tick_Z_values = [];
        end
    end

    % set Ticks and TickLabels
    tick_Z_values = [-flip(pos_tick_Z_values) 0 pos_tick_Z_values]; % make symmetric
    tick_z_values = signedlog10cont(tick_Z_values,C);
    tick_labels = tick_Z_values;

    jf = java.text.DecimalFormat;
    format_tick_fcn = @(v) char(jf.format(v));
    format_tick_array = @(v) arrayfun(@(s) string([format_tick_fcn(s) '%']),  invsignedlog10cont(v,C));

    % plot z - use contourf if X and Y are provided, imagesc if not  
    if use_XY
        contourf(X_data,Y_data,z,'LevelList',tick_z_values,...
                'ShowText',contour_on,'LabelFormat',format_tick_array);
    else
        imagesc(z)
    end

    % add colorbar with tick labels
    cb = colorbar('Ticks',unique(tick_z_values));
    cb.TickLabels = arrayfun(format_tick_fcn, unique(tick_labels), 'UniformOutput', false);
    % set limits for the caxis 
    caxis(crange_z); % represented in signed log10

    % use a symmetric colormap
    colormap(gca(), bluewhitered())

    improvePlot
    %axis square
end

function out = signedlog10cont(in,C)
    % modified continuous signed-log
    % see Measurement Science and Technology (Webber, 2012)  
    % allows for negative exponents up to C
    out = sign(in).*(log10(1+abs(in)/(10^C)));
end

function out  = invsignedlog10cont(in,C)
    % inverse of the above function
    out = sign(in) .* ( 10.^(abs(in)) - 1 ) * (10^C);
end