%[AUTOGENERATED]
function write_vars_to_tex(varargin)

    % Open the file for writing
    fid = fopen('pubs/journal-paper/numbers.tex', 'w');
% Function fopen
%
% :param 'pubs/journal-paper/numbers.tex': 'pubs/journal-paper/numbers.tex'
% :param 'w': 'w'
% :returns: write_vars_to_tex(varargin) fid

    % Write the LaTeX commands for each variable
    for i = 1:nargin
        fprintf(fid, '\\newcommand{\\%s}{%g}\n', inputname(i), varargin{i});
    end

    % Close the file
    fclose(fid);
end