function [a_q,b_q,c_q] = get_abc_symbolic(f,m,b,k,w,r_b,r_k)
%GET_ABC_SYMBOLIC
%    [A_Q,B_Q,C_Q] = GET_ABC_SYMBOLIC(F,M,B,K,W,R_B,R_K)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    17-Jul-2022 15:04:03

t2 = b.^2;
t3 = f.^2;
t4 = k.^2;
t5 = m.^2;
t6 = r_b.^2;
t7 = r_k.^2;
t8 = w.^2;
t9 = t8.^2;
t11 = k.*m.*t8.*2.0;
t12 = t2.*t8;
t15 = k.*m.*r_k.*t8.*-2.0;
t16 = k.*m.*r_b.*r_k.*t8.*4.0;
t10 = t5.*t9;
t13 = -t11;
a_q = -t3.*(t4+t12+r_b.*t4.*2.0+r_k.*t12.*2.0+t4.*t6+t7.*t12)+(r_b+1.0).^2.*(r_k+1.0).^2.*(t4+t10+t12+t13);
if nargout > 1
    b_q = t3.*(t11+t16-r_b.*t12.*2.0-r_k.*t4.*2.0-r_b.*r_k.*t4.*4.0-r_b.*r_k.*t12.*4.0-r_b.*t7.*t12.*2.0-r_k.*t4.*t6.*2.0+k.*m.*r_b.*t8.*4.0+k.*m.*r_k.*t8.*2.0+k.*m.*t6.*t8.*2.0+k.*m.*r_k.*t6.*t8.*2.0);
end
if nargout > 2
    t14 = r_k.*t11;
    t17 = -t16;
    t19 = t6.*t15;
    c_q = -t3.*(t10+t15+t17+t19+r_b.*t10.*2.0+r_k.*t10.*2.0+t4.*t7+t6.*t10+t7.*t10+t6.*t12+r_b.*r_k.*t10.*4.0+r_b.*t4.*t7.*2.0+r_b.*t7.*t10.*2.0+r_k.*t6.*t10.*2.0+r_k.*t6.*t12.*2.0+t4.*t6.*t7+t6.*t7.*t10+t6.*t7.*t12-k.*m.*t7.*t8.*2.0-k.*m.*r_b.*t7.*t8.*4.0-k.*m.*t6.*t7.*t8.*2.0);
end
