classdef ReadNonMatlabFigs < GenericAnalysis
    %READNONMATLABFIGS Analysis class for non-MATLAB figure reading
    %   Reads external image files and creates MATLAB figures
    
    properties
        fig_names = {'control_analysis_flowcharts',...
                    'damping_plate_flowchart',...
                    'dimensions',...
                    'equivalent_stiffness',...
                    'FBD',...
                    'graphical_abstract_modeling',...
                    'MEEM_geometry',...
                    'methodology_flowchart',...
                    'N2_diagram',...
                    'graphical_abstract_optim',...
                    'optimization_flowchart',...
                    'RM3_image',...
                    'sim_runtime', ...
                    'trapezoid',...
                    };
        tab_names = {};
    end
    
    methods (Static)
        
        function intermed_result_struct = analysis_fcn(~,~)
            % Store file information for post-processing

            intermed_result_struct.file_names = {...
                            'control_analysis_flowcharts.png',...
                            'damping_plate_flowchart.png',...
                            'dimensions.jpg',...
                            'equivalent_stiffness.png',...
                            'FBD.jpg',...
                            'graphical_abstract_modeling.png',...
                            'MEEM_geometry.jpg',...
                            'methodology_flowchart.png',...
                            'N2_diagram.JPG',...
                            'graphical_abstract_optim.JPG',...
                            'optimization_flowchart.jpg',...
                            'RM3_image.png',...
                            'sim_runtime.png',...
                            'trapezoid.png',...
                            };
        end
        
        function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct] = post_process_fcn(intermed_result_struct)
            
            num_figs = length(intermed_result_struct.file_names);
            fig_array = gobjects(1,num_figs);
            
            % Loop over the requested figure names
            for i = 1:num_figs
                file_name = intermed_result_struct.file_names{i};
                
                % Create the figure and read in the image file
                fig = figure;
                try
                    imshow(imread(file_name), 'Parent', axes(fig));
                catch
                    % If image file doesn't exist, create a placeholder
                    warning(['Missing image file (pdf may still exist): ' file_name])
                    text(0.5, 0.5, ['Missing: ' file_name], 'HorizontalAlignment', 'center');
                end
                fig.UserData = ['mdocean/plots/non_matlab_figs/pdf/' file_name(1:end-4) '.pdf'];
                % save_fig_with_diagnostic.m uses UserData, if it exists,
                % as the source of the pdf to save to results. This
                % ensures that the image is only used for the
                % diagnostic saved to the test report, and the latex
                % document uses the higher quality pdf.
                fig_array(i) = fig;
            end
            
            tab_array_display = {};
            tab_array_latex = {};
            
            end_result_struct.num_figs_created = length(fig_array);
        end
        
    end
end
