classdef ReadNonMatlabFigs < GenericAnalysis
    %READNONMATLABFIGS Analysis class for non-MATLAB figure reading
    %   Reads external image files and creates MATLAB figures

    properties
        fig_names = {'RM3_image','methodology_overview','N2_diagram',...
                    'dimensions','MEEM_geometry','WECSim_error_breakdown', ...
                    'FBD', 'sim_runtime', 'optimization_flowchart', 'equivalent_stiffness', ...
                    'trapezoid', 'damping_plate_flowchart', 'graphical_abstract'};
        tab_names = {};
    end

    methods (Static)

        function intermed_result_struct = analysis_fcn(~,~)
            % Store file information for post-processing
            intermed_result_struct.fig_names = {'RM3_image','methodology_overview','N2_diagram',...
                        'dimensions','MEEM_geometry','WECSim_error_breakdown', ...
                        'FBD', 'sim_runtime', 'optimization_flowchart', 'equivalent_stiffness', ...
                        'trapezoid', 'damping_plate_flowchart', 'graphical_abstract'};
            intermed_result_struct.file_names = {'geometry.png',...
                            'methods_flowchart_2_cropped.jpg',...
                            'xdsm.JPG',...
                            'dimensions.jpg',...
                            'MEEM-dims-basic-3.jpg',...
                            'Error_Accumulation_AEP.png',...
                            'structures_FBDs_4.jpg',...
                            'time_breakdown_3.png',...
                            'optim_process_flowchart_cropped.jpg',...
                            'equivalent_stiffness.png',...
                            'trapezoid.png',...
                            'damping_plate_flowchart.png',...
                            'graphical_abstract.png'};
        end

        function [fig_array,...
                 tab_array_display,...
                 tab_array_latex,...
                 end_result_struct] = post_process_fcn(intermed_result_struct)

            fig_array = [];

            % Loop over the requested figure names
            for i = 1:length(intermed_result_struct.fig_names)
                fig_name = intermed_result_struct.fig_names{i};
                file_name = intermed_result_struct.file_names{i};

                % Create the figure and read in the image file
                fig = figure;
                try
                    imshow(imread(file_name), 'Parent', axes(fig));
                    fig.UserData = ['plots/non_matlab_figs/' file_name(1:end-4) '.pdf'];
                catch
                    % If file doesn't exist, create a placeholder
                    text(0.5, 0.5, ['Missing: ' file_name], 'HorizontalAlignment', 'center');
                end
                fig_array = [fig_array, fig];
            end

            tab_array_display = {};
            tab_array_latex = {};

            end_result_struct.num_figs_created = length(fig_array);
        end

    end
end
