name: Ready to merge
description: Check version + changelog updated
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check validity of citation.cff
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "-i ./CITATION.cff -f zenodo --validate --show-trace"
      - name: Check for changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            version:
                - 'mdocean/__version__.py'
            changelog:
                - 'CHANGELOG.md'
      - name: Fail if version/changelog not bumped
        if: steps.changes.outputs.version == 'false' || steps.changes.outputs.changelog == 'false'
        run: exit 1
