name: Create GitHub Release

on:
  push:
    branches:
      - main
      - fix-ci-trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Extract version
        id: get_version
        run: echo "version=$(grep __version__ mdocean/__version__.py | cut -d '\"' -f2)" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: v${{ steps.get_version.outputs.version }}
            generate_release_notes: true