name: "Sphinx: Render docs"

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/sphinx.yml'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Build HTML
      uses: ammaraskar/sphinx-action@8.2.3
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: html-docs
        path: docs/_build/html/
    - name: Deploy # this pushes to the gh-pages branch, so Github's pages workflow will pick it up and create the website
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html