function [var_names] = wecsim_var_names()
    var_names = {'P',...
                'force_pto',...
                'float_amplitude',...
                'spar_amplitude',...
                'relative_amplitude',...
                'float_amplitude_rms',...
                'spar_amplitude_rms',...
                'relative_amplitude_rms',...
                'float_amplitude_fund',...
                'spar_amplitude_fund',...
                'rel_amplitude_fund',...
                'float_drag_force_fund',...
                'spar_drag_force_fund',...
                'float_drag_force_phase',...
                'spar_drag_force_phase',...
                'float_phase',...
                'spar_phase',...
                'rel_phase',...
                'X',...
                'p',...
                'B_p',...
                'K_p',...
                'git_hash',...
                'float_accel_ts',...
                'float_drag_ts',...
                'corner_HT',...
                'corner_N_per_T',...
                'dt_sim'};
end

